### ISSUE TITLE
List Organisation in alphabetical order for new users

### ISSUE THREAD

**Issue by pszemekd** [MISP/MISP#989] opened 2016-03-01 12:46 UTC
When creating new users, Organistations list is not sorted. Would be nice if there would be implemented alphabetical order of listed Orgs.

**Comment by elhoim** [comment] 2016-03-01 13:37
Duplicate of https://github.com/MISP/MISP/issues/918
Already fixed in 40b348e

**Comment by pszemekd** [comment] 2016-03-09 16:04
It is not fixed. Not duplicated - another issue... :(

**Closed as completed** 2016-03-09 16:18 UTC
Labels: T: enhancement, usability
