### ISSUE TITLE
Internal Error at /tags/index on fresh installation

### ISSUE THREAD

**Issue by AJohnDoe** [MISP/MISP#2898] opened 2018-02-01 01:13 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 9.3
| PHP version               | 7.0
| MISP version / git hash   | v2.4.84-17-g5a84d485

### Expected behavior
Tags should be listed at /tags/index

### Actual behavior
An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

### Steps to reproduce the behavior
* Create fresh installation of MISP following [the setup guide](https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.debian9.txt), replacing line 60 with

    `sudo -u www-data git checkout tags/v2.4.84-17-g5a84d485`

* Login to MISP, navigate to /tags/index
* Note that the error is not present on `v2.4.84-16-g3eba527e`

### Logs, screenshots, configuration dump, ...

debug.log:
```
2018-02-01 08:45:40 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Tag.user_id' in 'on clause'
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('SELECT `Tag`.`i...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(673): DboSource->execute('SELECT `Tag`.`i...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1184): DboSource->fetchAll('SELECT `Tag`.`i...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3038): DboSource->read(Object(Tag), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/PaginatorComponent.php(196): Model->find('all', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(1089): PaginatorComponent->paginate(Object(Tag), Array, Array)
#8 /var/www/MISP/app/Controller/TagsController.php(70): Controller->paginate()
#9 [internal function]: TagsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
```

**Comment by adulau** [comment] 2018-02-02 07:59
Should be fixed in https://github.com/MISP/MISP/commit/5e04ac97f94e7455efdfe1a0bebdc94fdcd914c8 Thanks for the notification!

**Closed as completed by adulau** 2018-02-02 07:59 UTC

**Comment by airlinedev** [comment] 2018-02-07 03:36
@adulau is it possible to provide instructions on upgrading to this commit that fixes this bug without having to do a fresh install?

**Comment by timhperrin** [comment] 2018-02-08 16:45
not fixed

**Comment by adulau** [comment] 2018-02-08 17:41
@timhperrin Just tested with fresh install from bc81448b5f73d9f102eb690e2d181602e18e8d79 - I tried without tags, with custom tags and tags from taxonomy.  I cannot reproduce it. I tested with the VM generated from the latest commit. https://www.circl.lu/misp-images/latest/ 

Could you test and let me know? thank you
