### ISSUE TITLE
Click "Show XXX more..." to make no difference.

### ISSUE THREAD

**Issue by kaien** [MISP/MISP#4819] opened 2019-07-01 09:26 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Windows 10
| PHP version               | 7.2
| MISP version / git hash   | v2.4.109 (08e7ca34b84fdbade732d42dc4883f7ebaf991a6) 
| Browser                   | Chrome

### Expected behavior
When you click "Show XXX more..." an additional "Related Events" entry should appear.

### Actual behavior
Click "Show XXX more..." to make no difference.

### Steps to reproduce the behavior
Occurs when there are many attributes entries in "https://localhost/events/view/xxx".
When you click "Show XXX more..." on the first page, it will work normally.
From page 2, however, clicking the "Show XXX more..." button will not respond.

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/5023329/60425469-92b04e00-9c2d-11e9-85f0-6bb932b5d116.png)

**Comment by SteveClement** [comment] 2019-07-02 06:27
I cannot reproduce this, could you try to update to the latest version?

**Comment by JakubOnderka** [comment] 2020-07-04 10:58
Should be fixed in 7a50616226bce30646eaf4220441203ffa07f45e

**Closed as completed** 2020-07-20 08:29 UTC
Labels: R: cannot reproduce
