### ISSUE TITLE
Cannot enable defailt Circl Feed

### ISSUE THREAD

**Issue by gossykid** [MISP/MISP#1667] opened 2016-11-15 12:13 UTC
Hello
After the installation I would like to enable the default feed "CIRCL OSINT Feed". I have enabled the respective Taxonomy Tags. When I try to enable the feed I got the following error message:
"Feed could not be updated. Invalid fields: event_id"

Is this a bug? Any help is highly appreciated.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug? 
| OS version (server)       | RedHat
| OS version (client)       | EL7
| PHP version               | 5.6.5
| MISP version / git hash   | 2.4.54
| Browser                   | IE11 & Firefox

**Comment by iglocska** [comment] 2016-11-15 13:13
This should be fixed by https://github.com/MISP/MISP/commit/b1ab540f4fa5c2d683666f2fa1116d516c77b388, could you git pull to the lastest commit on the 2.4 branch and see if the issue persists?

**Comment by adulau** [comment] 2016-11-17 14:24
This was fixed in b1ab540f4fa5c2d683666f2fa1116d516c77b388 and tested. If the issue is still there, please reopen the issue. Thank you.

**Closed as completed by adulau** 2016-11-17 14:24 UTC
