### ISSUE TITLE
Bug: Search attributes, "next" button doesn't work

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#9208] opened 2023-07-25 08:03 UTC
### Expected behavior

Have a set of attributes returned in the attribute search, use the **next** (or last) button to get to the next page of search results.

### Actual behavior

Clicking the next button (which has page:2) returns back to the Search Attributes form.
The last button has page:153722867280912928 (which is not correct, there are approx. 1000 attributes matching the search criteria), and also returns back to the Search Attributes form.

### Steps to reproduce

Search for attributes, specify a tag as a search criteria. Use a tag that is common on attributes.

### Version

2.4.173

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment] 2023-07-26 07:40
duplicate of #9157

**Closed as completed by righel** 2023-07-26 07:40 UTC
Labels: R: duplicate

**Comment by righel** [comment] 2023-07-26 07:48
The last button high number is a hack to make the `LightPaginator` more performant as it avoids doing additional `count()` SQL queries, see: https://github.com/MISP/MISP/blob/dc4236ef9b52364ed6660117ae321fff9a244b70/app/Model/Behavior/LightPaginatorBehavior.php#L17
