### ISSUE TITLE
"disable_correlation" does not work with a new object template

### ISSUE THREAD

**Issue by ogmasec** [MISP/MISP#3504] opened 2018-07-23 00:55 UTC
### Description
After creating a new object template, MISP doesn't consider the parameter `disable_correlation`.
Setting this up `true `or `false` doesn't change anything when inserting an object, _the correlation check box is checked_.

**Please see attachment**

### MISP object
![image](https://user-images.githubusercontent.com/40192406/43052094-795eaaae-8e65-11e8-93e5-6e1d8e7154af.png)

### Object template:

```
{
  "required": [
    "threat_score"
  ],
  "attributes": {
    "threat_score": {
      "description": "threat_score",
      "disable_correlation": true,
      "categories": [
        "External analysis"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "heuristic_raw_score": {
      "description": "heuristic_raw_score",
      "disable_correlation": true,
      "categories": [
        "External analysis"
      ],
      "ui-priority": 1,
      "misp-attribute": "text"
    },
    "heuristic_score": {
      "description": "heuristic_score",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "analysis_submitted_at": {
      "description": "Submission date",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "datetime"
    },
    "original_filename": {
      "description": "Original filename",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "permalink": {
      "description": "permalink date",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "id": {
      "description": "ThreatGrid ID",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "sha256": {
      "description": "sha256",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "sha1": {
      "description": "sha1",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "md5": {
      "description": "md5",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
      "misp-attribute": "text"
    },
    "iocs": {
      "description": "iocs",
      "disable_correlation": true,
      "categories": [
        "Other"
      ],
      "ui-priority": 0,
	  "multiple": true,
      "misp-attribute": "text"
    }
  },
  "version": 10,
  "description": "ThreatGrid report",
  "meta-category": "misc",
  "uuid": "23b3576b-2e68-4a86-a103-68820daef1d5",
  "name": "threatgrid-report"
}
```

**Comment by RichieB2B** [comment] 2018-07-25 10:06
Confirmed.. very nasty bug. :-(

**Comment by mokaddem** [comment] 2018-11-21 15:34
Hello @ogmasec, 
We recently fixed a bug related to the ``disable_correlation``.
I tried to reproduce your bug without success.
I created a new custom object with your provided template. Once added, the **Correlate** checkbox is not checked (which is the correct behavior).
If this bug still there for you, could you please provide more guidance to reproduce it?
Thanks a lot.

**Comment by SteveClement** [comment] 2019-02-04 06:03
Closing due to non-activity.

Feel free to re-open with updated content.

**Closed as completed by SteveClement** 2019-02-04 06:03 UTC
Labels: T: potential bug, S: under investigation, S: review before closing, performance, confirmed
