### ISSUE TITLE
misp-modules install: python cannot import yara: OSError libpcre.so.3

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3238] opened 2018-05-08 13:35 UTC
attempting to get misp-modules installed and being challenging getting yara to work.

hoping someone can offer the magic potion. thanks!!

we've installed yara-3.4.0, yara-python, pcre-8.42 (and then also pcre2-10.31 just in case) on CentOS 7 (Linux version 3.10.0-693.11.6.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Jan 4 01:06:37 UTC 2018). and when testing the install by attempting to import yara in python 3.6.4 we get this OSError:

```$ python3
python3
Python 3.6.4 (default, Dec 19 2017, 14:48:12)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
Failed to import '/usr/lib/libyara.so'
PATH = /home/mg973b/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/rh/rh-php71/root/usr/bin:/usr/local/sbin:/opt/rh/rh-php71/root/usr/bin:/opt/sims/db/bin/pyX:/home/mg973b/git/sp_flgit/bin;/usr/lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/lib/python3.6/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/lib/python3.6/site-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 421, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpcre.so.3: cannot open shared object file: No such file or directory
>>>
```

**Comment by adulau** [comment] 2018-05-09 11:40
I think you are missing the libpcre on your system. Did you install libpcre3 on your CentOS/RedHat? can you check with an `rpm -qa`?

**Comment by github-germ** [comment] 2018-05-09 13:54
i installed pcre from https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.gz and this installed earlier versions apparently. how do i get libpcre3

looks like we have several versions but not 3:

```
/usr/lib/libpcre.so.1
/usr/lib/libpcre.so.1.2.0
/usr/lib64/libpcre.so
/usr/lib64/libpcre.so.1
/usr/lib64/libpcre.so.1.2.0
/usr/local/lib/libpcre.so
/usr/local/lib/libpcre.so.1
/usr/local/lib/libpcre.so.1.2.10
```

also, now realize that the yara-1.7.7 setup.py install also complained about missing libpcre3

i will see if the person who is actually doing this install work can post in here with more info.

**Comment by adulau** [comment] 2018-05-09 13:57
I'll close the issue for the time being. Feel free to reopen if you get more information. Thank you.

**Comment by gitnorty** [comment] 2018-05-09 14:43
Hi adulau, I'm working with github-germ on this issue.  I believe I fixed the yara issue with the installation of yara-python.  I'm not seeing any errors when I run misp-modules:

[root@md2nj01ta yara-1.7.7]# 2018-05-09 14:08:08,284 - misp-modules - INFO - Launch MISP modules server from current directory.
2018-05-09 14:08:08,287 - misp-modules - INFO - Helpers loaded cache.py
2018-05-09 14:08:08,291 - misp-modules - INFO - MISP modules asn_history imported
2018-05-09 14:08:08,292 - misp-modules - INFO - MISP modules rbl imported
2018-05-09 14:08:08,295 - misp-modules - INFO - MISP modules farsight_passivedns imported
2018-05-09 14:08:08,296 - misp-modules - INFO - MISP modules iprep imported
2018-05-09 14:08:08,297 - misp-modules - INFO - MISP modules virustotal imported
2018-05-09 14:08:08,298 - misp-modules - INFO - MISP modules ipasn imported
2018-05-09 14:08:08,298 - misp-modules - INFO - MISP modules shodan imported
2018-05-09 14:08:08,299 - misp-modules - INFO - MISP modules reversedns imported
2018-05-09 14:08:08,300 - misp-modules - INFO - MISP modules crowdstrike_falcon imported
2018-05-09 14:08:08,301 - misp-modules - INFO - MISP modules circl_passivessl imported
2018-05-09 14:08:08,302 - misp-modules - INFO - MISP modules xforceexchange imported
2018-05-09 14:08:08,303 - misp-modules - INFO - MISP modules sourcecache imported
2018-05-09 14:08:08,304 - misp-modules - INFO - MISP modules geoip_country imported
2018-05-09 14:08:08,305 - misp-modules - INFO - MISP modules cve imported
(reverse-i-search)`': 2018-05-09 14:08:08,306 - misp-modules - INFO - MISP modules yara_syntax_validator imported
2018-05-09 14:08:08,307 - misp-modules - INFO - MISP modules otx imported
2018-05-09 14:08:08,308 - misp-modules - INFO - MISP modules circl_passivedns imported
2018-05-09 14:08:08,309 - misp-modules - INFO - MISP modules vulndb imported
2018-05-09 14:08:08,309 - misp-modules - INFO - MISP modules threatminer imported
2018-05-09 14:08:08,311 - misp-modules - INFO - MISP modules vmray_submit imported
2018-05-09 14:08:08,312 - misp-modules - INFO - MISP modules wiki imported
2018-05-09 14:08:08,313 - misp-modules - INFO - MISP modules eupi imported
2018-05-09 14:08:08,314 - misp-modules - INFO - MISP modules passivetotal imported                                                                        p': su apache -s /bin/bs': 2018-05-09 14:08:08,861 - misp-modules - INFO - MISP modules countrycode imported
2018-05-09 14:08:08,862 - misp-modules - INFO - MISP modules threatcrowd imported
2018-05-09 14:08:08,863 - misp-modules - INFO - MISP modules whois imported
2018-05-09 14:08:08,864 - misp-modules - INFO - MISP modules dns imported
2018-05-09 14:08:08,865 - misp-modules - INFO - MISP modules domaintools imported
2018-05-09 14:08:08,870 - misp-modules - INFO - MISP modules mispjson imported
2018-05-09 14:08:08,871 - misp-modules - INFO - MISP modules goamlimport imported
2018-05-09 14:08:08,872 - misp-modules - INFO - MISP modules threatanalyzer_import imported
2018-05-09 14:08:08,873 - misp-modules - INFO - MISP modules cuckooimport imported
2018-05-09 14:08:08,874 - misp-modules - INFO - MISP modules openiocimport imported
2018-05-09 14:08:08,875 - misp-modules - INFO - MISP modules email_import imported
2018-05-09 14:08:08,877 - misp-modules - INFO - MISP modules vmray_import imported
2018-05-09 14:08:08,878 - misp-modules - INFO - MISP modules stiximport imported
2018-05-09 14:08:08,879 - misp-modules - INFO - MISP modules csvimport imported
2018-05-09 14:08:08,880 - misp-modules - INFO - MISP modules ocr imported
2018-05-09 14:08:08,880 - misp-modules - INFO - MISP modules testimport imported
2018-05-09 14:08:08,883 - misp-modules - INFO - MISP modules testexport imported
2018-05-09 14:08:08,884 - misp-modules - INFO - MISP modules cef_export imported
2018-05-09 14:08:08,885 - misp-modules - INFO - MISP modules threatStream_misp_export imported
2018-05-09 14:08:08,886 - misp-modules - INFO - MISP modules threat_connect_export imported
2018-05-09 14:08:08,886 - misp-modules - INFO - MISP modules liteexport imported
2018-05-09 14:08:08,887 - misp-modules - INFO - MISP modules goamlexport imported
2018-05-09 14:08:08,888 - misp-modules - INFO - MISP modules pdfexport imported
2018-05-09 14:08:08,893 - misp-modules - INFO - MISP modules server started on localhost port 6666

but I'm still seeing errors when trying to access modules via the web UI:

{
    "error": "Something went wrong, no response from misp_modules."
}

I see these errors repeated several times in the logs when starting misp-modules:

2018-05-09 14:42:00 Warning: Warning (2): Illegal string offset 'modules' in [/var/www/MISP/app/Controller/ModulesController.php, line 53]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
ModulesController::index() - APP/Controller/ModulesController.php, line 53
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2018-05-09 14:42:00 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Controller/ModulesController.php, line 53]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
ModulesController::index() - APP/Controller/ModulesController.php, line 53
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by github-germ** [comment] 2018-05-09 16:20
adulau -- please re-open. i don't think we can as we didn't close the issue. thanks!!

**Comment by adulau** [comment] 2018-05-10 07:51
The pcre issue seems closed ;-) But for the modules, It seems to be another issue. Did you try to use a simple curl against the misp-modules like this:

`curl https://127.0.0.1:6666/modules`

**Comment by gitnorty** [comment] 2018-05-10 13:22
Hi adulau, not sure what was occurring, but the first time I ran the command it just hung for some time before I killed the execution.  After I killed the curl run, I looked to verify that misp-modules was running, which it was:

[root@md2nj01ta misp-modules]# ps -eaf |grep misp-m
root      4117 31099  0 May09 pts/0    00:00:02 python3.6 /usr/bin/misp-modules
root     27250 31099  0 13:11 pts/0    00:00:00 grep --color=auto misp-m

Not sure what accounted for the TIME_WAIT though...

[root@md2nj01ta misp-modules]# netstat -ann |grep 6666
tcp        0      0 127.0.0.1:6666          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:58806         127.0.0.1:6666          TIME_WAIT
tcp        0      0 127.0.0.1:6666          127.0.0.1:58812         TIME_WAIT
tcp6       0      0 ::1:6666                :::*                    LISTEN

The second time I ran it, it spit out about 200 or so lines of information; here is a snippet of the output:

[root@md2nj01ta misp-modules]# curl http://127.0.0.1:6666/modules
[{"name": "asn_history", "type": "modules", "mispattributes": {"input": ["AS"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Query an ASN Description history service (https://github.com/CIRCL/ASN-Description-History.git)", "module-type": ["expansion", "hover"], "config": ["host", "port", "db"]}}, {"name": "rbl", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["text"]}, "meta": {"version": "0.1", "author": "Christian Studer", "description": "Check an IPv4 address against known RBLs.", "module-type": ["expansion", "hover"], "config": []}}, {"name": "farsight_passivedns", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Christophe Vandeplas", "description": "Module to access Farsight DNSDB Passive DNS", "module-type": ["expansion", "hover"], "config": ["apikey"]}}, {"name": "iprep", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["text"]}, "meta": {"version": "1.0", "author": "Keith Faber", "description": "Query IPRep Data for IP Address", "module-type": ["expansion"], "config": ["apikey"]}}, {"name": "virustotal", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst", "md5", "sha1", "sha256", "sha512"], "output": ["domain", "ip-src", "ip-dst", "text", "md5", "sha1", "sha256", "sha512", "ssdeep", "authentihash", "filename"]}, "meta": {"version": "2", "author": "Hannah Ward", "description": "Get information from virustotal", "module-type": ["expansion"], "config": ["apikey", "event_limit"]}}, {"name": "ipasn", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Query an IP ASN history se

One other interesting note, there were no errors reported for about 2 or 3 hours now; just started looking at it, so there should have been very little happening on the system.  We have some MISP to MISP feeds pulling hourly, and a PySight2MISP pull once a day, but this was scheduled about 7 hours ago.

[root@md2nj01ta logs]# tail -11 error.log
2018-05-10 09:13:36 Error: [MethodNotAllowedException] You do not have permission to use this functionality.
Request URL: /tags/attachTagToObject
Stack Trace:
#0 /var/www/MISP/app/Controller/Component/ACLComponent.php(480): ACLComponent->__error(403, 'You do not have...')
#1 /var/www/MISP/app/Controller/AppController.php(379): ACLComponent->checkAccess(Array, 'tags', 'attachTagToObje...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}

**Comment by adulau** [comment] 2018-05-10 13:27
Interesting. The last entry of the error log seems to be a user without the role tagger. Could you check your roles in the MISP configuration? For the rest, misp-modules, it seems to work fine.

**Comment by gitnorty** [comment] 2018-05-10 13:32
only one role doesn't have the tagger permissions; this is the one pulling the iSight feed.

It seemed like the misp-modules was mostly working to us yesterday as well, but we aren't seeing anything reflected in the Web UI that allows us to do anything with the modules as far as I can see..

**Comment by gitnorty** [comment] 2018-05-10 13:43
by the way, I corrected the tagger permissions for the user pulling the iSight feed.

**Comment by iglocska** [comment] 2018-05-10 14:02
Make sure you update, that ACL error could be caused by a recent bug which
was fixed today, though it is probably unrelated to the modules not working.

**Comment by gitnorty** [comment] 2018-05-10 16:12
thanks for the suggestion iglocska, I've updated to 2.4.90; will keep an eye on things to see if the issue persists.

**Comment by github-germ** [comment] 2018-05-10 22:32
should a browser be able to see the resulting JSON output from http://127.0.0.1:6666/modules ?

it works with curl fine.

**Comment by SteveClement** [comment] 2018-05-17 05:59
Anything that can speak *http* will be able to see it.

Perhaps getting familiar with Layer 7 is of essence: https://en.wikipedia.org/wiki/List_of_network_protocols_(OSI_model)

(And the rest of the OSI model…)

sincerely.

**Closed as completed by SteveClement** 2018-05-17 05:59 UTC
Labels: T: support
