### ISSUE TITLE
Export: Generating STIX not working 

### ISSUE THREAD

**Issue by oana906** [MISP/MISP#1556] opened 2016-09-22 09:01 UTC
| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (client) | Windows Seven |
| MISP version / git hash | 2.4.51 |
| Browser | IE10, Chrome  52.0.2743.116 m |
### Expected behavior

I, as a Read Only user (Role ID 7), am exporting the STIX document. I Generate the file and then I succesfully download it. 
### Actual behavior

I, as a Read Only user (Role ID 7), am exporting the STIX document. I Generate the file but the progress bar is not changing even after I have waited for more than 10 minutes. When I press the download button, I get the error bellow.
### Steps to reproduce the behavior

After loging in, I choose the Export, and for Type=STIX, I press Generate. Nothing happens. If I pree Download, i get an error. Other types work correctly.
### Logs, screenshots, configuration dump, ...

The requested file was not found
Error: The requested address '/events/downloadExport/stix' was not found on this server.

**Comment by yohonet** [comment] 2016-09-22 14:40
Hello, I believe my problem is also related: XML export is not working either. Here is my curl query:

/usr/bin/curl -s -H "Authorization: [stripped]" http://[misp_server]/events/restSearch/download/null/ip-dst&&url&&hostname&&ip-src&&uri/null/null/null/null/null/2016-09-22

After several seconds (around 20), curl gets an HTTP error code and an HTML page saying "Internal error". By the way, the error page being a valid XML, it is not possible for a script to test if something wrong happened except by adding "-f" in the curl command line above.

I've been unable to find an error message in the logs so far - where could I look for to provide more information ?

**Comment by yohonet** [comment] 2016-09-29 12:18
Solved my issue, by turning on debug mode in the MISP web UI I figured out that the memory assigned to PHP was not enough for my restSearch: I had to increase the memory_limit to 8GB (!) and the max_execution_timeout to 15mn (!).

Don't know if the STIX export of the OP is the same problem.

**Comment by iglocska** [comment] 2016-09-29 12:20
8 GB? How many attributes do you have in your MISP?

**Comment by iglocska** [comment] 2016-09-29 12:38
Found an issue with it, basically what happened: 
- The list of parameters specify any event before 2016-09-22 instead of any event after that date
- This is still valid, it's a massive dataset but that shouldn't cause any issues by itself, MISP should tackle events one by one and add it to the resulting xml file (the contents of which should make up the lion share of the data stored in memory)
- However, due to a bug it loaded the entire valid dataset into memory in one go, resulting in memory exhaustion.

Please git pull and the memory usage should go down drastically. Also, for the parameters, you probably want to use this: http://[misp_server]/events/restSearch/download/null/ip-dst&&url&&hostname&&ip-src&&uri/null/null/null/null/2016-09-22

Alternatively to avoid confusion, I highly recommend POSTing a JSON object with the named parameters, passing them through the URL is highly recommended against.

**Comment by yohonet** [comment] 2016-09-29 23:09
Thanks for taking my case into consideration and I now realize I unintentionally hijacked this report because my issue does not appear to be related. Sorry for that but it should be the last comment.

Anyway, your first bullet point was intended, I wanted "most" of the MISP attributes (so the ones until 2016-09-22).

I git pulled and made sure this commit was in my git log. Export still takes some time (8 minutes) but I get the expected results after decreasing the memory_limit to a reasonable amount (1024MB) which was not the case before, so it appears to work just fine. Thanks.

**Comment by adulau** [comment] 2017-09-19 12:44
I suppose this has been fixed in recent version of MISP. Feel free to reopen if this is not the case.

**Closed as completed by adulau** 2017-09-19 12:44 UTC
Labels: T: support, T: potential bug
