### ISSUE TITLE
Importing a CISA STIX file fails

### ISSUE THREAD

**Issue by samitainio** [MISP/MISP#6531] opened 2020-10-31 10:58 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2.24
| MISP version / git hash   | v2.4.133 (9768fc9bcc3d88a266a9e671b294cffc0a8974b2)
| Browser                   | Not applicable

### Expected behavior
https://us-cert.cisa.gov/sites/default/files/publications/MAR-10135536-8.v4.stix.xml

Importing of the above mentioned stix file would be succesful.

### Actual behavior
Importing fails with errors in exec-errors.log, see the log below.

### Steps to reproduce the behavior
1. Try to import the file.

### Logs, screenshots, configuration dump, ...
exec-errors.log:
```
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
TOUMarking:TermsOfUseMarkingStructureType
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1534, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1529, in main
    stix_parser.build_misp_event(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 80, in build_misp_event
    self.build_misp_dict(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1179, in build_misp_dict
    self.parse_external_indicators(self.event.indicators)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1233, in parse_external_indicators
    self.parse_external_single_indicator(indicator)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1247, in parse_external_single_indicator
    'value': test_mechanism.rule.value
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 392, in from_dict
    raise NewAttributeError('The value of the attribute is required.')
pymisp.exceptions.NewAttributeError: The value of the attribute is required.
```

**Comment by adulau** [comment] 2020-11-02 10:48
I was able to reproduced the issue on the current HEAD.

**Comment by chrisr3d** [comment] 2020-11-02 11:26
It should be working now, let me know if anything else goes wrong

**Comment by adulau** [comment] 2020-11-02 15:24
It works for me, I imported the file without any issue. @samitainio we will close the issue, don't hesitate to reopen if you have any question.

**Closed as completed** 2020-11-02 15:26 UTC
Labels: T: bug

**Comment by samitainio** [comment] 2020-11-02 18:09
Thank you all! Now working here aswell.
