### ISSUE TITLE
Configuration help

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#4564] opened 2019-05-02 14:55 UTC
This is not a report of an issue but rather a question. Can we get post install assistance. Is there documentation out there that describes how to configure misp post install. Specifically settings found in server settings & maintenance.

**Comment by SteveClement** [comment] 2019-05-06 07:54
Yes, there is this documentation effort: https://www.circl.lu/doc/misp/

**Comment by dmolina213** [comment] 2019-05-07 18:27
The documentation tells me where to find it. But not the recommended settings. I appreciate the help

**Comment by SteveClement** [comment] 2019-05-08 12:47
As mentioned in chat:

Some configuration defaults are already in the INSTALL docs: https://misp.github.io/MISP/INSTALL.ubuntu1804/#initialize-misp-configuration-and-set-some-defaults
But admittedly there is more to tweak then that.
So far, this still needs better documentation.

**Comment by dmolina213** [comment] 2019-05-14 12:33
Steve, 
I am new in this board and want to understand the communication that is being sent here. Does this signify a change in MISP that we need to run an update? Are this patches that we should all run?

You can view, comment on, or merge this pull request online at:
  https://github.com/MISP/MISP/pull/4624
Commit Summary
•	chg: [conf] Added http to https redirection
•	chg: [installer] Updated installer to latest
File Changes
•	M INSTALL/INSTALL.sh (1) 
•	M INSTALL/INSTALL.sh.sfv (6) 
•	M INSTALL/INSTALL.sh.sha1 (2) 
•	M INSTALL/INSTALL.sh.sha256 (2) 
•	M INSTALL/INSTALL.sh.sha384 (2) 
•	M INSTALL/INSTALL.sh.sha512 (2) 
•	M INSTALL/apache.24.misp.ssl (20) 
Patch Links:
•	https://github.com/MISP/MISP/pull/4624.patch
•	https://github.com/MISP/MISP/pull/4624.diff

**Comment by SteveClement** [comment] 2019-05-14 13:50
@dmolina213 This is independent from the Core.
This just means:

The installer has been updated, so if people run the installer from that point onwards for a new install, they will get the latest installer version.

What you want to care about in terms of updates that might definitely impact your install, anything in the **app** directory.

**Comment by dmolina213** [comment] 2019-05-14 14:19
So watch for notifications with changes to the app directory. go ahead and update it via the diagnostic page?

**Comment by SteveClement** [comment] 2019-05-14 14:24
I think the best would be, watch the release page: https://github.com/MISP/MISP/releases

The updates will be less frequent, but you will be sure to get a, more or less, well tested release.

But of course, if something seems to be dysfunctional in your setup you can always raise the issue and then once fixed, update to that patch-level at the time of the fix via the WebUI.

**Comment by dmolina213** [comment] 2019-05-14 16:45
I am still having problems with updating on the GUI. I may have raised the issue on GITTER. I know GIT is installed. That was the way we downloaded misp and its components. But when I try to update I get this error. 
Let me know if you want me to raise a separate issue for this?
Currently installed version… () 
Unable to fetch current commit id, check apache user read privilege. 
Latest available version… () 
Status… Could not retrieve version from github 
Current branch… You are not on a branch, Update MISP will fail 
cd $(git rev-parse --show-toplevel) && git checkout app/composer.json 2>&1

sh: git: command not found

cd $(git rev-parse --show-toplevel) && git pull origin  2>&1

sh: git: command not found
sh: git: command not found

=================================

cd $(git rev-parse --show-toplevel) && git submodule update --init --recursive 2>&1

sh: git: command not found

**Comment by SteveClement** [comment] 2019-05-17 05:44
I suppose you use RedHat or CentOS?

**Comment by SteveClement** [comment] 2019-05-17 05:44
This in essence means the command git is not found.

**Comment by dmolina213** [comment] 2019-05-17 15:39
We are using RHEL7. 
Is  there a conf file we need to configure the path to inorder for the web gui to locate the git command?

**Comment by SteveClement** [comment] 2019-05-20 09:53
No, I cannot help more in this issue. If @rommelfs or @iglocska or some other RHEL familiar folks want to help out, please feel free.

I also know there are some people in Gitter who use RHEL.

Sorry, I cannot be of more help.

**Comment by dmolina213** [comment] 2019-05-20 12:41
thank you for all your patience and assistance steve.

**Comment by rommelfs** [comment] 2019-05-22 08:33
This turns into a duplicate of #4562. I'm closing this one here.

**Closed as completed by rommelfs** 2019-05-22 08:33 UTC
Labels: T: support
