### ISSUE TITLE
Can't download full list of events from CIRCL MISP events

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#4507] opened 2019-04-18 18:12 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Red Hat 7.6
| OS version (client)       | WIndows 10
| PHP version               | 7.2.10
| MISP version / git hash   | 2.4.105
| Browser                   | Chrome

### Expected behavior

Download of CIRCL OSINT Feed

### Actual behavior

Partial list downloaded (around 600~ events). I can explore the events remotely.

### Steps to reproduce the behavior

Clicking of fetch all events
Jobs status are Failed with Progress in Queued.

### Logs, screenshots, configuration dump, ...

We're using proxy configuration with SSL inspection.
Already added our certificates in /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt 
and did a link to cakephp use it in ...lib/Cake/Config/cacert.pem
Other feeds are downloaded normally. Tested with Botvrjj.eu, cybercrime-tracker.net and osingt.bambenekconsulting.com

**Comment by ghost** [comment] 2019-05-02 13:23
We're checking if maybe a Traffic Throttling behaviour is causing this. But I'm open to tshoot options.

**Comment by young2112129** [comment] 2019-05-23 01:47
@hackunagi have you fix this problem?
I also have the same problem, when I download CIRCL OSINT Feed, only a few(less than 10) events was downloaded.
I only set the proxy in Administration ->Server Settings & Maintenance ->Proxy settings
![222](https://user-images.githubusercontent.com/50349709/58220331-0dd63880-7d41-11e9-8173-d491a664917d.png)


Any suggestion? Thanks.

**Comment by ghost** [comment] 2019-05-23 14:19
No solutions yet.
I'm waiting a few internal changes in my company infrastructure, and then I'll do new tests.

**Comment by rommelfs** [comment] 2019-05-24 06:02
Tested this a few hours ago and it worked perfectly fine. 
Of course, if your network connection is interrupted (and that could be caused by anything between your server and the feed hosting server, especially with proxy servers in between), the job will fail. They won't resume on their own when manually pulled. In this case they have to be manually pulled again to resume.

The task can also be automated. Look at the events/automation page.
If it's automated, it will resume on next run.

I don't see anything we can help here with and I'm closing this issue. If you have reason to think this is something we could address, feel free to re-open.

**Closed as completed by rommelfs** 2019-05-24 06:02 UTC

**Comment by iglocska** [comment] 2019-05-24 06:54
A small side note if that doesn't solve it for you: Make sure you raise the memory limit in php.ini to something sane considering some of the event sizes (1024/2048 MB).
