### ISSUE TITLE
Cannot add a new feed?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#1605] opened 2016-10-10 13:30 UTC
I get an HTTP/500 error when trying to add a new feed...
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug? |
| OS version (server) | Ubuntu |
| OS version (client) | Any |
| PHP version | 5.5 |
| MISP version / git hash | 2.4.52 |
| Browser | n/a |
### Expected behavior

Creation of an external feed
### Actual behavior

HTTP/500

[2016-10-10 15:13:41] main.ERROR: {"queue":"default","id":"ad827dffe79a306828c7534e2eb54db5","class":"ServerShell","args":[{"0":"enqueuePull","1":1476104400,"2":"1","3"
:"2","s_time":1476100801}]} failed: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'org_id' at row 1 {"type":"fail","log":"SQLSTATE[HY000]:
 General error: 1366 Incorrect integer value: '' for column 'org_id' at row 1","job_id":"ad827dffe79a306828c7534e2eb54db5","time":817423,"worker":"misp:680"} []
### Steps to reproduce the behavior

Create a new feed and save it.

**Comment by iglocska** [comment] 2016-10-10 13:54
That error seems to come from a pull of a server initiated by the backround worker and unrelated to adding an external feed. 

As a first step, could you try to go to server settings -> diagnostics -> clear model cache and see if it resolves your issue that prevents you from adding a feed?

**Comment by xme** [comment] 2016-10-10 16:00
Done, same issue:

2016-10-10 17:59:25 Error: [PDOException] SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'event_id' at row 1
Request URL: /feeds/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO`mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(Feed), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/FeedsController.php(67): Model->save(Array)
#6 [internal function]: FeedsController->add()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(FeedsController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(FeedsController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by iglocska** [comment] 2016-10-10 16:25
Just pushed a fix, not 100% sure it solves it as I can't reproduce it. Could you give it a shot?

**Comment by xme** [comment] 2016-10-10 18:08
Hmm... Same error! :(
I will dive into the code to try to find the issue...

**Comment by xme** [comment] 2016-10-10 18:19
The problem is related to the feed I'm trying to add. Trying another one, it worked!

**Comment by iglocska** [comment] 2016-10-10 18:23
What the hell! Is it a public feed by any chance?

**Comment by xme** [comment] 2016-10-10 18:26
Here is the test URL that generates the error:
http://rules.emergingthreats.net/blockrules/compromised-ips.txt
(Selection CSV, column 1)

**Comment by iglocska** [comment] 2016-10-11 17:52
I simply can't seem to be able to reproduce it. I've pushed some minor fixes one of which is a blind fix attempt for this, if you could give it a shot (though I am really grasping at straws here).

Could you run a mysql query and print the results of it here though? That might help slightly:

describe feeds;

Also, does your misp mysql user have permissions to alter the db?

**Comment by iglocska** [comment] 2016-10-26 16:22
Had something similar come up recently so made some modifications to it, let me know if it still shows up!

**Closed as completed** 2016-12-13 22:02 UTC
Labels: T: support, WaitingAnswer
