### ISSUE TITLE
Alert if non correlated artifacts correlates to new Intel data in the future

### ISSUE THREAD

**Issue by seldem** [MISP/MISP#5592] opened 2020-02-04 11:02 UTC
Suppose I have an Event with several artifacts but none of them correlated. I wish to be alerted in a way (mail etc.) , if any of artifacts of this event correlates to new Intel data in the future. I hope you guys implement it. Thanks.

**Comment by adulau** [comment] 2020-02-04 13:57
Duplicate of #3622

**Comment by adulau** [comment] 2020-02-04 13:57
Related to #1613

**Comment by iglocska** [comment] 2020-02-04 14:59
My bad, I asked for the issue, thought we didn't have one yet for this ;)

**Comment by cvandeplas** [comment] 2020-05-19 05:24
closing as this is a duplicate of many more. See #1613 for updates.

**Closed as completed by cvandeplas** 2020-05-19 05:24 UTC
Labels: T: feature request
