### ISSUE TITLE
Could not attach cluster to event

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#2391] opened 2017-08-11 15:05 UTC
Users receive the following error when trying to add a cluster to an event.

Error: The requested address '/galaxies/attachClusterToEvent/984' was not found on this server.

Though an admin can attach it to the vent just fine, they do not have tag editor permissions. Though that shouldn't be an issue? Either way they can attach clusters fine most of them time and then every so often I have to go in and add the cluster for them due to this error. Currently we are running on apache 2.4 and MISP 2.4.69 and I can do some hot fixes, but I cannot update the server past that due to our environment. 

Error in error.log

2017-08-11 12:00:53 Error: [MethodNotAllowedException] could not attach cluster.
Request URL: /galaxies/attachClusterToEvent/1027
Stack Trace:
0 [internal function]: GalaxiesController->attachClusterToEvent('1027')
1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethon->invokeArgs(Object(GalaxiesController), Array)
2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/dispatcher.php(167): Dispatcher->_invoke(Object(GalaxiesController), Object(CakeRequest))
4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
5 {main}

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 6.9
| OS version (client)       | Windows 10
| PHP version               | 5.6
| MISP version / git hash   | 2.4.69
| Browser                   | Firefox

### Expected behavior

Threat-actor gets attached to event

### Actual behavior

Error from above 
### Steps to reproduce the behavior

I'm not sure on this one, it only happens sometimes and for some events.. I'm not sure if they leave the event or go back in and then only a "tag editor" can add the cluster. like I said it only happens every so often.

**Comment by iglocska** [comment] 2017-08-11 15:10
Weird, attaching a cluster should never require the tag editor role (only the tagger role).

However your MISP seems to be quite outdated, could you update to the latest version?

**Comment by ghost** [comment] 2017-08-11 16:09
I wish! we are planning that for the future though, so I will be eventually moving to CentOS 7 and the latest version of MISP. I only thought it was weird because an admin could do it, but the user that created the event couldn't. And it something that pops up from time to time. We are also using custom threat-actor lists.. that might possibly be the source issue too.. that being said as an admin I've never had this problem and I just go into their event and fix it.

**Comment by ghost** [comment] 2017-08-11 16:23
updated with error.log infomation.

Also the files in the errors were last updated over a year ago..

**Comment by marcnil815** [comment] 2018-12-13 12:34
Same behaviour in 2.4.98. User needs tag editor rights to add Galaxy cluster to event.

**Comment by dewiestr** [comment] 2019-01-07 11:00
Same behavior in 2.4.100. User with "tagger" permissions alone cannot add galaxy cluster to event.

**Comment by mokaddem** [comment] 2019-01-18 15:20
Hi all,
It should be fixed with the latest version. Feel free to re-open if you don't get the expected behavior.
Cheers!

**Closed as completed by mokaddem** 2019-01-18 15:20 UTC
Labels: T: potential bug
