### ISSUE TITLE
[Error] Class 'PDO' not found | Debian 9.3 Install guide

### ISSUE THREAD

**Issue by Jnizou** [MISP/MISP#2867] opened 2018-01-22 15:49 UTC
| Questions                  | Answers
|------------------------|--------------------
| Type of issue             | Bug
| OS version (server)    | Debian 9.3
| PHP version               | PHP 7.0.27

> 2018-01-22 14:54:47 Error: [Error] Class 'PDO' not found
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(261): Mysql->enabled()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Controller/EventsController.php(33): AppController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): EventsController->beforeFilter(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2018-01-22 14:54:47 Error: Fatal Error (1): Uncaught Error: Class 'PDO' not found in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php:209
Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(261): Mysql->enabled()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/MISP/app/Controller/AppController.php(99): ConnectionManager::getDataSource('default')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController(Object(Error))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct(Object(Error))
#8 in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 209]
2018-01-22 14:54:47 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 209)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Error:...', '/var/www/MISP/a...', 209, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

> php -m
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
igbinary
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib
[Zend Modules]
Zend OPcache

**Comment by adulau** [comment] 2018-01-22 17:18
Have you installed the php-pdo-mysql debian package?

**Comment by Jnizou** [comment] 2018-01-23 08:06
Yes, php7.0-mysql is installed, you can see the output of the command "php -m", PDO and pdo_mysql are loaded

**Comment by Jnizou** [comment] 2018-01-23 08:13
@adulau  Yes, php7.0-mysql is installed, you can see the output of the command "php -m", PDO and pdo_mysql are loaded, you can reproduce this issue by following the Debian installation guide with a fresh Debian 9.3 install.

**Comment by iglocska** [comment] 2018-01-23 08:24
php-m only shows the available modules, not the enabled ones. 

Could you run `sudo apt-get install php-mysql` just to make sure?

Could you also run `php -r "print_r(get_loaded_extensions());"` just to verify if it's loaded?

**Comment by Jnizou** [comment] 2018-01-23 08:35
```
apt search php | grep 'mysql'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

php-mdb2-driver-mysql/stable 1.5.0b4-2 all
  mysql MDB2 driver
php-mysql/stable,now 1:7.0+49 all  [installé]
php7.0-mysql/stable,now 7.0.27-0+deb9u1 amd64  [installé]
```
```
php -r "print_r(get_loaded_extensions());"
Array
(
    [0] => Core
    [1] => date
    [2] => libxml
    [3] => openssl
    [4] => pcre
    [5] => zlib
    [6] => filter
    [7] => hash
    [8] => pcntl
    [9] => Reflection
    [10] => SPL
    [11] => session
    [12] => standard
    [13] => mysqlnd
    [14] => PDO
    [15] => xml
    [16] => calendar
    [17] => ctype
    [18] => dom
    [19] => mbstring
    [20] => fileinfo
    [21] => ftp
    [22] => gettext
    [23] => iconv
    [24] => igbinary
    [25] => json
    [26] => exif
    [27] => mysqli
    [28] => pdo_mysql
    [29] => Phar
    [30] => posix
    [31] => readline
    [32] => redis
    [33] => shmop
    [34] => SimpleXML
    [35] => sockets
    [36] => sysvmsg
    [37] => sysvsem
    [38] => sysvshm
    [39] => tokenizer
    [40] => wddx
    [41] => xmlreader
    [42] => xmlwriter
    [43] => xsl
    [44] => Zend OPcache
)
```

**Comment by iglocska** [comment] 2018-01-23 08:41
Could you add this to php.ini and restart apache?

`extension=mysqlnd.so`

**Comment by iglocska** [comment] 2018-01-23 08:42
Ah wait, it shows up as loaded, I am blind. Just out of curiosity, you have a set up database file in /var/www/MISP/app/Config/database.php right?

**Comment by Jnizou** [comment] 2018-01-23 08:59
Yes, i have created the database and setup the database.php config file

```
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                //'datasource' => 'Database/Postgres',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'db login',
                'port' => 3306, // MySQL & MariaDB
                //'port' => 5432, // PostgreSQL
                'password' => '*************',
                'database' => 'misp',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}

```

**Comment by Jnizou** [comment] 2018-01-23 09:11
I have found the problem with a phpinfo() page to view the current PHP configuration.

```
System | Linux misp 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
-- | --
Build Date | Jan 5 2018 13:51:52
Server API | Apache 2.0 Handler
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /etc/php/7.0/apache2
Loaded Configuration File | /etc/php/7.0/apache2/php.ini
Scan this dir for additional .ini files | /etc/php/7.0/apache2/conf.d
Additional .ini files parsed | (none)
PHP API | 20151012
```
it's look like "additional.ini files" are only loaded in php CLI

**Comment by adulau** [comment] 2018-01-26 11:20
Thank you very much for the feedback.

If I understand correctly, you updated the php.ini for Apache to include the PDO and it works now.

I'll close the issue, feel free to reopen if the issue is not solved.

**Closed as completed by adulau** 2018-01-26 11:20 UTC
Labels: T: support
