### ISSUE TITLE
Why does events/view have vertical whitespace?

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3465] opened 2018-07-10 19:41 UTC
We see a lot of vertical whitespace on the event/view WebUI page between the top summary and the start of the attributes.

- What is the root cause?
- Please see the attached PNG.

<img width="819" alt="event-vertical-whitespace-issue" src="https://user-images.githubusercontent.com/8812009/42533392-b3a42bde-8457-11e8-8a93-37535323d16f.png">

**Comment by iglocska** [comment] 2018-07-11 08:07
Can't reproduce that o.O

**Comment by SteveClement** [comment] 2018-07-11 08:29
@github-germ which browser are you using? Which OS?

**Comment by github-germ** [comment] 2018-07-11 15:52
@SteveClement Hi, I don't think this a browser rendering issue. We recall that the whitespace didn't used to be there; and it's not there if we create a new Event from the WebUI. We are seeing for Events created via our `PySight.py` (enhanced) ingestion script. It may be possible that it started after I got the `org`/`orgc` issue working (https://github.com/MISP/PyMISP/issues/239)

Win-7: Chrome, Firefox
MacOS-10.13.5: Safari, Chrome, Firefox

**Comment by github-germ** [comment] 2018-07-17 12:57
When the browser window is not maximized the vertical whitespace is large; much less when maximized (but still a bit much). Could this be something like an HTML/css rendering issue?

**Comment by SteveClement** [comment] 2018-07-19 19:18
@github-germ I cannot reproduce it.
Also, in your example you have no sightings.
The View is quasi agnostic when it comes to the source of the data, thus I doubt the fact that you make an API submission plays into it.

Is it only on ONE particular event or ALL events?

**Comment by github-germ** [comment] 2018-07-19 19:31
@SteveClement Thx for investigating. This isn't a showstopper, but would be nice to understand.

We see it on the events ingested via `PyMISP` and not manually entered WebUI events, e.g.


**1. Manually created event:** 
<img width="639" alt="screen shot 2018-07-19 at 3 23 52 pm" src="https://user-images.githubusercontent.com/8812009/42965699-acca1b6c-8b68-11e8-85e8-75f403bb6c32.png">


**2. API created event with browser NOT maximized:** 
<img width="606" alt="screen shot 2018-07-19 at 3 22 15 pm" src="https://user-images.githubusercontent.com/8812009/42965437-015dcad0-8b68-11e8-8087-a61d567c62fd.png">


**3. Same API created event with browser maximized:**
<img width="809" alt="screen shot 2018-07-19 at 3 21 16 pm" src="https://user-images.githubusercontent.com/8812009/42965737-c0b1c102-8b68-11e8-92e2-824dad5daafd.png">

**Comment by Rafiot** [comment] 2018-07-20 12:15
Can you send us the source of the page? At least the part between activity and the galaxies.

**Comment by github-germ** [comment] 2018-07-24 18:22
Not sure if the HTML for the two cases will be OK. I had to redact a fair bit, but tried to keep the section in question untouched. Let me know...

1. Manually created event: no whitespace issue
[issue-3465-manual-event-no-whitespace-source-sample.txt](https://github.com/MISP/MISP/files/2224877/issue-3465-manual-event-no-whitespace-source-sample.txt)

2. API created event: extra whitespace
[issue-3465-api-event-yes-whitespace-source-sample.txt](https://github.com/MISP/MISP/files/2224882/issue-3465-api-event-yes-whitespace-source-sample.txt)

**Comment by SteveClement** [comment] 2018-09-03 08:53
As this is a very isolated case and not reproducible on our side we will close it in the meantime until it show main-stream potential.

**Closed as completed by SteveClement** 2018-09-03 08:53 UTC
Labels: T: support, WaitingAnswer, S: under investigation, UI
