### ISSUE TITLE
【Bug】PyMISP's search_index

### ISSUE THREAD

**Issue by SoheiMitsukawa** [MISP/MISP#4888] opened 2019-07-17 07:33 UTC
Hello.
I'm Japanese, so I wrote this document using automatic translation.

I use PyMISP's search_index.

When event info is specified as an argument, I found a bug that I can not get results correctly.

If event info contains multi-byte characters, as shown below, the correct result can not be obtained.
>WHERE lower(`Event`.`info`) LIKE '%Ａ%'
>WHERE lower(`Event`.`info`) LIKE '%О%'

The left side of the like clause uses MySQL's Lower, but the right side seems to be doing its own conversion.
I think that the conversion may not correspond properly.

I use MISP in my work, so I hope that you resolve it as soon as possible.

Best regards,

OS version (server): ubuntu 18.04
OS version (client): Ubuntu 18.04
PHP version: 7.3
MISP version / git hash: latest

**Comment by ITServ-DE** [comment] 2019-07-17 09:06
You have logical problem in your query. Try this:
```
WHERE lower(Event.info) LIKE lower('%Ａ%')
WHERE lower(Event.info) LIKE lower('%О%')
```
or - more simple - 
```
WHERE lower(Event.info) LIKE '%a%'
WHERE lower(Event.info) LIKE '%o%'
```

When you lowercase your left side of the comparison, you have to lower the right side too.

My results:
```
MariaDB [misp]> select count(*) from events Event where lower(Event.info) like "%A%";
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

MariaDB [misp]> select count(*) from events Event where lower(Event.info) like "%a%";
+----------+
| count(*) |
+----------+
|     1401 |
+----------+
1 row in set (0.00 sec)
```


If you do not run your own queries against the database, but took your query fragments from a mysql debug log, please provide more detailled information how you performed the search through the web interface which resulted in these unsuccessful database queries.

**Comment by SoheiMitsukawa** [comment] 2019-07-17 10:03
Thanks for quick reply.

But I'm sorry, I was short of explanation.
As stated, I didn't run my own queries against the database.

I just ran a PyMISP search_index.
And I copied the corresponding SQL from debug log.

In MISP, events "Ａ" and "О" are registered, but thePyMISP result is that an empty list is returned.

Best regards,

**Comment by ITServ-DE** [comment] 2019-07-17 10:29
Can you please provide the source code you execute, so I can try to reproduce your problem?

**Comment by Rafiot** [comment] 2019-07-17 16:16
The code would help. Also, please consider using ExpandedPyMISP (requires python 3.6+).

**Comment by SoheiMitsukawa** [comment] 2019-07-18 01:44
Thanks for your comments.
And sorry for the late reply.

I'll write the Python code I verified.
(URL and API are changing)

>from pymisp import PyMISP
>misp = PyMISP('https://hoge', 'hogehoge', False, 'json')
>misp.new_event(info='Ａ')
>print(misp.search_index(eventinfo='Ａ'))
{'response': []}

After the above execution, I saw the SQL mentioned yesterday from /var/log/mysql/mysqlquery_dump.log.

I use Python Version: 3.6.8.

Best regards,

**Comment by ITServ-DE** [comment] 2019-07-18 06:14
Can't reproduce for the moment. I run your code on my MISP (2.4.111) with a slightly modified event, and it works.

```
from pymisp import PyMISP

misp = PyMISP('https://***URL***', '***APIAUTHKEY***', True, 'json')
misp.new_event(info='Akdi93d')

print(misp.search_index(eventinfo='Akdi93d'))
```

gives exactly one event:

```
{'response': [{'id': '1706', 'org_id': '1', 'date': '2019-07-18', 'info': 'Akdi93d', 'uuid': '5d300d98-b67c-4c34-bea6-694055eb40de', 'published': False, 'analysis': '0', 'attribute_count': '0', 'orgc_id': '1', 'timestamp': '1563430296', 'distribution': '1', 'sharing_group_id': '0', 'proposal_email_lock': False, 'locked': False, 'threat_level_id': '4', 'publish_timestamp': '0', 'disable_correlation': False, 'extends_uuid': '', 'Org': {'id': '1', 'name': 'ORGNAME', 'uuid': '5cdd8e19-31a8-4f52-8d82-3dc25c69efb1'}, 'Orgc': {'id': '1', 'name': 'ORGNAME', 'uuid': '5cdd8e19-31a8-4f52-8d82-3dc25c69efb1'}, 'EventTag': []}]}
```

would you please check your PyMISP version by running

```
import pymisp
print(pymisp.__version__)
```

It should by 2.4.111, else update using ```pip update --upgrade pymisp ```

**Comment by SoheiMitsukawa** [comment] 2019-07-18 07:30
I'm sorry, my explanation was still inadequate.

This bug occurs when event info contains full-width upper case letters.

Succeeds in Akdi93d, but fails in Ａｋｄｉ９３ｄ.

Best regards,

**Comment by ITServ-DE** [comment] 2019-07-18 07:37
I just activated the query log and re-run the script, and found these two:

```
WHERE lower(`Event`.`info`) LIKE '%akdi93d%'
WHERE lower(`Event`.`info`) LIKE '%akdi93d%' 
```
You see a lowercase right side of the query.

Then, I cross-checked that my search_index searches for a capital Akdi93d, and it does.

What exact version of MISP (not: PyMISP) do you run?

**Comment by ITServ-DE** [comment] 2019-07-18 07:48
SoheiMitukawa,

If you do not provide an exact proof of the problem, nobody can help you. You were asked for a code sample, and obvisiously the code you have sent does not trigger the problem. And then you come around with "my explanation was still inadequate". 

I won't try to help you any further if you do not exactly describe your problem, with CORRECT sample data, CORRECT sample code, CORRECT version numbers.

**Comment by ITServ-DE** [comment] 2019-07-18 08:19
OK, by GUESSING what you were actually doing, I was able to reproduce the issue. I'm currently not fully understand it, but at least I can trigger the same problem.

**Comment by tkhr2019** [comment] 2019-07-18 08:23
Hello.

MySQL lower supports multibyte characters.
But php's strtolower doesn't support multibyte characters.

strtolower is used in app/Controller/EventsController.php.
You should use mb_strtolower instead of strtolower.

Thanks.

**Comment by ITServ-DE** [comment] 2019-07-18 08:36
You obvisously mix different character sets. When you search for Ａ (which is a unicode character), it does not match A from the ANSI/ASCII character set. The same happens to me for the german characters Ä, Ö, Ü, and I'm hunting the issue.

**Comment by ITServ-DE** [comment] 2019-07-18 08:54
@tkhr2019 
Thank you for your valuable input.

@SoheiMitsukawa 
as a workaound, fix your code by adding `.lower()` to the search you want to perform, like this:

```
from pymisp import PyMISP

misp = PyMISP('https://***URL***', '***APIAUTHKEY***', True, 'json')
misp.new_event(info='Ａ')

print(misp.search_index(eventinfo='Ａ'.lower()))
```
                                          ^^^^^^^^^

But again, be careful to understand the difference between `A` and `Ａ`.

**Comment by ITServ-DE** [comment] 2019-07-18 09:07
@tkhr2019 
You are absolutely right. Replacing all occurences of `strtolower`/`strtoupper` with the multibyte versions `mb_strtolower`/`mb_strtoupper` fixes it. But I'm no developer, I wont fix it in the source code because I cannot estimate the risks that come with this change.

But I will open another issue with a more detailed problem description than this thread.

**Comment by ITServ-DE** [comment] 2019-07-18 09:43
Opened https://github.com/MISP/MISP/issues/4901

@SoheiMitsukawa: Please close this issue.

**Closed as completed** 2019-07-18 14:54 UTC

**Comment by SoheiMitsukawa** [comment] 2019-07-19 01:06
Thank you very much, everyone.
And sorry for the late reply.

First of all, the script which is working now coped with the method which I received.
>print(misp.search_index(eventinfo='Ａ'.lower()))

And, thank you for creating a new issue.
I hope that this issue will be solved.

Thank you very much.
