### ISSUE TITLE
Push/pull error current HEAD 

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#365] opened 2015-01-15 11:05 UTC
Fatal error:  Call to a member function user() on a non-object in MISP/app/Model/Server.php on line 475

Any idea?

**Comment by iglocska** [comment] 2015-01-15 12:58
Good catch, the issue is caused by a previous patch this week, should be fixed now if you pull, if you still have issues with it, let me know!

**Closed by iglocska** 2015-01-15 12:58 UTC
