### ISSUE TITLE
Can't found MISP command in the Viper Framework

### ISSUE THREAD

**Issue by yousefhawwari** [MISP/MISP#5507] opened 2020-01-14 13:05 UTC
![ViperMISP](https://user-images.githubusercontent.com/25611301/72346566-ede3f280-36de-11ea-9996-acef7160087b.PNG)

What should i do to integrate the Viper Framework with the MISP ?
 (I installed it on the MISP Server but can't found MISP Command in the Viper Framework).

Thank You.

**Comment by yousefhawwari** [comment] 2020-01-16 08:46
any answer?

**Comment by SteveClement** [comment] 2020-01-16 10:11
@yousefhawwari viper is currently misp broken.

I can confirm that it seems to be non-existent in a std. install.

perhaps try, in the viper cli:

```
viper > update-modules
```

**Comment by yousefhawwari** [comment] 2020-01-16 10:30
I tried " viper > update-modules "

Also no MISP command !

**Comment by SteveClement** [comment] 2020-01-16 10:49
yeah, it is broken, might be fixed in the future.

Feel free to open an issue in: https://github.com/viper-framework/viper-modules/issues

This is outside of the scope of MISP-core.

Sorry.

**Closed as completed** 2020-01-16 10:49 UTC
Labels: external tool
