### ISSUE TITLE
Adding IOC takes long time >20 seconds /attribute

### ISSUE THREAD

**Issue by FurqanKhan1** [MISP/MISP#2714] opened 2017-12-07 12:38 UTC
Its not a bug ,but a question to get clarity.

For Free Text Based Feeds -
So when the IOC count exceeds a certain level >200k ,i have noticed that the scheduler /parser /  The method saveFreetextFeedData ,would add each ioc very slow roughly 20 seconds /ioc.

I am assuming it has to do with the fact that every new ioc would be co-related and that would require few db read /write operations for every ioc.

I just placed a small code snippet where the ioc is parsed and pushed to the database to get exact time of delay between each database push,and the logs suggested that it takes roughly 20 seconds to add each ioc.

Is that normal ? and to get around it ,do i need to disable co-relation.

Is there any way to improve / optimize it with co-relation being on..Or do i need to write a custom logic around that ,may be offload this to apache-spark  ,and once the corelation results are availible ,push everything in one shot.

I would really appreciate ,if anyone can let me know me over it ,weather its normal behaviour or there is something i am doing wrong..20 seconds per ioc ,roughly gives me a maximum of 3600 new ioc's a day ,which is something i want to be improved.

![image](https://user-images.githubusercontent.com/15893015/33715596-8b75a5be-db6c-11e7-9175-74b6d01a6ed4.png)

It could be verified with the above screen shot that the delay is close to 20 seconds.

@adulau  ,Can u kindly spear your opinion on that ,i would be very grateful.

Regards
Furqan

**Comment by iglocska** [comment] 2017-12-07 13:11
That sounds weird. Basically I am running a small dev instance on my puny laptop with > 1.5M attributes and I can push ~10+ attributes / sec on it, so something sounds wrong there.

Could you list the following pieces of info?

php max memory, mysql innodb cache size, the number of correlations you currently have in MISP (global actions -> statistics has the data)

**Comment by FurqanKhan1** [comment] 2017-12-07 13:29
Hi ,Thanks a lot  !


Really appreciate your prompt reply.

Here are the details as under 

I am using mysql 5.7 at backend.

innodb_buffer_pool_size = 128M
number of correlations = 553991 
php max memory : memory_limit = 8048M 

I do understand that the memory limit for php is very high ,but i was running into issues while generating exports ,so had to increase it.

The number of co-relations look reasonably acceptable and not very high ,does it have to do with the buffer_pool_size of 128M...


Thanks 
Furqan

**Comment by iglocska** [comment] 2017-12-07 15:23
That buffer_pool_size is tiny (though it still shouldn't be this slow...)

**Comment by FurqanKhan1** [comment] 2017-12-10 07:36
@iglocska  
@adulau 

I have tried changing the buffer_pool_size to larger value (60% of the RAM) ,but still the issue seems to persist.Is there any other place i can look into to debug further.


To add more context to it ,i had added debug code-snippets to figure out where exactly the time is being consumed (is it the associative write to multiple tables or something else )
Following are the results of the added snippets 
![image](https://user-images.githubusercontent.com/15893015/33805040-37083a6c-ddcb-11e7-8a8a-ee309b395e7b.png)


As it can be seen that there is a 20 seconds delay between the message "Attribute Creating" and "Finished Attribute  After Save" message. Which is logged for each new IOC /attribute to be added.

I added the log messages at following places 
Model/Feed.php 
![image](https://user-images.githubusercontent.com/15893015/33805060-769c9d58-ddcb-11e7-8dbc-9738cd637fe7.png)



Model/Attribute.php
![image](https://user-images.githubusercontent.com/15893015/33805067-9bee3c1a-ddcb-11e7-8611-ab6b7fd06415.png)

![image](https://user-images.githubusercontent.com/15893015/33805072-bcca3a38-ddcb-11e7-9d6f-9f6c89aba766.png)


The only thing ,i am able to deduce is that ,the delay is caused by processing logic before or by the save command itself.

Currently i have 1000k entries in the co-relations table and around 280k entries in the attributes table.


Furthermore ,the caching i am using with my application is file caching given as under ,in the file core.php

Cache::config('default', array('engine' => 'File'));
Configure::load('config');

Currently i am working with debug mode as =0 ,but i also tried with mode=1 ,but no luck..
As suggested ,i also updated the buffer_pool_size ,and then restarted everything ,but no luck again..


Furthermore ,i also disabled co-relation for a particular event in order to verify weather was it the co-relation that could be causing this ,but again the write time as the same -> 20 seconds.

I am working on CentOS 7 ,Mysql5.7 ,64 bit OS ,8GB ram, and 500GB h disk.

Can any one  help me resolve /optimize this ,i would be really grateful.

Regards
Furqan

**Comment by FurqanKhan1** [comment] 2017-12-11 11:42
Hi @iglocska , @adulau 

Just to add an update on it ,on debugging it further , i realised that ,when i comment out the prepossessing and post processing logic (i.e) BeforeSave and AfterSave in attributes.php ,the save operation takes one second per >100 attributes.

Following is the screen shot of Attributes.php of commented out code 

![image](https://user-images.githubusercontent.com/15893015/33829336-45dbffe2-de89-11e7-9a5e-bc638de6bb35.png)

![image](https://user-images.githubusercontent.com/15893015/33829376-68ed3212-de89-11e7-91a5-89eeb8e9beef.png)


This implies that its the pre-processing and post-processing logic that causes the delay ,which makes me wonder does it have to do with mysql or its something at application level itself.

Would really appreciate your reviews over the same.

Regards
Furqan

**Comment by iglocska** [comment] 2017-12-11 13:33
Pre and post processing include the correlation, which is the heaviest part
of adding data. Do you have advanced correlations enabled by any chance?

**Comment by FurqanKhan1** [comment] 2017-12-11 14:08
@iglocska  ,actually no ,i do not have advance correlations enabled at all ,and just to correct my earlier comment where i mentioned that commenting out the logic was increasing the speed ,actually yes the loop was iterated very fast but since i had commented out the validation part also :beforeValidate function in attribute.php ,actually it did not save any ioc to the event ,rather just iterated and rinted to the custom log file ....

I seem to be running out of options to understand why this is happening .

To give few more highlights -

1) Irrespective of size of table at back end ,there is a constant delay of 20 seconds /save operation in this   function saveFreetextFeedData ,also Note that ,if i point the feed to create a new event ,the line where it creates new event $result = $this->Event->save($event); ,also adds a 20 seconds delay /consumes 20 seconds (verified by custom log file).
2) I have exactly the same OS at a different box ,and i am running it as a virtual image ,with same codabase and everything ,but there the turnaround time is =1 second /ioc.
3) Just to verify further ,,i created a dummy model and at different controller added around 30 values in less then a second to that dummy model.


I have verified all the configuration files of mysql ,php.ini ,rh-php -php.ini and they seem to be exactly same as i have in my home computer...
The only difference may be version of php (not sure of that ,will have to check tonight)...


The misp application is using php 7.02 and the resqueue stack is invoked by rh-php56 as follows : 
su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/MISP/app/Console/worker/start.sh'


Is there anything that you can possibly establish...

Thanks and regards
Furqan

**Comment by iglocska** [comment] 2017-12-11 14:52
Very odd, I'll try to recreate it. Is it one of the default feeds, just so
I can reproduce it using the same types etc?

**Comment by FurqanKhan1** [comment] 2017-12-11 15:15
@iglocska  ,Hi i just established that it probably has to do nothing with the size of the database /table records.

I just took a backup of all the data and cleaned up everything on the actuall db ,Then tried fetching from feeds to see if the behaviour persists ,to my surprise the feeds of type misp were very fast (>200 ioc / second).


But the moment it  reached to free text feeds (so that the code causing trouble would get triggered  ) ,again it took 20 seconds /ioc even for an empty database !! .

For very small feed sources like -
https://rules.emergingthreats.net/blockrules/compromised-ips.txt


So either i have wrongly configured something ,which is causing this or ...cant say...

Thanks and Regards
Furqan

**Comment by iglocska** [comment] 2017-12-11 15:18
That sounds horribly wrong. On a new database 20 seconds/ioc is weird as hell. Will test it today still.

**Comment by iglocska** [comment] 2017-12-11 15:21
Just tried that feed on my dev laptop with a dirty instance - 25 seconds for the full feed import. Something is definitely wrong there.

**Comment by adulau** [comment] 2017-12-11 15:22
@iglocska import or caching?

**Comment by iglocska** [comment] 2017-12-11 15:22
I imported. New event, 1.5k attributes.

**Comment by adulau** [comment] 2017-12-11 15:23
60 attributes/second.

**Comment by iglocska** [comment] 2017-12-11 15:26
Anything weird in your error logs?

**Comment by FurqanKhan1** [comment] 2017-12-11 15:30
Hi @iglocska  , @adulau 

Yes ,it does seem that there is something wrong in here ,but i am having a hard time to establish where exactly and what exactly....

I have gone through all the config files multiple times ,and cant find anything there ..
With type MISP (feeds) ,its very quick ,but with Free-text ,even when i disable co-relation and on a fresh database its taking 20 seconds....

Any possible thing /direction you guys could point me to where i should be looking !!

Thanks and regards.

**Comment by adulau** [comment] 2017-12-11 15:31
- What kind of filesystem where the database sits on?
- Physical disks? SSD or HDD? iotop?
- Virtual server?

**Comment by FurqanKhan1** [comment] 2017-12-11 15:44
Anything weird in your error logs? 
@iglocska  , No nothing that i can really confirm.

@adulau 

- - Filesystem is - ext4 
- Physical disk is HDD
- Yes it is a virtual Server

But to add on that ,i am using Mysql with some other apps also ,and there is no latency .delay in read write operations ,also to test it ,i added a tiny snippet with misp app itself that would push 10,20 records to a dummy table on loading the feeds page (feeds controller) ,there the operation was very fast (1 sec -20,30 writes).


i was running into issues with group by clause that misp uses and mysql5,7 ,as of which i just add this simple line:
 set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

But i do the same in my other box ,where it seems to work fine ..with the avg speed of 1-2 ioc/second (this 1 is a virtual image) ,so its likely to be slow ,but not as slow as this one..


Thanks
Furqan

**Comment by FurqanKhan1** [comment] 2017-12-12 11:11
Hi guys 

@iglocska  , @adulau 

The difference bewteen my home computer and this one ,was just version of mysql (5.7.19 at home) and 5.7.20 on the current box having delay issue.
I have downgraded to mysql5.7.19 here as well ,but no luck.It seems to do every write operation at 20 seconds when it comes to this piece of code : saveFreetextFeedData
// $result = $this->Event->save($event); Even this takes 20 seconds ,and the strangest part is that i have the exact same version code working fine at home !!....

Would try to do a fresh install of MISP and cake ,will see if something helps there..
This is kind of really strange tough..

Following is the memory partition on my machine ,mysql is not mounted at an extended partition ,but a linux partition only...

Is there anything you can establish here ?
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sda8       26639332 6010464  19252612  24% /
devtmpfs         3990868       0   3990868   0% /dev
tmpfs            4005288   24776   3980512   1% /dev/shm
tmpfs            4005288   66472   3938816   2% /run
tmpfs            4005288       0   4005288   0% /sys/fs/cgroup
/dev/sda2       31864656 5772280  24450700  20% /usr
/dev/sda7        3008560  972736   1863280  35% /tmp
/dev/sda1         560120  287624    231500  56% /boot
/dev/sda5       17305968  121436  16282388   1% /home
/dev/sda3       19091540 5772480  12326192  32% /var
tmpfs             801060      12    801048   1% /run/user/42
tmpfs             801060      48    801012   1% /run/user/0
[root@meysocctidev01 mysql]# fdisk -l

Disk /dev/sda: 107.4 GB, 107374182400 bytes, 209715200 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x0006b159

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048     1173503      585728   83  Linux
/dev/sda2         1173504    66185215    32505856   83  Linux
/dev/sda3        66185216   105246719    19530752   83  Linux
/dev/sda4       105246720   209715199    52234240    5  Extended
/dev/sda5       105248768   140679167    17715200   83  Linux
/dev/sda6       140681216   149069823     4194304   82  Linux swap / Solaris
/dev/sda7       149071872   155318271     3123200   83  Linux
/dev/sda8       155320320   209715199    27197440   83  Linux
[root@meysocctidev01 mysql]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk 
sda      8:0    0  100G  0 disk 
├─sda1   8:1    0  572M  0 part /boot
├─sda2   8:2    0   31G  0 part /usr
├─sda3   8:3    0 18.6G  0 part /var
├─sda4   8:4    0    1K  0 part 
├─sda5   8:5    0 16.9G  0 part /home
├─sda6   8:6    0    4G  0 part [SWAP]
├─sda7   8:7    0    3G  0 part /tmp
└─sda8   8:8    0   26G  0 part /


Is there a chance it may have to do something with the slow inserts .


Thanks and regards
Furqan

**Comment by adulau** [comment] 2017-12-12 14:20
@FurqanKhan1 Could it be that you upgrade the MySQL part at some point? I remember an issue with some innodb backend where the upgrade was introducing some issues (instead of an install from scratch).

**Comment by FurqanKhan1** [comment] 2017-12-12 14:49
@adulau 

I did not upgrade MYSQL , it was a fresh installation on this instance.
Today again i purged /removed all  and then reinstalled ..still no luck..

I wonder is it a mysql issue or does it have to do with ORM of cakephp ,as i mentioned earlier that i am using mysql with other applications (python) on same server , where the write operation takes less than second..

thanks and regards
Furqan

**Comment by FurqanKhan1** [comment] 2017-12-13 07:57
@adulau @iglocska 

Hi guys ,Greetings of the day.

Drilling down further ,i am able to establish that there might be something wrong with cake-php ORM on my instance (probably regenerating cache for every write or lazy loading or something causing this -pardon me i come from python background ,have limited knowledge there ,hope you guys can help me out with it).

So what i did was ,i configured the feed id=4 zeustracker.abuse.ch  ,to create a new event each fetch .Earlier the event creation time was 20 seconds and each ioc was also added after a delay of 20 seconds.Now i placed a code snipped just before it would create an event ,it would also create a dummy event using RAW-SQL .The dummy event was created in less then a second where as the actual event through ORM again took 20 seconds.

Yes we may think that the ORM event save invokes the after Save method internally ,But i commented out that code which does the correlation check,and still the event creation time was 20 seconds with ORM and < 1 second with Raw sql.

The following logs and code snippets suggest the same -
![image](https://user-images.githubusercontent.com/15893015/33927372-73608398-dffb-11e7-8ad7-7b2c3cf92e11.png)

![image](https://user-images.githubusercontent.com/15893015/33927646-7d0975f2-dffc-11e7-9261-f6619d43d0d6.png)


![image](https://user-images.githubusercontent.com/15893015/33927417-b25fcf54-dffb-11e7-827d-348a126cd4f0.png)


All i am able to deduce is that something has gone wrong in the installation process of cake-php probably.

Is there anything you can suggest ,which would help me narrow it down.

Furthermore ,If i would want to use the raw-sql approach only ,i am assuming it may not invoke the BeforeSave after Save methods on its own ,and i would have to call/invoke them manually.Would that be advisable.


Adding to it ,I just checked the model cache at path /app/tmp/cache/model

The cache file for events and attributes seems to have regenerated at the time when the code last created events/attributes.I have set the debug mode to 0 in both core and config files.
![image](https://user-images.githubusercontent.com/15893015/33928311-0d2cc6d2-dfff-11e7-815f-aa003ddd3c75.png)


Also the first entry in the cache file is the timestamp ,and on converting it ,it suggested the same time when i last accessed /created an event 11:36 a.m 13 december....

Is there a chance it would have to do with the slow writing ,if yes can u kindly tell me how to get around it.

 

Thanks and Regards
Furqan

**Comment by RichieB2B** [comment] 2017-12-13 08:19
Don’t change the MISP code but fix the CakePHP issue instead. Did you already reinstall CakePHP? Did you run MISP in debug mode including SQL logging?

**Comment by FurqanKhan1** [comment] 2017-12-13 08:23
@RichieB2B  

I was just able to establish that it might be a cakephp issue ,earlier we were focussed on Mysql .

I haven't reinstalled cakephp ,will do that now .
Yes i did run MISP in debug mode ,but not with sql logging ,i used mode=1 ,will try with mode =2 .

Thanks and Regards
Furqan

**Comment by FurqanKhan1** [comment] 2017-12-13 09:21
@RichieB2B 

Can you kindly point me as to where i should be looking for the sql logs ,the debug mode is set as 2 ,and i can see the logs on my web interface ,but not for background jobs.Can u kindly let me know the source.I tried looking at /app/tmp/logs nothing there of sql.

If u referred to general error logs of Mysql - i had tried that earlier too ,could not find anything at all over there.


Thanks and Regards

**Comment by FurqanKhan1** [comment] 2017-12-14 13:36
@iglocska  , @adulau 

Hi guys ,

Current update -

I have tried uninstalling and reinstalling MISP altogether to the latest version ,cake-php ,mysql and everything i could possibly think of would be related ,but even after a fresh install and on a empty database ,the issue seems to persist.

I think that it has to do with ORM + virtual server  (hdd/ssd) + centos .

I am saying so ,because ,as i pointed earlier too  ,i have used the same version of code in my home laptop with centos and rest everything as same ,and did not encounter any issue.

Now it brings me to two things i can try ,install virtual box on the virtual server and put centos on it and test ,put ubantu /Linux on it and test.

Kindly let me know if you have a better approach to narrow it down.

Regards
Furqan

**Comment by iglocska** [comment] 2017-12-14 14:56
No clue really what could be going on - but since it's a shared disk, maybe your HDD is being hammered?

**Comment by FurqanKhan1** [comment] 2017-12-16 15:34
@iglocska  , @adulau 

Hi guys  ,
Narrowing it down ,i finally seem to have arrived to the point as to where the delay is happening.

As i had pointed out earlier ,there was a 20 seconds delay at two places -
For Free text based Events -
1) When ever a scheduled fetch /or manual pull created a new event.Event creation time was 20 seconds
2) Once the event was created ,the push of each IOC from parsed data also took 20 seconds each.

Now i am able to see that teh actual delay is not caused by the ORM Save ,but instead by the method beforeValidate.

![image](https://user-images.githubusercontent.com/15893015/34071828-598cae04-e296-11e7-8218-71bd8af39737.png)


The custom logs that i am creating validated the same -

![image](https://user-images.githubusercontent.com/15893015/34071844-85dd3a78-e296-11e7-9ccb-2306159b15ca.png)


Please note that the delay is between start validate and end validate.

Earlier on ,i said raw SQL is working much faster ,it was because of the fact that it never called the beforevalidate method.

I have checked for it on EventSave ,i am sure the same woukd be the reason on AttributeSave..(altough i am yet to verify that)..

Edit : Just verified Its the same method Before Validate for attributes also which is taking 20 seconds to process.

I cant see too many DB operations on the BeforeValidate method...

Any idea on why would it take 20 seconds //....

I hope we can establish something here that would help me fix this..


@iglocska , @adulau 
Edit 2: 
I cant believe ,it is this line CakeText::uuid() ,this line seems to take 20 seconds on my office server ,and it takes < second on the home computer.

Now i know that uuid   contains a reference to the network address of the host that generated the UUID, a time-stamp (a record of the precise time of a transaction), and a randomly generated component.

It may have to do with the fact that in this box misp code is sitting behind a corporate proxy ,and probbaly the address translation /etc may take time...

Its the same line which is there in beforeValidate of attributeSave .

![image](https://user-images.githubusercontent.com/15893015/34072337-1b2fe56e-e29f-11e7-8d57-78f7b2393296.png)


The logs excatly point that its Generating uuid and generated UUID -Thats what takes 20 seconds --
Any inputs on as how i should get around this one.


My current fix is that ,i am generating the uuid with python -> uuid.uuid4() ,and invoking the python script from the php code ,this is a temporary fix ,can u suggest or guide me for a better one ,and can u tell me  is there a chance that it could be a bug with php method  itself ,when used in a network as i am currently in ,or it may have to do with some misconfigured server file that cakephp::uuid() method uses to generate one.

Had there been an issue /misconfiguration with the server ,than probably python code would also be taking time ,which is not the case here !!!


Just to inform ,now i am able to easily do 40 attributes / sec...


Thanks and Regards
Furqan

**Comment by iglocska** [comment] 2017-12-17 16:22
What the hell! The uuid creation is 20 seconds??? I need to look into this, that is weird to say the least. Not enough entropy perhaps?

**Comment by iglocska** [comment] 2017-12-17 16:28
Indeed, it looks like uuid() has 3 mt_random() calls which each call /dev/urandom. This in itself is fine, but considering that you're running a virtualised machine, it could happen that you are exhausting your entropy. Could you install and run haveged in the background and see if the speed bounces back up?

**Comment by adulau** [comment] 2018-01-08 15:32
@FurqanKhan1 Is the issue fixed with the user-space random generator? I'll close the issue. Feel free to reopen if the issue is not fixed. Thank you very much for the detailed analysis and report.

**Closed as completed by adulau** 2018-01-08 15:32 UTC
Labels: T: support
