### ISSUE TITLE
Issue with "List events" view related to Threat Actors & Tools

### ISSUE THREAD

**Issue by LegitUsername** [MISP/MISP#1780] opened 2016-12-22 12:13 UTC
### Work Environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 3.16.0-4-amd64
| PHP version               | 5.6.29
| MISP version / git hash   | 2.4.57
| Browser                   | Chrome

I'm using MISP latest version at the moment (2.4.57). My server and the CIRCL's instance are synchronised correctly, i.e. I am pulling all published events as expected.

### Expected Behavior
If I am correct, when pulling events and attributes, I should have exactly the same view in "List events" on my instance than the CIRCL's instance, including the new "Clusters" field.

### Actual Behaviour
The "Clusters" field from the "List events" view seems to be completed on a random (?) basis when I compare my instance with the CIRCL's one. 

There are events (for instance id 5585 on the CIRCL's instance) where "Clusters" is empty on my instance but filled with " PROMETHIUM" and "NEODYMIUM" on the CIRCL's server. When I click on the event, the "Galaxies" field is empty but the tag list contains "misp-galaxy:threat-actor="PROMETHIUM" and same for NEODYMIUM" (which is not the case on the CIRCL's instance).

Similarly, the "Sofacy" threat actor is absent from id 5616, and not even mentionned in the tags. 

Sometimes "Clusters" are correct when I compare, and sometimes there're not.

Has anyone experienced the same issue ?

**Comment by iglocska** [comment] 2016-12-22 12:22
It basically means that your galaxies are not up to date. All galaxies are using the shared repository currently and are attached to an event via a tag.

If your MISP doesn't have the information on a cluster, it will simply display it as a tag (until you get the cluster in your db).

Simply run git submodule update on your instance and after that go to the galaxy list (galaxies -> list galaxies) and update the list. After that it should look the same as it does on the CIRCL instance.

Let me know if it didn't work!

**Comment by LegitUsername** [comment] 2016-12-22 12:49
Thanks for replying so fast.

I ran git sumbodule update -> no change.
I decided to go with the update process (git pull origin 2.4 + git submodule update) -> no change either.
Just to check, I ran "pull all" on the CIRCL's instance afterwards but no luck either...

**Comment by iglocska** [comment] 2016-12-22 12:50
did you run the update within MISP?

**Comment by LegitUsername** [comment] 2016-12-22 12:52
what dou you mean within MISP ?

**Comment by iglocska** [comment] 2016-12-22 12:55
Galaxies -> List Galaxies -> Update Galaxies

**Comment by LegitUsername** [comment] 2016-12-22 12:56
Yes i did it too, after the submodule update command

**Comment by iglocska** [comment] 2016-12-22 13:02
Hmm weird, you are indeed correct. My guess is that the misp galaxy reference in the MISP repository is out of date and the one on the CIRCL instance has modifications that are not available by default yet. Let me have a look.

**Comment by iglocska** [comment] 2016-12-22 13:06
Just pushed the latest version and for me it resolves it.

Could you run:

```
git pull origin 2.4 && git submodule update
```

and after that update the galaxies from within MISP (galaxies -> list galaxies -> update galaxies) again?

Also, thanks a lot for the heads-up.

**Comment by RichieB2B** [comment] 2016-12-22 13:14
I can confirm that last update fixed this issue for me. Interestingly the galaxy id's changed from 1 and 2 to 3 and 4 while I expected their version numbers to be increased instead.

**Comment by LegitUsername** [comment] 2016-12-22 13:15
Thank you, that indeed updated the event 5585 and filled the "Cluster" field.

However, for the other events that did not have tags such as "misp-galaxy:threat-actor=XYZ", nothing changed.

**Comment by iglocska** [comment] 2016-12-22 13:18
Could you name an event's id where you see a difference like that? I'll debug it asap.

@RichieB2B That is correct for now, right now it just drops all galaxy information and reloads it from scratch. I'll change the behaviour later on once we get the ability to actually edit galaxies and want persistence but for now it's just a costmetic issue.

**Comment by LegitUsername** [comment] 2016-12-22 13:24
Thank you again, please find below some events' ids (from page 1 and 2) where there is a difference:
5616, 5595, 5592, 5591, 5590, 5588, 5587, 5348, 5563.

I doesn't seem to be threat actor related, or even publisher related.
I hope you will be able to see a pattern. Feel free to ask me for more ids if you need some more.

**Comment by iglocska** [comment] 2016-12-22 13:30
Hmph that is weird, I just pulled some of those to my dev instance and I don't see any differences. Is it still the same symptom (some clusters appearing as tags instead of proper galaxy clusters?)

**Comment by LegitUsername** [comment] 2016-12-22 13:33
No that problem has been solved. For those ids, there are no galaxy-related tags.
I'm gonna try to pull all events once more.

**Comment by iglocska** [comment] 2016-12-22 13:38
Curious! If all else fails, try to delete the event and pull it again, though it's weird.

**Comment by RichieB2B** [comment] 2016-12-22 13:52
I'm seeing the same issue as @LegitUsername : a lot of events already pulled do not have the misp-galaxy tags. For example: CIRL has 13 events with misp-galaxy:tool="Mirai" while I locally only have 2. Deleting them locally is not really feasible because I'd need to know which ones to delete first.

**Comment by iglocska** [comment] 2016-12-22 13:54
Hmm that is weird. I think it's the same old issue, tagging doesn't trigger a sync. We need to resolve this asap.

**Comment by RichieB2B** [comment] 2016-12-22 13:54
Could it be that these events were tagged on the CIRL MISP after they were published? Changing tags does not change the event timestamp..

**Comment by iglocska** [comment] 2016-12-22 13:54
Yep. Indeed.

**Comment by iglocska** [comment] 2016-12-22 13:55
Kind of tempted to unpublish events if you tag them with an exportable tag.

**Comment by RichieB2B** [comment] 2016-12-22 14:00
Not a bad way to resolve #643. Having a fix for #1258 would be handy as well.

**Comment by iglocska** [comment] 2016-12-22 14:01
yeah the biggest issue with that is that you'll end up updating events by just locally tagging events (which is something that site admins often do and override the local rules). You may end up inadvertantly blocking and updated event by tagging something.

So as an inbetween solution only doing it for exportable tags could work - as in those cases you want to push the information out.

**Comment by RichieB2B** [comment] 2016-12-22 14:06
Sounds good. Make sure you give a visual indication that the event is unpublished, otherwise I'll have to open another issue like #1763 ;-)

**Comment by LegitUsername** [comment] 2016-12-22 14:10
Mmmmh I see. 
Thing is, I deleted 2 events to see if re-pulling would temporarly solve the issue, but they were not pulled ...

**Comment by iglocska** [comment] 2016-12-22 14:13
You probably have the blacklist deleted event function turned on.

```
MISP.enableEventBlacklisting
```

in the settings.

@RichieB2B haha, good point ;)

**Comment by LegitUsername** [comment] 2016-12-22 14:21
Indeed ! thank you iglocska.

**Comment by iglocska** [comment] 2016-12-22 14:37
OK, let's keep this thread open, this is a recurring issue with the tagging and it's something we need to resolve asap.

**Comment by iglocska** [comment] 2016-12-23 08:37
OK, whilst the current fix won't solve the issues for previous events, it should now be fixed for all future events. Adding a tag (no matter if exportable or not) unpublishes the event. After putting some thought into it, this makes a lot more sense than a few months ago as tags, through the galaxies, carry much more information than the initial design of the system intended and attaching a galaxy cluster can change the meaning of an event pretty heavily. Sadly the only real solution for older events is removing / repulling them.

I'll close the issue for now, feel free to open a new one if you have any ideas / issues with it!

**Closed as completed by iglocska** 2016-12-23 08:37 UTC
