### ISSUE TITLE
NIDS Extraction - Extra space

### ISSUE THREAD

**Issue by 0xtf** [MISP/MISP#3875] opened 2018-11-14 18:21 UTC
Hi,

Currently rules are generated as:

`alert ip $HOME_NET any -> REDACTED 80 (msg: "MISP e12141 [] Outgoing To IP: REDACTED|80";   classtype:trojan-activity; sid:21011079; rev:1; priority:2; reference:url,https://REDACTED;)` 

Even though it's minimal, there is an additional space after the rule msg and the classtype. This appears to be present in all my extracted rules.

**Comment by 0xtf** [comment] 2018-11-14 18:26
![screenshot from 2018-11-14 18-25-03](https://user-images.githubusercontent.com/24301448/48503719-ca06f180-e83a-11e8-8684-50382810541a.png)
An image makes it a bit more clear to understand.

**Comment by cvandeplas** [comment] 2018-11-15 12:42
This is actually caused by the templating used to build the NIDS rules.
In some rules some of the sub-elements are empty, but the [`$ruleFormat`](https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsExport.php#L141) template contains spaces between those variables (`%s`).
See also [L246](https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsExport.php#L246) of the [NidsExport.php](https://github.com/MISP/MISP/blob/2.4/app/Lib/Export/NidsExport.php) file.

Why is this spacing an issue? Is is just for cosmetic reasons or is it breaking some other things?

**Comment by 0xtf** [comment] 2018-11-15 13:51
No problems whatsoever. Just noticed it was there and decide to report it.

My initial report was regarding the alert categories of exported events,
but I realized there’s already an open issue about that. Decided to still
post this one.

**Comment by cvandeplas** [comment] 2018-11-15 14:27
Thank you, I'll then close the issue as preventing this behavior would add some unneeded complexity to the code. Feel free to re-open if it breaks things elsewhere.

**Closed as completed by cvandeplas** 2018-11-15 14:27 UTC

**Comment by Alaa-HIjazi** [comment] 2020-04-16 08:05
'am trying to Curl with nids : curl -k --header "Authorization: key" --header "Accept: application/json" --header "Content-Type: application/json" https://misp.local/events/nids/suricata/download/2/false/tag1/
the following output is shown:

# MISP export of IDS rules - optimized for 
#
# These NIDS rules contain some variables that need to exist in your configuration.
# Make sure you have set:
#
# $HOME_NET	- Your internal network range
# $EXTERNAL_NET - The network considered as outside
# $SMTP_SERVERS - All your internal SMTP servers
# $HTTP_PORTS   - The ports used to contain HTTP traffic (not required with suricata export)
Any Suggestions ?

**Comment by Alaa-HIjazi** [comment] 2020-04-16 08:05
'am trying to Curl with nids : curl -k --header "Authorization: key" --header "Accept: application/json" --header "Content-Type: application/json" https://misp.local/events/nids/suricata/download/2/false/tag1/
the following output is shown:
```
# MISP export of IDS rules - optimized for 
#
# These NIDS rules contain some variables that need to exist in your configuration.
# Make sure you have set:
#
# $HOME_NET	- Your internal network range
# $EXTERNAL_NET - The network considered as outside
# $SMTP_SERVERS - All your internal SMTP servers
# $HTTP_PORTS   - The ports used to contain HTTP traffic (not required with suricata export)
```
Any Suggestions ?
