### ISSUE TITLE
Character Limit on Comments?

### ISSUE THREAD

**Issue by ninjadru** [MISP/MISP#6324] opened 2020-09-18 16:27 UTC
# This template is meant for bug reports, if you have a feature request user the other template.
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | RHEL
| PHP version               | 7.3
| MISP version / git hash   | v2.4.128
| Browser                   | If applicable

### Expected behavior
Use API to post a comment to an event

### Actual behavior
This works:
curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: XXXX" --data "{"Event":{"comment":"test"}}" -X POST http://misp.XXXX.com/posts/add/event//1234
{"Event":{"Attribute":[{"comment":"test"}]}}

However using a SOAR tool (Phantom) and a long comment I seem to get JSON errors. It appears the API has a character limit or some from of truncation.

### Steps to reproduce the behavior
curl -i -H "Accept: application/json" -H "content-type: application/json" -H "Authorization: XXXX" --data "{"Event":{"comment":"test"}}" -X POST http://misp.XXXX.com/posts/add/event//1234
{"Event":{"Attribute":[{"comment":"LOTS OF TEXT GOES HERE"}]}}

**Comment by chrisinmtown** [comment] 2020-09-29 23:55
Maybe you should move this issue to the PyMISP project area.  There I see a *very similar* question about comments, please read it, @rafiot explains there that events do not have comments, only attributes: https://github.com/MISP/PyMISP/issues/618

Also you should say what length comment triggers a failure - one hundred characters, one million characters, ?

**Comment by Rafiot** [comment] 2020-09-30 21:07
The call it definitely going to bounce, as the data is invalid, it has nothing to do with the length: an attribute **requires** a value field, and a type, at least. Just passing a comment will fail.

**Comment by enjeck** [comment] 2020-11-22 14:23
This is more of a support issue, not a bug. It's been addressed, I believe. Closing for now. It can be reopened if need be.

**Closed as completed by enjeck** 2020-11-22 14:23 UTC
Labels: T: support, S: diagnosed, R: fixed
