### ISSUE TITLE
"Explore events remotely page" not displaying most recent events

### ISSUE THREAD

**Issue by iamshleya** [MISP/MISP#1812] opened 2017-01-06 14:45 UTC

**Comment by adulau** [comment] 2017-01-06 15:55
In the current version of MISP, there is no scheduled job for the OSINT feeds. You need to fetch it manually by clicking on the download arrow icon. 

We plan to update this quite soon. Thank you for your report.

**Comment by adulau** [comment] 2017-01-06 15:58
Regarding the browsing by itself, I suppose the caching (recently introduced) is still taking the old feed. 

You can check the cache by looking at the specific files in  /var/www/<MISP>/app/tmp/cache/misp_feed* and you can also remove the file as you wish.

**Comment by iglocska** [comment] 2017-01-07 22:39
We had a chat about this with @adulau and the two things are not directly related - the caching only happens for freetext/csv feeds, not for MISP feeds. I don't seem to be able to reproduce the issue on any of my systems, I can see the latest event on all of them. Very odd.

**Comment by iamshleya** [comment] 2017-01-11 14:53
Thanks for the quick response. Just to be clear, I really only want to see the most up to date events remotely, so that I can pick and choose which ones to download to my instance. Looking at the feed remotely, the most recent one I can find is from January 8th but looking at the feed directly through the url, there's events from yesterday (January 10th). I tried to fetch manually by selecting "Fetch all events" (download arrow icon)  but then it added all the events locally.

Any other suggestions for viewing the most recent events remotely?

**Comment by StefanKelm** [comment] 2017-11-28 10:04
On a possibly related note: sorting events while exploring MISP feeds remotely doesn't do anything:
![auswahl_001](https://user-images.githubusercontent.com/25325656/33313715-c1575c2e-d42b-11e7-9650-536106e619ac.png)
![auswahl_002](https://user-images.githubusercontent.com/25325656/33313716-c18504ee-d42b-11e7-9102-1bb305daaa2e.png)
![auswahl_003](https://user-images.githubusercontent.com/25325656/33313717-c1adf840-d42b-11e7-8ee3-24e67cc78751.png)
![auswahl_004](https://user-images.githubusercontent.com/25325656/33313718-c1d962b4-d42b-11e7-8de2-39de02bf74d2.png)

**Comment by SteveClement** [comment] 2019-02-04 05:57
Closing due to non-activity.

Feel free to re-open with updated content.

**Closed as completed by SteveClement** 2019-02-04 05:57 UTC
Labels: T: enhancement, c-list, topic: feed, S: under investigation, S: review before closing
