### ISSUE TITLE
Erreur message on view log to other Org

### ISSUE THREAD

**Issue by truckydev** [MISP/MISP#1479] opened 2016-08-26 11:30 UTC
Sample : 
"user1" from org "One"
"user2" from org "Two"

My event was create whis user1.
When i try to view history event logs with user2 I have a page internal error.

The logic is ok but it will be cool to have a good message :)

| Questions | Answers |
| --- | --- |

| MISP version / git hash   | 2.4
### Expected behavior

Explanatory message like : 
You do not have the good right to view this information right.
### Actual behavior

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.
### Steps to reproduce the behavior

try to view history event from a user who are not in the Event org

**Comment by iglocska** [comment] 2016-08-26 11:35
Hmm that sounds like a bug. The event history should be visible to all that have access to the event

**Comment by iglocska** [comment] 2016-08-26 11:39
I just tried it on my dev system and I couldn't reproduce it.

Here are a few questions that could help with figuring it out:
1. Which version of MISP are you on? (Best would be a commit ID)
2. Is the event you created private? Is it in a sharing group?
3. Could you check the actual error message? It should be in /var/www/MISP/app/tmp/logs/error.log

Thanks in advance!

**Comment by truckydev** [comment] 2016-08-26 14:32
My MISP version is up-to-date ^_^
1. last commit : 399a039065d716f1d09b3672b0276643062b8165  
   - PHP 5.6.24-0+deb8u1  
   - All permissions are set correctly

2.1. Local orgasisation :  
- 1    Test1   Test1   xxx Automatically generated admin organisation  
- 2    Test2   Test2   xxx temporaire  

2.2. Users :   
- 1    Test1   User    test@test.com  
- 2    Test2   User    tmp@test.com  

2.3. Test Event : 

```
|Published | Org    | Id    | Attr. |...| Distribution | Actions            |
|No            | Test1  |   45 | 144  |...| Community | Not published  |
|Yes           | Test1 |    39 |   31  |...| All               |                        |
```

my user test(org test1) can go to event 45 ans 39 and to the history view.
but with tmp(org test2) have an internal error.
1.  
   It was the right place to look

```
2016-08-26 16:23:21 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Attribute.email' in 'field list'
Request URL: /logs/event_index/45
```

This error is certainly due to the change I made (sorry, all my bad) : 
https://github.com/MISP/MISP/issues/1389

```
Stack Trace:
#0 /MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): PDOStatement->execute(Array)
#1 /MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(434): DboSource->_execute('SELECT `Attribu...', Array)
#2 /MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(671): DboSource->execute('SELECT `Attribu...', Array, Array)
#3 /MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1120): DboSource->fetchAll('SELECT `Attribu...', false)
#4 /MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3031): DboSource->read(Object(Attribute), Array)
#5 /MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3003): Model->_readDataSource('all', Array)
#6 /MISP/app/Controller/LogsController.php(102): Model->find('all', Array)
#7 [internal function]: LogsController->event_index('45')
#8 /MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(LogsController), Array)
#9 /MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#10 /MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(LogsController), Object(CakeRequest))
#11 /MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
```

**Comment by truckydev** [comment] 2016-08-26 14:36
I just add ", 'email'" https://github.com/MISP/MISP/blob/2.4/app/Controller/LogsController.php#L107
And not in this line https://github.com/MISP/MISP/blob/2.4/app/Controller/LogsController.php#L90

And it works ^_^

**Comment by iglocska** [comment] 2016-08-26 15:02
Ah ok, that's good news ;) I'll close the issue then!

**Closed as completed by iglocska** 2016-08-26 15:02 UTC
