### ISSUE TITLE
Install on Ubuntu 18.04 failing

### ISSUE THREAD

**Issue by rbcrack** [MISP/MISP#6790] opened 2020-12-22 19:42 UTC
I am installing fresh install of MISP and it keep failing on 

**sudo: /var/www/MISP/venv/bin/pip: command not found
apt is maybe locked, waiting 3 seconds.
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>**

Cannot fix the error no matter what I do please help

**Comment by rbcrack** [comment] 2020-12-22 20:50
> I am installing fresh install of MISP and it keep failing on
> 
> **sudo: /var/www/MISP/venv/bin/pip: command not found
> apt is maybe locked, waiting 3 seconds.
> You are not currently on a branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
> ```
> git pull <remote> <branch>**
> ```
> 
> Cannot fix the error no matter what I do please help

Still, no luck I have tried in a fresh install of Ubuntu install 18.04 and same error

**Comment by peanuter** [comment] 2021-06-21 15:35
I am experiencing the same issue. Any update on when this will be patched?

**Comment by barvhaim** [comment] 2022-01-05 10:22
same error

**Comment by SteveClement** [comment] 2022-01-07 02:04
I literally tested it right now. And it worked on Ubuntu 18.04.6 without any issues.

Please run the installer with:  bash -x /tmp/INSTALL.sh -c

And include the debug output.

Closing until update.

Thanks.

**Closed as completed by SteveClement** 2022-01-07 02:04 UTC
Labels: T: support, topic: install, R: cannot reproduce

**Comment by william-mack** [comment] 2022-08-08 18:14
I am still having this issue on Ubuntu 18.04.6

**Comment by zumzen** [comment] 2022-08-12 14:39
Hi, 
I have the same issue on Ubuntu 20.04

**Comment by ml58158** [comment] 2022-09-02 16:36
This fixed the issue for me.

The issue is related to not being able to write to the /var folder and install venv. 

Run this outside of the MISP setup. 

sudo virtualenv -p python3 /var/www/MISP/venv

**Comment by aumaxx** [comment] 2023-06-06 09:58
I am attempting to install MISP on 22.04 and I am getting the following error.

sudo: /var/www/MISP/venv/bin/pip: command not found
apt is maybe locked, waiting 3 seconds.

when I navigate to /var/www/MISP/venv there is no /bin/pip but there is a /local and if I navigate to /var/www/MISP/venv/local there is a /bin/pip
