### ISSUE TITLE
Download using restSearch API call does not yield expected results

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#656] opened 2015-09-15 08:26 UTC
I am trying to download all the events modified after a certain date.
The parser I have is handling events in XML format.

I am trying to use the following URL:
https://server/events/restSearch/download/null/null/null/null/null/null/2015-09-01/
I get a response that there are no matches, despite the fact that there is when I check the web interface.
I have events that have an event date after 2015-09-01, and others that have been modified since 2015-09-01.

**Comment by iglocska** [comment] 2015-09-15 08:52
It's definitely a bug, seems like there is a misplaced bracket and it ignores almost all parameters. Will be fixed within the hour!

**Comment by iglocska** [comment] 2015-09-18 07:41
This should now be fixed.

**Comment by elhoim** [comment] 2015-09-22 08:57
Tried after a git pull this morning, and it is still outputing too many results. Used the same query.

**Comment by elhoim** [comment] 2015-09-22 08:59
**https://server/events/restSearch/download/null/null/null/null/null/null/null/null/20d/**
does not yield expected results either

**Comment by Rafiot** [comment] 2015-09-22 09:03
@elhoim: I would recommend to use the python API, this is much more reliable. Did you try?

**Comment by elhoim** [comment] 2015-09-22 09:52
Problem is that I am using a SIEM connector that expects XML, what I am trying to do is script a way to events modified in the last X days instead of reparsing everything each time I do an import.

In PyMISP, download_last (and most of the functions) are outputing JSON and forcing JSON despite the value set in the constructor.

**Comment by elhoim** [comment] 2015-09-22 10:02
Even /events/xml/download API call with a POST containing 
```xml
<request><last>5d</last></request>
```
Did not work.

**Comment by iglocska** [comment] 2015-09-22 17:50
All 3 methods are producing the correct result for me... Are you positive it's up to date?

Test that I have done:

I have 8 events in my db, only one is from september, rest is from april.

https://server/events/restSearch/download/null/null/null/null/null/null/2015-09-01/

Result: returns 1 event

https://server/events/restSearch/download/null/null/null/null/null/null/null/null/20d/

Result: returns 1 event

<request><last>20d</last></request>

Result: returns 1 event

**Comment by iglocska** [comment] 2015-09-22 17:53
Tested it on CIRCL, working as intended.

**Comment by iglocska** [comment] 2015-09-24 09:28
Any luck?

**Comment by iglocska** [comment] 2015-09-25 22:15
I'll close this for now as I can't reproduce it, feel free to re-open it if it's still not fixed for you!

**Closed by iglocska** 2015-09-25 22:15 UTC
Labels: bug, support
