### ISSUE TITLE
[Idea] make an event out of an eml

### ISSUE THREAD

**Issue by jaegeral** [MISP/MISP#1059] opened 2016-04-06 19:13 UTC
Would like to get feedback on the following user-story:

Imagine you have an eml file, maybe with attachements, and you want to create an event for it, stuff like sender-mail adress, destination, maybe target-email, attachements, body of the mail etc could be extracted automatically.

Opinions?

**Comment by iglocska** [comment] 2016-04-06 22:30
Definitely something we need sooner or later. Once we have the import module this could be an excellent module.

**Comment by elhoim** [comment] 2016-04-11 00:47
Duplicate of https://github.com/MISP/MISP/issues/143

**Closed as completed** 2016-04-11 06:31 UTC
Labels: import/export
