### ISSUE TITLE
Add tagg by attribut

### ISSUE THREAD

**Issue by ANSSI-BSOD** [MISP/MISP#1191] opened 2016-05-31 13:34 UTC
Hi team,

regardless of the specific comments on an event. It would be interesting to add more description by attribute.

Example, define a relevant, if the pattern generates false positives .

A good example would be adding a CVSS : https://www.first.org/cvss/calculator/3.0

We might as well look for example all scorers with a particular tag and a CVSS than 3 .

**Comment by iglocska** [comment] 2016-05-31 14:27
Definitely. Attribute tagging is on our short term roadmap.

**Comment by rotanid** [comment] 2016-06-12 04:29
duplicate of #802

**Closed as completed by rotanid** 2016-06-12 04:29 UTC
