### ISSUE TITLE
Export Jobs Hanging

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#1390] opened 2016-07-27 22:12 UTC
I have a MISP instance with ~100,000 malware configs, 16 CPUs, 64 GB of RAM.  The major issue is running exports (both for admin and for users, there is only one organization).  Many exports take near an hour but even with 5 cache workers, none of the other jobs seem to run.  I can successfully maybe run 1 or 2 exports and the reset simply never progress with no errors in any of the logs.
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Ubuntu |
| OS version (client) | 14.04 LTS |
| PHP version | PHP 5.5.9-1ubuntu4.17 |
| MISP version / git hash | 2.4.49 |
| Browser | If applicable |

**Comment by adulau** [comment] 2016-07-28 09:20
Interesting. Indeed, it should be work to have multiple workers for export at the same time but you might have hit a bug. We will check how we can debug this in an optimal way and let you know.

**Comment by bambenek** [comment] 2016-07-28 13:02
Happy to give you access to the box (at AWS). Seems it works fine if admin generates export. Anyone else not so much.

**Comment by iglocska** [comment] 2016-07-28 16:18
Sure. Could you give us the credentials via info@circl.lu? PGP: http://pgp.circl.lu/pks/lookup?op=get&search=0xEAADCFFC22BD4CD5

**Comment by bambenek** [comment] 2016-07-30 13:06
Key has been sent.  Ran MySQLTuner, this was the output (and I made the changes).

ubuntu@ip-172-31-58-243:~/MySQLTuner-perl$ sudo ./mysqltuner.pl 

> >  MySQLTuner 1.6.14 - Major Hayden major@mhtx.net
> >  Bug reports, feature requests, and downloads at http://mysqltuner.com/
> >  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[OK] Logged in using credentials from debian maintenance account.
[OK] Currently running supported MySQL version 5.6.31-0ubuntu0.14.04.2
[OK] Operating on 64-bit architecture

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +ARCHIVE +BLACKHOLE +CSV -FEDERATED +InnoDB +MEMORY +MRG_MYISAM +MyISAM +PERFORMANCE_SCHEMA 
[--] Data in InnoDB tables: 2G (Tables: 40)
[--] Data in MyISAM tables: 22M (Tables: 1)
[!!] Total fragmented tables: 1

-------- Security Recommendations ------------------------------------------------------------------
[OK] There are no anonymous accounts for any database users
[OK] All database users have passwords assigned
[--] There are 605 basic passwords in the list.

-------- CVE Security Recommendations --------------------------------------------------------------
[OK] NO SECURITY CVE FOUND FOR YOUR VERSION

-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 2d 16h 9m 51s (95M q [415.474 qps], 1M conn, TX: 846G, RX: 284G)
[--] Reads / Writes: 91% / 9%
[--] Binary logging is disabled
[--] Physical Memory     : 62.9G
[--] Max MySQL memory    : 93.0G
[--] Other process memory: 58.3M
[--] Total buffers: 17.5G global + 512.8M per thread (150 max threads)
[--] P_S Max memory usage: 403M
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 35.0G (55.56% of installed RAM)
[!!] Maximum possible memory usage: 93.0G (147.90% of installed RAM)
[!!] Overall possible memory usage with other process exceeded memory
[OK] Slow queries: 0% (43/95M)
[OK] Highest usage of available connections: 22% (34/150)
[OK] Aborted connections: 0.00%  (1/1410276)
[!!] name resolution is active : a reverse name resolution is made for each new connection and can reduce performance
[!!] Query cache may be disabled by default due to mutex contention.
[OK] Sorts requiring temporary tables: 0% (135 temp sorts / 17M sorts)
[!!] Joins performed without indexes: 2421364
[!!] Temporary tables created on disk: 99% (2M on disk / 2M total)
[OK] Table cache hit rate: 94% (202 open / 214 opened)
[OK] Open file limit used: 1% (60/5K)
[OK] Table locks acquired immediately: 99% (53M immediate / 53M locks)

-------- Performance schema ------------------------------------------------------------------------
[--] Performance schema is enabled.
[--] Memory used by P_S: 403.8M
[--] Sys schema isn't installed.

-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is disabled.

-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 18.7% (100M used / 536M cache)
[OK] Key buffer size / total MyISAM indexes: 512.0M/11.9M
[OK] Read Key buffer hit rate: 100.0% (72M cached / 2K reads)
[OK] Write Key buffer hit rate: 99.8% (1M cached / 2K writes)

-------- AriaDB Metrics ----------------------------------------------------------------------------
[--] AriaDB is disabled.

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[OK] InnoDB buffer pool / data size: 16.0G/2.2G
[!!] InnoDB buffer pool instances: 8
[!!] InnoDB Used buffer: 14.59% (152945 used/ 1048568 total)
[OK] InnoDB Read buffer efficiency: 100.00% (2792531142 hits/ 2792549610 total)
[!!] InnoDB Write Log efficiency: 86.71% (17564377 hits/ 20256671 total)
[OK] InnoDB log waits: 0.00% (0 waits / 2692294 writes)

-------- TokuDB Metrics ----------------------------------------------------------------------------
[--] TokuDB is disabled.

-------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is disabled.

-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] No replication slave(s) for this server.
[--] This is a standalone server.

-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    Run OPTIMIZE TABLE to defragment tables for better performance
      OPTIMIZE TABLE misp.cake_sessions; -- can free 48 MB
    Total freed space after theses OPTIMIZE TABLE : 48 Mb
    Reduce your overall MySQL memory footprint for system stability
    Dedicate this server to your database for highest performance.
    Configure your accounts with ip or subnets only, then update your configuration with skip-name-resolve=1
    Adjust your join queries to always utilize indexes
    When making adjustments, make tmp_table_size/max_heap_table_size equal
    Reduce your SELECT DISTINCT queries which have no LIMIT clause
Variables to adjust:
  **\* MySQL's maximum memory usage is dangerously high ***
  **\* Add RAM before increasing MySQL buffer variables ***
    query_cache_type (=0)
    join_buffer_size (> 512.0M, or always use indexes with joins)
    tmp_table_size (> 16M)
    max_heap_table_size (> 16M)
    innodb_buffer_pool_instances(=16)

It seems that the admin export works, but when a user runs the export it hangs.  Additionally, the snort and suricata exports seems to take forever in particular.

**Comment by iglocska** [comment] 2016-07-30 17:42
I've made some changes that should resolve the issues with it working for the admin but not other users at least, so if you could, just git pull and give it a shot. I'll try to have a look at your instance to see what we can do to improve it further.

Another issue I noticed is that you keep your events unpublished, which caused issues with certain exports that only use published items (they seem to have failed as they were executed but didn't actually receive any valid input). This should now be in better shape, so you won't be able to start generating exports that would result in empty sets. 

Also, I've added a JSON export.

**Comment by bambenek** [comment] 2016-07-30 17:46
We have had a weird issue that events seem to get unpublished after our daily imports. Will work to get that fixed.

**Comment by bambenek** [comment] 2016-07-30 17:49
Pull done. Any easy way to bulk publish all events?

**Comment by iglocska** [comment] 2016-07-30 19:33
I think the easiest in your case (unless you also want e-mail alerts / pushing them to other instances - which afaik you don't), the easiest is going via mysql:

`UPDATE `events` set published = 1;`

**Comment by bambenek** [comment] 2016-07-30 19:39
K will do shortly.

**Comment by iglocska** [comment] 2016-07-30 20:01
Perfect, let me know how it goes!

**Comment by elhoim** [comment] 2016-08-01 10:44
Globaly it seems you are fine from the MySQL instance.

```
[OK] Slow queries: 0% (43/95M)
[OK] Sorts requiring temporary tables: 0% (135 temp sorts / 17M sorts)
```

Virtually no slow queries or sorts requiring temp tables.

```
MyISAM
[OK] Read Key buffer hit rate: 100.0% (72M cached / 2K reads)
[OK] Write Key buffer hit rate: 99.8% (1M cached / 2K writes)
```

Most of the reads and writes are done via the buffers.

```
InnoDB
[!!] InnoDB Used buffer: 14.59% (152945 used/ 1048568 total)
[OK] InnoDB Read buffer efficiency: 100.00% (2792531142 hits/ 2792549610 total)
[!!] InnoDB Write Log efficiency: 86.71% (17564377 hits/ 20256671 total)
[OK] InnoDB log waits: 0.00% (0 waits / 2692294 writes)
```

Most of the read and writes done via buffers and plenty of bufferer left to go.

The recommendations given by MySQLtuner would not hurt to be implemented, but the MySQL side of things looks healthy from my point of view.

**Comment by rotanid** [comment] 2016-08-01 15:15
maybe we could try to use more indexes? "[!!] Joins performed without indexes: 2421364"
someone with an active installation would have to activate log_queries_not_using_indexes in MySQL and look at the log, which additional columns might need an index.
@bambenek could also check, if all the indexes from MYSQL.sql are in-place in his installation, maybe they didn't get applied with some update in the past that should have added them.

**Comment by bambenek** [comment] 2016-08-01 15:25
One of the reasons I store the data the way I do was the correlation just broke at about 10,000 samples (granted my dataset are highly related entries). Indices would have helped that problem (and a toggle to display related IDs or not in the UI).

**Comment by elhoim** [comment] 2016-08-03 10:44
@bambenek When you mention that it broke, do you mean long insert times or long lookup times or something else?

**Comment by bambenek** [comment] 2016-08-03 16:45
Long to non functional insert times

**Comment by bambenek** [comment] 2016-08-06 00:39
Seems better. Full cache jobs take a little less than an hour but cache_csv_all is dog slow. Been going 2 days.

**Comment by iglocska** [comment] 2016-08-06 05:23
Interesting, will look into it.

**Comment by cristianbell** [comment] 2016-08-07 17:15
@rotanid I did that a while ago, but reached ~2Gb of logs in a few days. (log_queries_not_using_indexes). 

The issue is that I couldn't see much to optimize at the db structure when the exports run on a larger data set.

**Comment by bambenek** [comment] 2016-08-13 04:15
FYI updated to latest version. Snort/suricata exports still hanging and see three php resque jobs grinding away on nothing on the server. The admin exports seemed to go quick enough. Going to try user exports next

**Comment by RichieB2B** [comment] 2016-08-16 12:16
Perhaps related to https://github.com/MISP/MISP/issues/1439

**Comment by iglocska** [comment] 2016-08-22 22:39
I've pushed a fix that will most likely fix the issues that you are having. What happened was that newer versions of MySQL (including the one that comes standard in Ubuntu 16.04) enforce the "only_full_group_by" policy which broke on a lookup query in some of the caches (snort, suricata, md5, sha1, sha256). 

I'll keep the issue open for now, let us know if the issue is resolved by this!

**Comment by bambenek** [comment] 2016-08-22 22:48
I will update tonight and let you know.

**Comment by bambenek** [comment] 2016-08-23 04:16
All the cache jobs from the admin account take a reasonable time. Cache snort and suricata seem to be hanging.

**Comment by rotanid** [comment] 2016-08-23 10:22
@iglocska maybe another issue, because you write about newer MySQL-versions and he hasn't got a newer one, as he is using ubuntu 14.04

**Comment by iglocska** [comment] 2016-08-23 10:41
Will look into snort and suricata, it is indeed weird. You are indeed correct, he is using 5.6.x so it shouldn't be the only_full_group_by issue.

**Comment by bambenek** [comment] 2016-08-23 14:34
The "user" exports are dog slow, been running at least 12 hours. Most
finished within 5 minutes when run as admin

**Comment by iglocska** [comment] 2016-08-23 15:19
Just having a look at your instance, this definitely seems really weird. Could you send me a copy of the following files?

/var/www/MISP/app/tmp/logs/error.log
/var/www/MISP/app/tmp/logs/debug.log
/var/www/MISP/app/tmp/logs/resque-worker-error.log
/var/www/MISP/app/tmp/logs/resque-2016-08-23.log

Just use the e-mail address from my profile, PGP key is this:

https://pgp.mit.edu/pks/lookup?op=get&search=0xBEA224F1FEF113AC

Sorry for the hassle!

**Closed as completed** 2016-08-29 19:10 UTC
Labels: T: bug, T: enhancement

**Comment by uiucseclab** [comment] 2016-08-30 02:19
Still doesn't appear fixed... generating them now and will give you updated info and send the logs.

**Comment by bambenek** [comment] 2016-08-30 02:21
Just upgraded to latest version, doesn't appear to be fixed... going to fully regenerate everything and send logs once I'm done.
