### ISSUE TITLE
The request has been black-holed

### ISSUE THREAD

**Issue by ndhambi** [MISP/MISP#4720] opened 2019-06-04 12:24 UTC
My MISP instance used to work fine but i now keep getting this error when i try to login via the web interface 
 "The request has been black-holed
Error: The requested address '/users/login' was not found on this server. " 

I have attached the error log below and cant seem to find what the cause is.

ERROR LOG
==============================================================

2019-06-04 12:18:11 Warning: Warning (2): session_start(): open(/var/lib/php/sessions/sess_i9pic0hds7etmm1i3uatk6qjd5, O_RDWR) failed: Permission denied (13) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 743]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_start - [internal], line ??
CakeSession::_startSession() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 743
CakeSession::start() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 219
CakeSession::check() - APP/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 248
AuthComponent::user() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 670
SysLogLogableBehavior::setup() - APP/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php, line 270
BehaviorCollection::load() - APP/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php, line 145
BehaviorCollection::init() - APP/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php, line 66
Model::__construct() - APP/Lib/cakephp/lib/Cake/Model/Model.php, line 781
AppModel::__construct() - APP/Model/AppModel.php, line 46
ReflectionClass::newInstance() - [internal], line ??
ClassRegistry::init() - APP/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php, line 169
Controller::loadModel() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 741
AppController::beforeFilter() - APP/Controller/AppController.php, line 123
UsersController::beforeFilter() - APP/Controller/UsersController.php, line 30
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-06-04 12:18:11 Error: [BadRequestException] The request has been black-holed
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('secure')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(UsersController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(UsersController), 'secure', Object(SecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): SecurityComponent->startup(Object(UsersController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2019-06-04 12:18:11 Warning: Warning (2): session_write_close() [<a href='http://php.net/function.session-write-close'>function.session-write-close</a>]: open(/var/lib/php/sessions/sess_i9pic0hds7etmm1i3uatk6qjd5, O_RDWR) failed: Permission denied (13) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal], line ??
[main] - [internal], line ??

2019-06-04 12:18:11 Warning: Warning (2): session_write_close() [<a href='http://php.net/function.session-write-close'>function.session-write-close</a>]: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in [Unknown, line 0]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
session_write_close - [internal]

**Comment by SteveClement** [comment] 2019-06-06 04:39
Well seems fairly obvious, by this:

```
2019-06-04 12:18:11 Warning: Warning (2): session_start(): open(/var/lib/php/sessions/sess_i9pic0hds7etmm1i3uatk6qjd5, O_RDWR) failed: Permission denied (13) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 743]
```

Fix the /var/lib/php/sessions permissions first so php can actually start a session.

**Comment by SteveClement** [comment] 2019-06-06 04:39
I am nearly sure you Run: RHEL/CentOS, have recently updated something.

**Comment by mpurzynski** [comment] 2019-06-06 15:47
This bug made MISP completely unusable for me (as our fetching logic depends on tags).

Adding a tag results with a "request has been blackholed" message


2019-06-06 15:42:23 Error: [BadRequestException] The request has been black-holed

Request URL: /attributes/addTag/4155516

Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(831): AppController->blackhole('auth')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(351): SecurityComponent->_callback(Object(AttributesController), 'blackHole', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/SecurityComponent.php(255): SecurityComponent->blackHole(Object(AttributesController), 'auth', Object(AuthSecurityException))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(AttributesController))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
^C

**Comment by RichieB2B** [comment] 2019-06-07 09:19
Your last remark sounds like #4406 which I can also still reproduce. Please discuss it further there.

**Comment by cbboggs** [comment] 2019-06-14 16:08
I ran into this blackhole on login issue - but it was due to a full disk.   We were running scheduled export generation, and I believe it was filling up /var/www/MISP/app/files/scripts/tmp with files and we either had waaay to many events, or it was not cleaning up after itself.

**Comment by vgiri-rms** [comment] 2019-12-16 16:43
@cbboggs   I am having the same issue.. What would be the best way to fix this issue ?

**Comment by diskurse** [comment] 2020-01-09 16:27
Same issue here in docker.

**Comment by marian-craciunescu** [comment] 2020-02-05 17:05
any ideas on how to solve this ?

**Comment by mokaddem** [comment] 2020-02-05 17:44
Hey guys,
1. I suppose your MISP is up to date?
2. Does it only occur when adding tags? Or do you see that behavior somewhere else?

Also keep in mind that CRSF token are used aggressively in MISP by default, meaning that if you fetch the token and spend to much time without using it, it will expire leading to a blackhole. The typical case would be if you spend to much time on the login page.

**Comment by marian-craciunescu** [comment] 2020-02-06 11:45
@mokaddem  i've tried with all the latest version and I've found out that with chrome none of them works.
You as a team have this bug from regarding blackhole for at least 2 months and it shows some kind of carelessness  that you weren't able to solve it.At least update your general documentation.

However using Mozilla v72 it worked  and version 3.0.1
Helps this will help other facing this issue.

**Comment by iglocska** [comment] 2020-02-07 09:17
2 months? Can you point out the issue that persists for that long? Since you are replying to an issue posted by someone else, I assume you have the same issue described by OP, which is a file read error when trying to access the session files:

```
 Warning: Warning (2): session_start(): open(/var/lib/php/sessions/sess_i9pic0hds7etmm1i3uatk6qjd5, O_RDWR) failed: Permission denied (13) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 743]
```

Or alternatively the issue described above by another, which was resolved by making space on the disk where the session data is solved. 

If it is neither of those, please open a new issue and describe what isn't working for you.

**Closed as completed by iglocska** 2020-02-07 09:17 UTC
Labels: T: support, blackhole

**Comment by marian-craciunescu** [comment] 2020-02-13 09:31
the issue in place is called `The request has been black-holed`
And as I've detailed already it's related to the browser used.
Hope it helps

**Comment by HoangKhuong129** [comment] 2020-12-31 07:29
I use the API to push data to MISP, but during the data push I cannot access the MISP homepage. I tried many ways, tested the server but it failed to fix it. I need help.

**Comment by ghost** [comment] 2020-12-31 07:29
I use the API to push data to MISP, but during the data push I cannot access the MISP homepage. I tried many ways, tested the server but it failed to fix it. I need help.
