### ISSUE TITLE
MISP Proxy doesn't work

### ISSUE THREAD

**Issue by young2112129** [MISP/MISP#4653] opened 2019-05-20 02:06 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Win10
| PHP version               | 7.2.17
| MISP version / git hash   | 2.4.107 (8a51109e2b2ad8bf372c34145d07571393a9bac7) 
| Browser                   | Chrome

### Expected behavior
Internet connection with proxy working

### Actual behavior
Internet connection with proxy not working

### Steps to reproduce the behavior
1. Set proxy in Administration->Server Settings & Maintenance->Proxy setting,
2. Then do the diagnostics and it shows OK, like below:
    **Proxy**
    This tool tests whether your HTTP proxy settings are correct.
    Proxy settings…OK
    (That means the proxy configuration is OK?)
3. fetch events
    (No events been fetched in my environment. That is the problem that I have)

### Comments
I have modified the proxy setting and the diagnostics shows OK.
But no events can be fetched through it.
I used tcpdump when fetch events and it shows that misp actually ignores the proxy.

Any suggestion? Thanks.

**Comment by SteveClement** [comment] 2019-05-20 09:51
Please try your proxy settings on the command line first to make sure your proxy works.
Also, please include the proxy settings here, you can obfuscate the details..

**Comment by young2112129** [comment] 2019-05-21 02:09
@SteveClement Thank you for your reply.
I have add the proxy settings to /etc/profile and use wget to try it. The result is it works.
I also use tcpdump to capture the packets and there's no packets been sent to proxy server that I set.
All the packets were sent to the feeds server directly.
It seems like that the proxy setting didn't works.

Should I modify some other configurations?
Is there any logs can use to check if the proxy setting right?

My proxy settings is here:
![proxy](https://user-images.githubusercontent.com/50349709/58063216-d6845200-7baf-11e9-9d40-2ac664302f33.png)

Here is the diagnostics:
![Diagnostics](https://user-images.githubusercontent.com/50349709/58063224-dd12c980-7baf-11e9-958e-2aacba8a7cd1.png)

tcpdump results:
![tcpdump](https://user-images.githubusercontent.com/50349709/58063364-75a94980-7bb0-11e9-8dde-c25c24f11f2b.png)

**Comment by SteveClement** [comment] 2019-05-21 06:41
Ok, thanks that is all we needed to see, I have a very limited setup at the moment and no means to test for proxy issues.
Perhaps @adulau or @iglocska @rommelfs have a better way to test proxy.

If you have not done so already, please also check the gitter chat, there are people who also use proxies in production.

**Comment by young2112129** [comment] 2019-05-22 01:53
@SteveClement Is there any further information? or who else should I asked for help?

**Comment by SteveClement** [comment] 2019-05-22 03:59
@young2112129 I mentioned some people in my reply.

you can try the gitter support: https://gitter.im/MISP/Support

I have not further information.

**Comment by rommelfs** [comment] 2019-05-22 05:58
Tested on 2.4.107, proxy is respected.

In your case I see you entered a schema into the host field. That's not correct.
Only the host is supposed to be in the host field.

I'm closing this issue. Feel free to re-open it if this is not the cause of your trouble.

**Closed as completed by rommelfs** 2019-05-22 05:58 UTC
Labels: T: potential bug, proxy

**Comment by SteveClement** [comment] 2019-05-22 06:13
This is a bug then. The input field should check for erroneous entries.

**Comment by young2112129** [comment] 2019-05-23 01:44
@rommelfs Thank you very much! Now it works.
I have one more question.
When I fetched feeds, there some "publish_alert_email " jobs like below:
![111](https://user-images.githubusercontent.com/50349709/58219907-30ffe880-7d3f-11e9-8db8-6aaa59b7cc13.png)
What does these jobs means?

**Comment by rommelfs** [comment] 2019-05-23 06:16
This is a totally unrelated question. 
I answer it here anyways.

If a new event is published on your MISP instance and mail notifications are enabled, MISP sends notifications to the users who have email notification enabled.
There is a worker handling this, and you'll see jobs in the job list.

Is that not described in the manual?

**Comment by deathscoming** [comment] 2020-05-14 14:32
> This is a totally unrelated question.
> I answer it here anyways.
> 
> If a new event is published on your MISP instance and mail notifications are enabled, MISP sends notifications to the users who have email notification enabled.
> There is a worker handling this, and you'll see jobs in the job list.
> 
> Is that not described in the manual?

Yes, it is

If you want to disable it, there is an option in MISP Settings Tab.

**Comment by dmolina213** [comment] 2020-05-15 01:52
I am fetching a feed using a PyMisp script. One of the function calla publish(event, alert=false). Alert is set to false.  Manual says email should not be sent. But email is sent. I want to suppress email alerts for feed pulls with multiple events as it becomes annoying spam
Sent from my IPhone
V/R
Help Me, Help You
Douglas P Molina, MBA, CISSP, C|EH, CySA+,CCSK,GCTI
U.S. Department of Veterans Affairs
Office of Information Security (OIS)
Cyber Threat Intelligence (CTI)
Work Phone: 708-938-2720
Mobile Phone: 202 779 2034
UNCLASS: douglas.molina@va.gov


________________________________
