### ISSUE TITLE
Make some tags local only

### ISSUE THREAD

**Issue by lfortemps** [MISP/MISP#7415] opened 2021-05-18 15:12 UTC
**Is your feature request related to a problem? Please describe.**
Some tags do not convey any meaning outside of our organization such as workflows and are purely meant to be used as local tags. However mistakes could be made and such a tag could be used as a global tag which will modify the timestamp and be synced externally(once published).

**Describe the solution you'd like**
An additional checkbox when creating/editing a tag: "local-only" which will prevent such a tag from being used as a global tag.

**Describe alternatives you've considered**
Using the tags as "non-exportable" but it breaks the automation which is using the API. "Hidden" tags is also not an option as regular users need to see it and use it to tag events/attributes.

**Additional context**
Any other way to achieve this with using current functionalities is welcome :)

**Comment by Wachizungu** [comment] 2023-05-30 12:32
Hi,

I believe this issue can be closed.
Duplicate of #7876 and already fixed.

**Closed as completed** 2023-05-30 18:47 UTC
Labels: T: enhancement, T: feature request, topic: local tags
