### ISSUE TITLE
Tag name can not display in List events page

### ISSUE THREAD

**Issue by Knoxpix** [MISP/MISP#4942] opened 2019-07-31 00:28 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.02 LTS
| OS version (client)       | macOS Mojave 10.14.5
| PHP version               | 7.3
| MISP version / git hash   | 2.4.111, 41a5597dd14b856a4964925ac84adb8a6bb2e8c0
| Browser                   | Firefox Quantum 68.0.1

### Expected behavior
Can display tag name in event list page

### Actual behavior
Tag name can not display normally

### Steps to reproduce the behavior
Login -> Event Actions -> List events

### Logs, screenshots, configuration dump, ...
![image](https://user-images.githubusercontent.com/5124273/62174563-a356ff80-b364-11e9-8507-252df81cadd4.png)

**Comment by iglocska** [comment] 2019-07-31 07:25
That is not a bug, but feature - you can control whether to show those "minimal" cards instead of tags or the actual tags in the server settings, just go to administration -> server settings -> MISP tab and change the `MISP.full_tags_on_event_index` setting to something other than minimal. This feature was broken for the past few weeks, that's why it "changed" over night, I basically pushed a fix to align the display with the setting.

**Closed as completed by iglocska** 2019-07-31 07:25 UTC
