### ISSUE TITLE
Hostname and domain correlation

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#603] opened 2015-08-19 10:22 UTC
Hi all, 

I was jsut wondering about the following:
If an attribute is google.com (type:domain) for X event and there is another event (say Y event) that has an the attribute www.google.com (type:hostname), are X and Y events related in MISP?

Cheers,
Andreas

**Comment by elhoim** [comment] 2015-08-19 11:48
No there is no cross-attribute or non-exact matches correlations between attributes.

This is a duplicate of details described in #117, but trying to track the generic idea under #480.

**Closed by elhoim** 2015-08-19 11:48 UTC
Labels: datamodel enhancement, functionality
