### ISSUE TITLE
Unpublish during pull doesn't work

### ISSUE THREAD

**Issue by zpevma** [MISP/MISP#7197] opened 2021-03-12 09:27 UTC
We have two MISP instances A and B. The sync is set to: "A pulls from B" with Unpublish event checkbox checked. After running pull, the pulled events on instance A are published.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |  Ubuntu both instances
| OS version (client)       |Ubuntu
| PHP version               | 7.2.24 instance A, 7.4.3 instance B
| MISP version / git hash   | 2.4.137 both instances
| Browser                   | Firefox

### Expected behavior
Events in instance A are not published.

### Actual behavior
Events in instance A are published.

### Steps to reproduce the behavior
Setting of server B on instance A:
![image](https://user-images.githubusercontent.com/14806666/110919697-d624f000-831c-11eb-895a-526fee4b074d.png)

After clicking on "Pull all", the synchronization is successful, but all events are published on instance A.

**Comment by Wachizungu** [comment] 2021-03-12 18:47
Just realized this is a duplicate of #7139.

**Comment by enjeck** [comment] 2021-03-14 12:41
Duplicate of #7139

**Closed as completed by enjeck** 2021-03-14 12:41 UTC
Labels: T: bug, R: duplicate
