### ISSUE TITLE
Export functions not working -- empty files

### ISSUE THREAD

**Issue by devnull-** [MISP/MISP#3740] opened 2018-10-05 09:15 UTC
Hello all,

"Download as" functions (to download attributes) are not working (except MISP XML and MISP Json formats [1]) in the Event view. All files are empty (only the header line is contained in the downloaded files).

This issue is initially reported via #3699.

Don't hesitate to contact me if you need some help and if you have some question.

devnull-

MISP version : 2.4.95 (commit: e7ae566c408907f3f7d82fe0bad2258227ed8b91)

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | all
| MISP version / git hash   | 2.4.95, e7ae566c408907f3f7d82fe0bad2258227ed8b91
| Browser                   | Chrome, Firefox, all

### Expected behavior

Download functions don't return empty files.

### Actual behavior

Downloaded files are empty (only the header line is contained in the downloaded files).

### Steps to reproduce the behavior

Click on a MISP event, and download the attributes in CSV, STIX, etc formats (click "Download as..." -> "XXX"). Check the downloaded files.

### Logs, screenshots, configuration dump, ...

Several errors/bugs: 
```
2018-10-05 10:42:56 Notice: Notice (8): Undefined variable: results in [/var/www/MISP/app/Model/Attribute.php, line 2981]

2018-10-05 10:42:56 Notice: Notice (8): Undefined variable: key in [/var/www/MISP/app/Model/Attribute.php, line 2979]
```

For example, variables `results` (https://github.com/MISP/MISP/blob/2.4/app/Model/Attribute.php#L2979) and `keys` (https://github.com/MISP/MISP/blob/2.4/app/Model/Attribute.php#L2977) are not initialized/defined.

[1]: The MISP XML and MISP Json results are displayed on the browser window instead of offer the possibility to save the file on the machine.

**Comment by adulau** [comment] 2018-10-10 13:15
Could you update to the latest version? and test? I was not able to reproduce it with the current version. Thank you.

**Comment by iglocska** [comment] 2018-10-10 14:06
Yeah this should be fixed in 96.

**Comment by devnull-** [comment] 2018-10-10 16:39
Thank you for your help and I confirm that the "Download as" functions work.

2 minor points:

- Could you change the generic filename when you select CSV format (`download .csv`) by something like `misp.event11541.csv`?
- The MISP XML and MISP Json results are displayed on the browser window instead of offer the possibility to save the file on the machine. May you change it ?

Have a nice afternoon and thank you for your messages and the fix.

**Comment by devnull-** [comment] 2018-10-16 11:24
Good afternoon @iglocska and @adulau 

> * Could you change the generic filename when you select CSV format (`download .csv`) by something like `misp.event11541.csv`?

I pushed a tiny patch #3768 to fix this point.

devnull-

**Closed as completed** 2019-04-15 04:41 UTC
Labels: T: support
