### ISSUE TITLE
launching example PyMISP give me the issue " Unverified HTTPS request is being made. Adding certificate verification is strongly advised"

### ISSUE THREAD

**Issue by santi10** [MISP/MISP#1989] opened 2017-02-24 13:16 UTC
Hi,

I've just received this message:

/usr/local/lib/python2.7/dist-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)

My keys.py is conifugured so:

`#!/usr/bin/env python

-- coding: utf-8 --

misp_url = 'https://misp.local/'
misp_key = 'api_key' # The MISP auth key can be found on the MISP web interface under the automation section
misp_verifycert = False`

When I set the script example, I had these message...

Do you known this fix????

Regards

**Comment by FloatingGhost** [comment] 2017-02-24 14:11
http://nopython2.uk/

Also, you've **disabled** SSL cert verification, so of *course* it's gonna warn you about an unverified SSL cert.

```python
misp_verifycert = False
```

Try changing that to
```python
misp_verifycert = True
```

**Comment by Rafiot** [comment] 2017-02-25 07:24
... and duplicate of https://github.com/CIRCL/PyMISP/issues/87

**Closed as completed by Rafiot** 2017-02-25 07:24 UTC

**Comment by santi10** [comment] 2017-02-27 09:03
Hi FloatingGhost

I've seen the same error, I changed to True and I don't get fix the error.

So I set "True" or "False" the message is same...do you know that I can do?

Thx!

**Comment by FloatingGhost** [comment] 2017-02-27 09:03
Try using a real python version

like 3 maybe.

That'll fix it.

**Comment by Rafiot** [comment] 2017-02-27 09:20
@santi10 you get a warning, not an error. If you have an error, please open an other issue with the error message.

**Comment by santi10** [comment] 2017-02-27 10:40
OK,,

Show you me new massage with python3

root@local:/var/www/MISP/PyMISP/examples# python3 get_network_activity.py --netflow --event 18
Traceback (most recent call last):
  File "get_network_activity.py", line 23, in <module>
    from pymisp import PyMISP
ImportError: No module named 'pymisp'

If I run with python only I don't see that message...what I can do, please?

Thx

**Comment by FloatingGhost** [comment] 2017-02-27 10:40
maybe install pyMISP

That might help a bit, y'know?

**Comment by Rafiot** [comment] 2017-02-27 10:42
`pip3 install pymisp` will make it.

**Comment by santi10** [comment] 2017-02-27 11:11
Yeah!!!! with pip3 install pymisp I've just fixed the issue!!!

Thanks to all!

**Comment by Rafiot** [comment] 2017-02-27 13:01
Excellent ;)
