### ISSUE TITLE
Bug: Plugin.ZeroMQ_audit_notifications_enable fails

### ISSUE THREAD

**Issue by dogmachine** [MISP/MISP#8093] opened 2022-01-14 03:01 UTC
### Expected behavior

Hi all.

Correctly configuring ZeroMQ plugin and enabling Plugin.ZeroMQ_audit_notifications_enable should result in audit log messages being sent to redis/zmq for pubsub consumption.

### Actual behavior

Audit log messages never make it to redis/zmq, JsonTool.php exits with a JsonException complaining about non-UTF8 characters.  "An internal error has occurred" is displayed in the browser.

I suspect this is because json_encode() is attempting to encode the client IP address which is in binary form.

Presumably this was introduced in this commit: https://github.com/MISP/MISP/commit/f1283996adf5aa9d43d569e3ad3b5084855e8115#diff-6ecc88df37e1480952215d0a596a6204ac0eaf1dd459ab89d4510a862d4d4792

https://github.com/MISP/MISP/blob/v2.4.152/app/Model/AuditLog.php#L183

### Steps to reproduce

- Correctly configure ZeroMQ plugin
- Enable Plugin.ZeroMQ_audit_notifications_enable
- Submit a new event via the standard "Add event" page
- You should now receive "An Internal Error Has Occurred."

### Version

2.4.152

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Chrome

### Browser version

Version 97.0.4692.71 (Official Build) (64-bit)

### Relevant log output

```shell
2022-01-14 01:03:22 Error: [JsonException] Malformed UTF-8 characters, possibly incorrectly encoded
Request URL: /events/add
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/JsonTool.php(19): json_encode()
#1 /var/www/MISP/app/Lib/Tools/PubSubTool.php(246): JsonTool::encode()
#2 /var/www/MISP/app/Lib/Tools/PubSubTool.php(166): PubSubTool->pushToRedis()
#3 /var/www/MISP/app/Model/AuditLog.php(236): PubSubTool->publish()
#4 /var/www/MISP/app/Model/AuditLog.php(217): AuditLog->logData()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): AuditLog->beforeSave()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1873): CakeEventManager->dispatch()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#8 /var/www/MISP/app/Model/AuditLog.php(324): Model->save()
#9 /var/www/MISP/app/Model/Behavior/AuditLogBehavior.php(207): AuditLog->insert()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(129): AuditLogBehavior->afterSave()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): ObjectCollection->trigger()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1970): CakeEventManager->dispatch()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#14 /var/www/MISP/app/Model/Event.php(3801): Model->save()
#15 /var/www/MISP/app/Controller/EventsController.php(2129): Event->_add()
#16 [internal function]: EventsController->add()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#18 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#19 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#20 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#21 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment] 2022-01-14 11:09
Hello @dogmachine ,
Thanks for the report and pinpointing the root cause, seems the error occurs when the client ip is ipv6.
Pushed a fix (https://github.com/MISP/MISP/pull/8096 ) and soon will be merged if all tests pass ok.

**Closed as completed** 2022-01-14 11:18 UTC
Labels: T: bug, confirmed, needs triage
