### ISSUE TITLE
Several notices when pulling updates in branch 2.4

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#776] opened 2015-12-21 12:33 UTC
Testing synchronisation (Synch actions -> List servers -> Pull updates only) against misppriv I see the following notices in the debug and error logs:

==> resque-worker-error.log <==
Notice Error: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]
Notice Error: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]
/var/www/MISP/app/tmp/logs/[10715]: 2015-12-21 13:22:08 Notice: ShadowAttribute "5.45.123.152" (12) added by User "SYSTEM" (0). -- to_ids () => (1), deleted () => (1), event_id () => (15), type () => (ip-dst), category () => (Network activity), uuid () => (553602ba-1c54-4ca4-9d72-4bd5950d210b), org () => (CIRCL), event_org () => (Swisscom), comment () => (C&C/fetcher), event_uuid () => (5530fba9-9f1c-4a84-9ddc-4908ac100567), proposal_to_delete () => (0), value1 () => (5.45.123.152)
Notice Error: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]
Notice Error: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]
/var/www/MISP/app/tmp/logs/[10715]: 2015-12-21 13:22:08 Notice: ShadowAttribute "199.201.121.169" (13) added by User "SYSTEM" (0). -- to_ids () => (1), deleted () => (1), event_id () => (15), type () => (ip-dst), category () => (Network activity), uuid () => (553602ba-0504-461f-ae4b-4bd5950d210b), org () => (CIRCL), event_org () => (Swisscom), comment () => (C&C/fetcher), event_uuid () => (5530fba9-9f1c-4a84-9ddc-4908ac100567), proposal_to_delete () => (0), value1 () => (199.201.121.169)
Notice Error: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]
Notice Error: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]
/var/www/MISP/app/tmp/logs/[10715]: 2015-12-21 13:22:08 Notice: ShadowAttribute "108.61.189.99" (14) added by User "SYSTEM" (0). -- to_ids () => (1), deleted () => (1), event_id () => (15), type () => (ip-dst), category () => (Network activity), uuid () => (553602ba-2888-4dbb-b6de-4bd5950d210b), org () => (CIRCL), event_org () => (Swisscom), comment () => (C&C/fetcher), event_uuid () => (5530fba9-9f1c-4a84-9ddc-4908ac100567), proposal_to_delete () => (0), value1 () => (108.61.189.99)
Notice Error: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]
Notice Error: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]
/var/www/MISP/app/tmp/logs/[10715]: 2015-12-21 13:22:08 Notice: ShadowAttribute "107.191.46.222" (15) added by User "SYSTEM" (0). -- to_ids () => (1), deleted () => (1), event_id () => (15), type () => (ip-dst), category () => (Network activity), uuid () => (553602ba-3370-4c4f-9fa1-4bd5950d210b), org () => (CIRCL), event_org () => (Swisscom), comment () => (C&C/fetcher), event_uuid () => (5530fba9-9f1c-4a84-9ddc-4908ac100567), proposal_to_delete () => (0), value1 () => (107.191.46.222)
Notice Error: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]
Notice Error: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]
/var/www/MISP/app/tmp/logs/[10715]: 2015-12-21 13:22:08 Notice: ShadowAttribute "95.126.99.8" (16) added by User "SYSTEM" (0). -- to_ids () => (1), deleted () => (1), event_id () => (15), type () => (ip-dst), category () => (Network activity), uuid () => (553602ba-4d30-4a4d-9528-4bd5950d210b), org () => (CIRCL), event_org () => (Swisscom), comment () => (C&C/fetcher), event_uuid () => (5530fba9-9f1c-4a84-9ddc-4908ac100567), proposal_to_delete () => (0), value1 () => (95.126.99.8)
Notice Error: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]
Notice Error: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]
/var/www/MISP/app/tmp/logs/[10715]: 2015-12-21 13:22:08 Notice: ShadowAttribute "64cb341c6d686aadeeaf0ef191d1cef7" (17) added by User "SYSTEM" (0). -- to_ids () => (1), deleted () => (1), event_id () => (15), type () => (md5), category () => (Payload delivery), uuid () => (5535fe69-e99c-409a-b1e5-359c950d210b), org () => (CIRCL), event_org () => (Swisscom), event_uuid () => (5530fba9-9f1c-4a84-9ddc-4908ac100567), proposal_to_delete () => (0), value1 () => (64cb341c6d686aadeeaf0ef191d1cef7)
Notice Error: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: Org in [/var/www/MISP/app/Model/Server.php, line 1028]
Notice Error: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> debug.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]

==> resque-worker-error.log <==
2015-12-21 13:22:08 Notice: Undefined index: EventOrg in [/var/www/MISP/app/Model/Server.php, line 1029]
/var/www/MISP/app/tmp/logs/[10715]: 2015-12-21 13:22:08 Notice: ShadowAttribute "f934a0a78c17bfe2b5fd4c0fa71eeab6" (18) added by User "SYSTEM" (0). -- to_ids () => (1), deleted () => (1), event_id () => (15), type () => (md5), category () => (Payload delivery), uuid () => (5535fe34-e678-4907-8ed5-3a61950d210b), org () => (CIRCL), event_org () => (Swisscom), event_uuid () => (5530fba9-9f1c-4a84-9ddc-4908ac100567), proposal_to_delete () => (0), value1 () => (f934a0a78c17bfe2b5fd4c0fa71eeab6)

The job completely successfully, but there are no new events in my instance.

**Comment by iglocska** [comment] 2015-12-21 12:48
Weird, looking into it!

**Comment by iglocska** [comment] 2015-12-21 12:50
Just one quick thing: Update only will not pull any new events, it will only update existing ones. 

The idea is that you might want to just manually pick a subset of the events (with the preview tool), and download those to your instance. You can later on upgrade these without pulling anything unwanted.

**Comment by h122015** [comment] 2015-12-21 12:55
Ah OK. I used the preview tool and downloaded only one event to my instance, that worked fine. But now, how about if I want to download the events from today to my instance? If I do a pull all I guess I'll get all the events in misppriv right?

**Comment by iglocska** [comment] 2015-12-21 12:58
There is no functionality to only download stuff based on time, but that is a cool idea. Let's keep this ticket open until that is implemented.

**Comment by adulau** [comment] 2018-01-18 14:08
@h122015 could you review with a recent version of MISP? I'll close the issue but feel free to reopen if the issue is still there.

**Closed by adulau** 2018-01-18 14:08 UTC
Labels: automation, enhancement, functionality

**Comment by h122015** [comment] 2018-01-18 15:13
@adulau I don't have the issue anymore. Has the functionality to only download based on time been implemented?
