### ISSUE TITLE
STIX (v1) export via API not working

### ISSUE THREAD

**Issue by mohlcyber** [MISP/MISP#3657] opened 2018-09-10 09:46 UTC
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04
| PHP version               | 7.2.7
| MISP version / git hash   | 2.4.95

I am trying to download STIX (v1 - xml) via the API using the following url:
```<mispurl>/events/stix/download/<eventid>```

I am receiving an internal error has occurred (HTTP - 500).
This download procedure worked with 2.4.93 perfectly.

Please find the log below:
```
2018-09-10 09:27:32 Error: [Exception] There was an issue generating the STIX export.
Request URL: /events/stix/download/855
Stack Trace:
#0 [internal function]: EventsController->stix('download', '855')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

If I am trying to download STIX (v2 - json) via the API it works successfully:
```<mispurl>/events/stix2/download/<eventid>```

**Comment by rommelfs** [comment] 2018-09-10 11:37
via web: /events/stix/download/ -> empty stix doc
via web: /events/stix2/download/ -> valid doc

**Comment by adulau** [comment] 2018-09-10 11:59
@chrisr3d Could you have a look?

**Comment by chrisr3d** [comment] 2018-09-10 12:40
[a3f83fa](https://github.com/MISP/MISP/commit/a3f83fac63521673f73c57a764d5d3d86e538e9e) should have fixed the issue
Let us know if anything is going wrong

**Comment by mohlcyber** [comment] 2018-09-10 15:00
Thanks Guys for the quick response. 

@chrisr3d i added line 2456, 2457 and 2458. 
Still couldn't download, however i got a new error message in /var/www/MISP/app/tmp/logs/exec-errors.log:

```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/misp2stix_framing.py", line 4, in <module>
    from stix.core import STIXPackage, STIXHeader
  File "/usr/local/lib/python3.6/dist-packages/stix-1.2.0.6-py3.6.egg/stix/__init__.py", line 5, in <module>
  File "/usr/local/lib/python3.6/dist-packages/stix-1.2.0.6-py3.6.egg/stix/base.py", line 19, in <module>
  File "/usr/local/lib/python3.6/dist-packages/stix-1.2.0.6-py3.6.egg/stix/utils/__init__.py", line 383, in <module>
  File "/usr/local/lib/python3.6/dist-packages/stix-1.2.0.6-py3.6.egg/stix/utils/walk.py", line 8, in <module>
ModuleNotFoundError: No module named 'cybox'
``` 

i just run:
```
pip3 install cybox
```

this fixed the issue. 
Again thanks so much Guys for you support.

**Comment by chrisr3d** [comment] 2018-09-11 14:16
Indeed, this library should be installed by default on the new VMs we generate

**Comment by adulau** [comment] 2018-09-16 18:43
@chrisr3d VMs are installed by default with cybox. I tried with a recent VM and cannot reproduce the issue. (Maybe it was fixed in the mean time?) I'll close the issue except if we have to dig further ;-)

**Closed as completed by adulau** 2018-09-16 18:43 UTC
Labels: T: bug, confirmed
