### ISSUE TITLE
Duplicated event attributes

### ISSUE THREAD

**Issue by sustefil** [MISP/MISP#6034] opened 2020-06-19 13:45 UTC
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.126

### Expected behavior
No attribute duplicates in one event at all.

### Actual behavior
Duplicated attributes of network-activity types (domain, ip-src, ..). This bug then spawns another bugs, such as inability to tag these attributes (through pymisp event_udpate), we have also found sync issues (these events are not pushed)

### Steps to reproduce the behavior
Well, hard to say. My guess would be that we use concurrent PyMISP access to the MISP instance (3 load balanced IntelMQ output bots). And these bots can access the same events. When they want to add the very same attribute concurrently, it somehow slips the validation.

Can MISP handle such concurrency? Or shall we serialize the PyMISP calls?

### Logs, screenshots, configuration dump, ...

![image](https://user-images.githubusercontent.com/32512488/85138584-4fd2f600-b243-11ea-8923-29864e6bd21e.png)

I can try digging some logs if needed.

Thanks in advance

**Comment by mokaddem** [comment] 2020-07-17 14:27
Hello,

What view are you showing with the screenshot? Is it `/attributes/search/`?
It seems that you don't actually have duplicated attributes but rather they are somehow fetched twice. Could you please confirm?

Also, do you have any logs regarding your sync issues?

Thanks in advance!

**Comment by sustefil** [comment] 2020-07-20 09:12
Hi @mokaddem,

This is /events/view/<number>, so it's one particular event. 

We are strongly confident that it is caused by concurrent PyMISP accesses (calling misp.update on the same event and attribute in the same time). The uniqueness of the attribute in an event is not enforced by the database schema, so it would really make sense to me that the REST API calls just don't handle concurrency, what do you think?

We even deployed an attribute deduplicator module to delete these duplicates regularly (database select to find them and REST query to delete them).

This is an example SQL query that the deduplicator uses for deletion:
```
MariaDB [misp]> select GROUP_CONCAT(attributes.id SEPARATOR ", "),category,type,count(*),value1,value2,event_id,events.info,events.published from attributes join events on attributes.event_id=events.id where type in ("ip-src", "ip-dst", "domain", "domain|ip", "ip-src|port", "ip-dst|port") and events.timestamp > 1593594255  group by category,type,value1,value2,event_id having count(*) > 1;
+--------------------------------------------+------------------+--------+----------+----------------+--------+----------+-------------------------------------------+-----------+
| GROUP_CONCAT(attributes.id SEPARATOR ", ") | category         | type   | count(*) | value1         | value2 | event_id | info                                      | published |
+--------------------------------------------+------------------+--------+----------+----------------+--------+----------+-------------------------------------------+-----------+
| 16009833, 16009834                         | Network activity | ip-src |        2 | 185.132.53.115 |        |  1209074 | URLHaus Report - Gandylyan1 - 2020-06-24  |         1 |
| 16010885, 16010886                         | Network activity | ip-src |        2 | 45.95.168.194  |        |  1209125 | URLHaus Report - zbetcheckin - 2020-06-24 |         1 |
+--------------------------------------------+------------------+--------+----------+----------------+--------+----------+-------------------------------------------+-----------+
2 rows in set (23.30 sec)

MariaDB [misp]> 

```

This is a screenshot of /events/view/1209074:

![image](https://user-images.githubusercontent.com/32512488/87920512-9baed000-ca79-11ea-958d-29cbfeef1136.png)

Let's not focus on the sync issues, since that is only a symptom of the attribute duplication.

Thanks in advance for help.

**Comment by JakubOnderka** [comment] 2020-07-20 13:25
The problem is missing lock for attribute table. So if you add attribute from multiple processes. For example:

Process A checks if attribute is unique
Process B checks if attribute is unique
Process A add attribute
Process B add attribute

So the solution is to add write lock for attribute table before checking for unique values and unlock after attribute is added.

**Comment by mokaddem** [comment] 2020-07-21 09:20
@JakubOnderka explained it clearly. However, adding a lock for the table would add (once again) a non-negligible delay that we are not really willing to introduce.
The situation would be totally different if the IDs or UUIDs would be duplicated but fortunately, it is not the case. You are nearly in the same situation that you can be when using objects (duplication is allowed).
@sustefil if you could modify your setup to use the `batch import` mode when adding attributes, it would speed up the insertion process and will not create the duplication you are experiencing.

I'm closing the issue as a wont-fix, but the discussion is obviously open and clever suggestions are welcome.

**Closed as completed by mokaddem** 2020-07-21 09:20 UTC
Labels: T: potential bug, R: wontfix

**Comment by github-germ** [comment] 2020-07-21 13:10
> @sustefil if you could modify your setup to use the `batch import` mode when adding attributes, it would speed up the insertion process and will not create the duplication you are experiencing.

@mokaddem -- Hi, can you offer more details about `batch import` mode please. Thanks.

**Comment by mokaddem** [comment] 2020-07-22 13:42
@github-germ 
`Batch Import` allows you to create multiple attributes at once.
One value will be created per line.
See the example on the picture below
![image](https://user-images.githubusercontent.com/6977223/88183481-ce032d80-cc31-11ea-8082-7684f6bf1246.png)

**Comment by github-germ** [comment] 2020-07-22 14:03
> `Batch Import` allows you to create multiple attributes at once.

Appreciate the reply. OK, I thought there was something new to me via PyMISP since this was the context of this discussion.

**Comment by sustefil** [comment] 2020-07-23 08:34
@mokaddem Ok, understood.

Just to mention here, we have observed that these duplicated attributes spawn more errors, namely:

1) Adding a tag with PyMISP to these attributes fails silently

2) Duplication of UUID. The same attributes have the same UUID after push.
Let's say you have instances A, B and C. Push is configured A -> B -> C. There are 2 duplicated attributes (with different ID and UUID) on A, but in B (after push) the very same attributes have the very same UUID. Push B -> C then get errors for this event because of the same UUID.

I see these are only symptoms of the duplicated attributes, so I don't expect you would fix them. Anyway, at least good to know.

Thanks

**Comment by mokaddem** [comment] 2020-07-27 08:18
@sustefil The point you mentioned is concerning as the **B** instance should not have 2 attributes with the same UUID. Moreover, **C** should not get any errors.

I tried to reproduce the issue you had (with commit 46eb547). This is what I did:
1. Created 2 attributes via the API on **A**
    - As I couldn't reproduce the duplication, I manually edited the DB to have 2 identical attributes (unless the `ID` and `UUID`)
2. I managed to attach tags via the API using the `/tags/attachTagToObject` endpoint
3. I published the event on **A**, which then was subsequently propagated to **B** and **C** 
    - **A** -> **B** -> **C**
4. As expected, only the first duplicated attribute is present on **B** (the save of the second is ignored due to the duplication)
5. The sync on **C** is correct and mirrors the event on **B**

Would you mind describing what is failing with PyMISP (code or function call would help)?
But more importantly, could you elaborate on the procedure to reproduce the faulty behavior (or correct mine)? Providing a sample of the event would also help in case I missed something.

Thanks a lot!

**Comment by sustefil** [comment] 2020-07-28 14:38
@mokaddem Thanks for the effort! 

I am currently on a 2-week holiday, I will get back to this later.
