### ISSUE TITLE
Import from MISP export does not update existing events

### ISSUE THREAD

**Issue by SOCDev80** [MISP/MISP#3533] opened 2018-08-07 10:51 UTC
Per a previous request (https://github.com/MISP/MISP/issues/890) - would it be possible to add the functionality for MISP to identify when importing events where an event already exists but is different and therefore update the event accordingly?

At the moment when trying to update events via a separate MISP export.json, MISP will identify existing events but not update them if there are changes - it will just take no action.

**Comment by SteveClement** [comment] 2018-08-15 09:15
Duplicate of #890 
@SOCDev80 please use the initial issue.

**Closed as completed by SteveClement** 2018-08-15 09:15 UTC
