### ISSUE TITLE
Sync broken?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#3364] opened 2018-06-21 10:12 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | -
| PHP version               | 7.1...
| MISP version / git hash   | 2.4.92
| Browser                   | -

### Expected behavior
For a few days, a MISP instance cannot pull new events from a remote instance

### Actual behavior
Log entry: 
0 events and 0 proposal pulled or updated. 474 events failed or don't need an update

### Steps to reproduce the behavior
-

### Logs, screenshots, configuration dump, ...
-
Connection with the remote instance is ok, workers are ok, no error in logs.

**Comment by adulau** [comment] 2018-06-21 12:24
@xme If you pull the CIRCL OSINT feed, does it work? Is the time of the instance properly set?

**Comment by xme** [comment] 2018-06-21 13:06
System time is ok but I can't try a feed because the MISP instance is not online.

**Comment by iglocska** [comment] 2018-06-21 13:20
Git pull please it was fixed yesterday ;)

**Comment by adulau** [comment] 2018-06-21 13:24
@xme if you can test the latest HEAD, if you were running on HEAD ;-)

**Comment by xme** [comment] 2018-06-21 13:40
What did change? The MISP instance is already based on yesterday's code (rebuilt a docker image)

**Comment by iglocska** [comment] 2018-06-21 13:41
Which instance are you pulling from? The problem is that the bug was on the /events/view/[id].json part so the remote needs to update ;)

**Comment by xme** [comment] 2018-06-21 13:43
Ok, I'll suggest this to CERT.eu then ;-)
Their instance is also 2.4.92

**Comment by iglocska** [comment] 2018-06-21 13:43
yep, 2.4.92 was affected for 2 days, if they update it will be fixed :)

**Closed as completed** 2020-11-30 05:49 UTC
Labels: T: support, topic: sync, R: fixed
