### ISSUE TITLE
Sync deleted attributes

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#698] opened 2015-10-27 16:09 UTC
Sync deleted attributes so that deletion propagates.
This would be useful for cases where false positives are detected and removed by content producers.

**Comment by elhoim** [comment] 2015-10-27 16:12
After a quick chat, the best way to do it would be to store in a separate table the list of attributes that have been deleted. This table would contain attribute uuid and even uuid, to know which attribute in which event has been deleted.
In the data set of the event sent for sync, an additional tag with something like <deleted_attributes><uuid>1-2-3-4</uuid><uuid>5-6-7-8</uuid></deleted_attributes> to send?
Unknown tags are ignored, so this should be backward compatible.

**Comment by Rafiot** [comment] 2016-03-29 14:31
Duplicate of #659, closing.

**Closed by Rafiot** 2016-03-29 14:31 UTC
Labels: automation, datamodel enhancement
