### ISSUE TITLE
User with Tagger-Permission can add, but not remove local Tags in external Events

### ISSUE THREAD

**Issue by marjatech** [MISP/MISP#7099] opened 2021-02-26 07:25 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Win10, Ubuntu
| PHP version               | 7.4
| MISP version / git hash   |  v2.4.139 (6fd2c4807abc2232b90d00fd290b0020db83fcaa) 
| Browser                   | Firefox

### Expected behavior
If the user is able to add a local Tag to an event, it would be expected he will be able to remove it again too.

### Actual behavior
The Tagger ist not allowed to remove local Tags on events created by external orgs.

### Steps to reproduce the behavior
- add a local tag to an event created by an external org 
- try to remove it as non-SiteAdmin

### Logs, screenshots, configuration dump, ...

**Comment by mokaddem** [comment] 2021-03-23 15:52
Hey,
I tried to reproduce your issue but everything is working as intended.
Would you mind explaining more in depth what are the roles and configuration of the instance?
I tried the following:
- As a standard user (**part** of the `MISP.host_org_id` org) with `perm_tagger`, I could attach and detach local tags from attributes belonging to an event that I own, regardless if I'm the creator or not
- As a standard user (**not part** of the `MISP.host_org_id` org) with `perm_tagger`, I could attach and detach local tags from attributes belonging to an event that I own, regardless if I'm the creator or not
Thanks for your help!

**Comment by marjatech** [comment] 2021-03-23 15:58
Hi,

you're right, this seems to work on attribute level, but it doesn't for local Tags on the event.

**Comment by mokaddem** [comment] 2021-03-24 10:06
Hey,
Thanks for the feedback, I pushed a fixed (41099defb240f30c2a6c23ec65ee50837fd91b50) on the dev branch that should solve the issue.
Let us know if you notice more inconsistencies!

**Closed as completed** 2021-10-11 13:18 UTC
Labels: T: potential bug, topic: tagging, topic: local tags
