### ISSUE TITLE
When adding elements to template, displays error but it really adds the element

### ISSUE THREAD

**Issue by orbital-github-user** [MISP/MISP#2388] opened 2017-08-10 07:55 UTC
Hello, here using MISP 2.4.78 with the latest commit,

two different cases:

When adding an Attribute or File element to a template and press Submit, I get "The object(s) could not be saved. Please, try again." error message.

![adding error2](https://user-images.githubusercontent.com/30801261/29160224-b76b85da-7db1-11e7-8f82-1fff9d4cb760.png)

![add file element](https://user-images.githubusercontent.com/30801261/29160227-b9e8f270-7db1-11e7-80d1-e42eeb0f02b8.png)

When adding a Text element to a template and press Submit, the dialog disappears instantly and appears again, displaying no message.

![adding](https://user-images.githubusercontent.com/30801261/29160283-f28bc6ac-7db1-11e7-804f-d3dac34ad9a7.png)
![adding2](https://user-images.githubusercontent.com/30801261/29160289-f468bc8c-7db1-11e7-977d-100ade69fdab.png)
![adding](https://user-images.githubusercontent.com/30801261/29160290-f6114414-7db1-11e7-9a31-df7c4201643d.png)

In both cases after closing the Add dialog, the template apparently remains equal as before, but when going to "View Template", the template appears filled with all the elements I added!

![final template](https://user-images.githubusercontent.com/30801261/29160252-cad95dea-7db1-11e7-9966-cccd92eabafb.PNG)

**Comment by iglocska** [comment] 2017-08-10 08:40
Woah, thanks for the detailed bug report. Indeed, this was caused by a recent change to how we handle JSON responses and some mistakes in that patch, should be fixed now! Let me know if it's still broken!

**Closed as completed** 2017-08-10 08:40 UTC
