### ISSUE TITLE
REST interface can't add an event when using json format

### ISSUE THREAD

**Issue by otmarlendl** [MISP/MISP#454] opened 2015-04-10 14:19 UTC
We just spent significant time debugging our PyMISP scripts that should import/edit events. We then switched to doing manual queries with curl to nail this down.

It seems to be that in EventsController.php / new() the variable $this->request->data will never receive data from the POST request.

The search function works with json, and there is a line
                                $data = $this->request->input('json_decode', true);
in restSearch() which seems to fetch the data and parse it. I could not find where an equivalent operation should take place for the add() case.

Can someone comment on the state of the REST/JSON API? 
Is this usable at all? Or should we switch to using XML?

**Comment by iglocska** [comment] 2015-04-10 15:00
I just tried POSTing a JSON event to the REST API and it seems to work as intended. 

What I did exactly:

POST url:
http://192.168.56.102/events (my local dev instance)

Headers: 
Authorization: <Auth key>
Accept: application/json

Body:
{"Event":{"date":"2015-04-10","threat_level_id":"1","info":"test event","analysis":"0","distribution":"0","orgc":"Iglocska", "Attribute": [{"type":"comment","category":"Other","to_ids":false,"distribution":"3","value":"test value"}]}}

This created an event with an attribute as expected. Could you show me a sample JSON that you tried to push? Also, did you specify the right headers?

**Comment by aaronkaplan** [comment] 2015-04-10 15:19
On Apr 10, 2015, at 5:00 PM, Andras Iklody <notifications@github.com> wrote:

> I just tried POSTing a JSON event to the REST API and it seems to work as intended.
> 

Just cross checking: are we comparing the same versions of MISP (stable and stable)?

**Comment by iglocska** [comment] 2015-04-10 15:22
2.3.59 from Master here

**Comment by didelphodon** [comment] 2015-04-13 14:19
we have 2.3.0 here

**Comment by iglocska** [comment] 2015-04-13 14:33
Are you sure? The footer takes the footer text from the settings that have to be manually edited (it's kind of silly, I'll update this now that I am reminded of it soon...) - make sure you check the version you are on in the server settings.

As a site admin, go to administration -> server settings -> Diagnostics. It should show you your patch version and the latest available version out there.
![version](https://cloud.githubusercontent.com/assets/3668672/7117709/ddfa3840-e1fa-11e4-8c57-15fadd9d4cd5.PNG)

**Comment by didelphodon** [comment] 2015-04-13 14:54
2.3 hotfix 44

**Comment by iglocska** [comment] 2015-04-13 15:00
Try to update your instance and see if that fixes the issue.

Also, could you give an example of something that you are trying to POST to MISP that fails that you could share? I'll try to reproduce the issue on my end then.

**Comment by didelphodon** [comment] 2015-04-13 15:04
{
  "Event": {
    "date": "2012-04-12",
    "threat_level_id": "4",
    "info": "info",
    "distribution": "0",
    "analysis": "0",
    "timestamp": "1",
    "Attribute": [
      {
        "type": "ip-dst",
        "category": "Network activity",
        "to_ids": "1",
        "distribution": "0",
        "value": "1.1.1.1",
        "timestamp": "0"
      }
]
  }
}

**Comment by iglocska** [comment] 2015-04-13 15:27
OK, I see what's going on, add this header in addition, I just tried it again and had the same error, it worked after adding the following header: 

Content-Type: application/json

**Comment by didelphodon** [comment] 2015-04-14 08:29
Hm, that really seems to be the solution for this. Actually we are using PyMISP for the DB communications and it was PyMISP which already had those "Invalid event." issue in the beginning, it's our quest to nail down the problem which brought us here. Gotta check out if PyMISP does it also wrong that way, if so I will open up a ticket there.
Thx a lot.

**Comment by didelphodon** [comment] 2015-04-14 10:14
So, while I'm now capable of adding events I'm still having problems with updates, with some new taste, though.
Though my update receives a 200 return code it gets "message":"Error" as a content. I just tried to change the "info" of an event and changed the "timestamp" value accordingly as I had to (the latter I learned from a response of the API).
Any ideas with this one?

**Comment by iglocska** [comment] 2015-04-14 11:54
I've just tested it and it seems to work ok. What I did: 

I first posted an event to http://mymisp/events (tried both xml and json). 

I got a response with the actual created event.

I took the created event from the response, used it as my new request body, edited the timestamp to 1 higher than the old value and changed the info field. I posted this to http://mymisp/events and got a response telling me that the event already exists and I should edit it using the address given in the location header. 

I posted it again to the address specified there and the event correctly saved. 

Could you try to repeat the steps that I took and see if it still fails? I've also updated the REST api on the attribute level with a patch just not, so before you start using that part, make sure you pull :)

**Comment by didelphodon** [comment] 2015-04-14 12:25
will try ...

**Comment by didelphodon** [comment] 2015-04-14 13:32
we need to switch to dev-tree before ... to be continued

**Comment by iglocska** [comment] 2015-04-14 13:50
Sure, let me know if there's anything that I can help with!

**Comment by didelphodon** [comment] 2015-04-14 13:57
seems we're having problems in switching - can't get dev-tree working ;-(

**Comment by didelphodon** [comment] 2015-04-14 14:03
we tried to effectively *switch* from stable to dev to keep our db-data. since the switch the web-frontend doesn't appear due to APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 120

sorry for the unclear informations on that, aaron is abroad and I'm trying to follow his actions via Skype, etc. remotely

**Comment by aaronkaplan** [comment] 2015-04-14 14:04
okay, so here is what's happening when switching to the develop branch:
app/Lib/cakephp seems to break apart

@iglocska : what's in your opinion the best way to switch a running MISP system to the develop branch?
Nuke it and start new?

**Comment by iglocska** [comment] 2015-04-14 14:29
That definitely sounds weird, switching to develop should cause no issues
at all - the two are nearly identical at the moment... There should be no
need to start new.

Just try the following:

cd /var/www/MISP/app/Lib/cakephp
git checkout origin/2.6
git pull origin 2.6

Does this fix it for you?

**Comment by iglocska** [comment] 2015-04-14 14:34
OK, if it doesn't there is the nuclear option:

cd /var/www/MISP/app/Lib/cakephp
git fetch origin 
git reset --hard origin/2.6

**Comment by iglocska** [comment] 2015-04-14 14:35
The issue is that cakephp 3.0 has come out of beta, and they moved the old master (which MISP uses) to the 2.6 branch. You must have ended up with 3.0 which breaks everything. The above will simply force reset you to 2.6.

**Comment by didelphodon** [comment] 2015-04-14 15:31
I'll leave this to Aaron as that's far beyond from what I feel comfortable with in terms of my MISP installation knowlegde which is actually zero ... @aaronkaplan, can you help me out on that?

**Comment by didelphodon** [comment] 2015-04-21 12:05
News: We managed to switched (and patched) our test instance to development branch and now the update of events works as expected. What ever the problem was, it seems to be fixed now :-)
Thx a lot!

**Comment by iglocska** [comment] 2015-04-21 12:33
Excellent news! :) Glad it all worked out.

**Comment by didelphodon** [comment] 2015-04-28 11:40
Some new problem ... don't know if it's worth a new issue so I'll keep it in here, initially.
Everything seems to work fine so far, however, when I try to update an existing event by adding 74 attributes (as in my test-case) it only adds some of them - let's say 40. When I retry the same update request it adds another 20 of them ... Everytime I try this test-case I need 3 to 4 cycles to finally have all of the attributes added.
Any ideas on this phenomenon?

**Comment by didelphodon** [comment] 2015-04-28 15:04
Found the solution ...

Our Apache config gives each request 30 secs to finish and it kills the request if it takes longer. We played with the actual value in the Apache config and were able to get the request going successfully. However, this issue actually reveals something that should be prevented beforehand. What I'm talking about is the fact that the update-request was finished partially in my previous tries with 30 secs. Shouldn't the actual SQL statements in the backend be bound together using transactions? For me using PyMISP as a MISP-API wrapper the request seemed to have finished successfully which was actually not true.

About the time the request took: I always work with the same test-data so there are multiple redundancies in the database - I guess the major amount of time was used for the correlation of the attributes between those multiple events. However, I will check this with new attributes which should  result in massively reduced execution-time if my guess is right.

**Comment by didelphodon** [comment] 2015-04-28 15:11
My guess was right - it has been those correlations that took so long. For the sake of completeness, the previous request took between 1 and 2 minutes to finish - now it only took about 10 seconds, which is still a lot imho.

**Comment by elhoim** [comment] 2015-05-08 07:41
Should a ticket for speeding up correlations be opened?

**Comment by Rafiot** [comment] 2015-09-15 15:09
Original bug fixed, follow up on #481

**Closed by Rafiot** 2015-09-15 15:09 UTC
Labels: potential-bug
