### ISSUE TITLE
Support: MISP Sharing Events

### ISSUE THREAD

**Issue by linozinho** [MISP/MISP#9760] opened 2024-05-31 15:08 UTC
### Support Questions

When sharing an event, is it possible to select more than one sharing group? If yes, how can I do it?

### MISP version

v2.4.192

### Operating System

Ubuntu

### Operating System version

Ubuntu 22.04.4 LTS

### PHP version

PHP 7.4.33 

### Browser

Chrome

### Extra attachments

![Screenshot from 2024-05-31 14-54-46](https://github.com/MISP/MISP/assets/93954491/c3e26a83-c8aa-4312-a7e0-11be9f095ffc)

![Screenshot from 2024-05-31 14-54-46](https://github.com/MISP/MISP/assets/93954491/1ab4ae2f-d14e-4d30-b71f-ea4e537c307f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment] 2024-06-05 12:21
Duplicate of #9763.

**Closed as completed by iglocska** 2024-06-05 12:21 UTC
Labels: needs triage, support
