### ISSUE TITLE
Wrong JSON output when /events/index returns empty result

### ISSUE THREAD

**Issue by obert01** [MISP/MISP#4690] opened 2019-05-29 13:50 UTC
### Work environment
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| MISP version / git hash   | v2.4.107 (6a09fca7653c10b90117d27de92c238721063b64) 

### Expected behavior
When there is no result, MISP should return a valid JSON string indicating no result, like:
```
[]
```

### Actual behavior
MISP returns:
```
Array
```

### Steps to reproduce the behavior
Perform a request like the following one, ensuring there will be no result:
```
curl -o - --header "Authorization: XXXXX" --header "Accept: application/json" --header "Content-Type: application/json"  \
-d '{"eventinfo":"qsdmklfjqsdmklfj"}' \
https://misp-backend.cert-ist.com/events/index
```

**Comment by obert01** [comment] 2019-05-29 14:07
This issue is rather critical for us at Cert-IST, since we use the OTX_MISP python script, which does not work anymore due to this problem. Actually  PyMISP generate an exception, stating that the JSON output is not valid. 

I have tried to figure out how to fix that in MISP, with no luck.

**Comment by TheDr1ver** [comment] 2019-05-29 14:31
Seconded. I noticed it today when OTX_MISP stopped working, but also traced it back to a PyMISP error being thrown [here](https://github.com/MISP/PyMISP/blob/efed0033022e43ee0ce0a98643a3bb79b492646f/pymisp/api.py#L250) as best as I can tell. 

I've been crawling through the recent changes made to /app/Controller/EventsController.php to see if I can pinpoint what change may have resulted in it returning 'Array' instead of a valid JSON response, but haven't found anything yet. (To be fair, I'm not sure that EventsController is even the right place I should be looking)

**Comment by TheDr1ver** [comment] 2019-05-29 17:07
I still can't seem to figure out where the issue is. Here are some additional logs from a single PyMISP request that might help (though the same issue is already captured in the curl example listed above):

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymisp import PyMISP
>>> misp_url = 'https://<misp_server>/'
>>> misp_key = '<api_key>'
>>> misp = PyMISP(misp_url, misp_key, ssl=False, out_type='json')
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
>>> misp.search_index(eventinfo="asdfasdf")
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 242, in _check_response
    json_response = response.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 1144, in search_index
    res = self._check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 250, in _check_response
    raise PyMISPError(everything_broken.format(response.request.headers, response.request.body, response.text))
pymisp.exceptions.PyMISPError: Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.106 - Python 3.6.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '25', 'Authorization': '<api_key>', 'content-type': 'application/json'}
Request body:
{"eventinfo": "asdfasdf"}
Response (if any):
Array
>>>

```

**Comment by TheDr1ver** [comment] 2019-05-29 19:11
I noticed I get a similar 'Array' response when attempting to search the index for an attribute that doesn't exist:

```
>>> misp.search_index(attribute="asdfasdf")
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 242, in _check_response
    json_response = response.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 1144, in search_index
    res = self._check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 250, in _check_response
    raise PyMISPError(everything_broken.format(response.request.headers, response.request.body, response.text))
pymisp.exceptions.PyMISPError: Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.106 - Python 3.6.7', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '25', 'Authorization': '<api_key>', 'content-type': 'application/json'}
Request body:
{"attribute": "asdfasdf"}
Response (if any):
Array
```

As best as I can tell, the only common thread between the two handlers (and the largest change to both of their code) [is this commit](https://github.com/MISP/MISP/commit/e899eb8b9d1ccaa97a6167202dfd7a5adbc011fd#diff-4696dd90b951cc67a2d642575f6011f5). Unfortunately, I'm still not quite sure what might be causing it to return `Array` instead of `[]`, but if I had to guess I'd bet it'd be something in that commit.

**Comment by iglocska** [comment] 2019-05-30 09:01
Thanks, indeed. Should be fixed now.

**Closed as completed** 2019-05-30 09:00 UTC

**Comment by TheDr1ver** [comment] 2019-05-30 10:11
Looks like that worked, thanks!

(Just to clarify, this fix also seems to be adding a growing stack of `[]` towards to the top of the event page now)

![image](https://user-images.githubusercontent.com/6147794/58626335-9190a780-82a2-11e9-9f03-69f2ea28fc38.png)

**Comment by iglocska** [comment] 2019-05-30 11:53
Should be fixed now, brainfart :)
