### ISSUE TITLE
REST in case of SSO (shibboleth)

### ISSUE THREAD

**Issue by dsever** [MISP/MISP#3786] opened 2018-10-22 13:56 UTC
Hi,

In case of using shibboleth as SP, I've configured by using instruction https (https://github.com/MISP/MISP/tree/2.4/app/Plugin/ShibbAuth):

       <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                #Require all granted
                <If "-T reqenv('HTTP_AUTHORIZATION')">
                  Require all granted
                  AuthType None
                </If>

                <Else>
                 Require valid-user
                 AuthType shibboleth
                 ShibRequestSetting requiresession On
                 ShibRequestSetting shibexportassertion On
                 ShibUseHeaders On
                </Else>
        </Directory>

Checked if, HTTP_AUTHORIZATION exists, I've tried event hardcode it as:

  SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=xi9NdGJz9EmIshvQo7L2Be1o2TOWkZuiwfJ4EaqA

But it looks like it always fires shibboleth even there is Authorization variable in header. 
So does anyone has the same problem, and is there any kind of workaround?

Thanks
Dubravko

**Comment by dsever** [comment] 2018-10-29 14:07
After few days of debugging looks like rewrite in .htaccess comes to late, and HTTP_AUTHORIZATION is empty.
So workaround would me, check header variables like:
<If "-T req('Authorization')">

Dubravko

**Comment by pettai** [comment] 2019-04-10 14:52
Hi, could you elaborate on how you solved this? 
Did you patch ./app/webroot/.htaccess or the apache configuration?

**Comment by dsever** [comment] 2019-04-11 08:13
Sorry but don't remember anymore, it was on my previous job :(

**Comment by SteveClement** [comment] 2019-04-12 09:24
@dsever do you have the same issue?

**Comment by pettai** [comment] 2019-04-12 10:06
@SteveClement you mean me @pettai, right? 
Yes, we're also running MISP with Shibb-auth infront, but I published the API on another port as a workaround instead of debugging the issue, so, hence I was curious on howto solve that. (The docs for the Shibb plugin isn't working, probably incomplete)

**Comment by marvin-sinister** [comment] 2019-04-12 11:19
The fix was to do:
```
                #<If "-T reqenv('HTTP_AUTHORIZATION')">
                <If "-T req('Authorization')">
```

in ```/etc/httpd/conf.d/misp.conf```

The root of the problem is (and i just think so, i couldn't find a definitive answer) that rewrite rule in ```/var/www/MISP/app/webroot/.htaccess```:
```
    # Adds AUTH support to Rest Plugin:
    RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization},last]
```
is not executed before you check it in apache.
In other words, for .htaccess rule to be evaluated you need access to that file, which you don't have because the rule is in that same file (and again, this is just my speculation, i couldn't find the exact order of rule execution in apache, but if i had to guess, .htaccess is last).

So the fix is to check the existence of HTTP header.

**Comment by pettai** [comment] 2019-04-13 02:39
Yes, I can confirm that it works

**Comment by pettai** [comment] 2019-04-18 20:48
I think it's safe to close this issue now...

**Closed as completed** 2020-11-30 03:30 UTC
Labels: T: support, topic: API, authentication, R: fixed
