### ISSUE TITLE
misp-backup.sh cause disk exhaustion when GnuPG homedir is empty in config.php

### ISSUE THREAD

**Issue by g4l4drim** [MISP/MISP#4312] opened 2019-03-15 14:34 UTC
Running tools/misp-backup/misp-backup.sh with an empty homedir in config.php causes a recursive copy of / to backup destination thus exhausting disk space

`GnuPGHomeDir=$(grep -o -P "(?<='homedir' => ').*(?=')" $PATH_TO_MISP/app/Config/config.php) ; checkVar GnuPGHomeDir

...

cp -rp $GnuPGHomeDir/* $TmpDir/

`

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| MISP version / git hash   | Misp v2.4.102

### Expected behavior

No copy when homedir=""

### Actual behavior

Recursive copy of / and disk-space exhaustion

### Steps to reproduce the behavior

Run misp-backup.sh without homedir set in the config.php

**Comment by SteveClement** [comment] 2019-03-17 15:57
Thanks for the report, this is the bug I have been looking for ;)

**Comment by SteveClement** [comment] 2019-03-17 16:05
@g4l4drim Could you just please confirm that you use this version of the script:

https://github.com/MISP/MISP/blob/43f0010cab9776d5bb447dc230f488b8229ffa6d/tools/misp-backup/misp-backup.sh#L151


It already has a check if the directory is empty and should warn you.

**Comment by g4l4drim** [comment] 2019-03-17 16:11
no checkVar on 2.4.102....

**Comment by SteveClement** [comment] 2019-03-17 16:12
Yeah, the problem is indeed with checkVar not doing it's thing :(

**Comment by g4l4drim** [comment] 2019-03-17 16:15
looks like the variable is set but not empty :(

Maybe:
if [ -z "$var" ] then       echo "\$var is empty" else       echo "\$var is NOT empty" fi

**Comment by g4l4drim** [comment] 2019-03-18 19:34
I confirm i was using this version of the script: https://github.com/MISP/MISP/blob/v2.4.102/tools/misp-backup/misp-backup.sh

**Comment by SteveClement** [comment] 2019-03-21 12:08
Fixed in https://github.com/MISP/MISP/pull/4349

It is not elegant, but it works ;)

**Closed as completed by SteveClement** 2019-03-21 12:08 UTC
Labels: T: potential bug, external tool, confirmed
