### ISSUE TITLE
Ubuntu upgrade to 18.04 - CakePHP related (?) issue - Reserved Word

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#4010] opened 2019-01-12 12:43 UTC
After an upgrade to Ubuntu 18.04.1 I am having trouble to get MISP running again.
I think it's tied to CakePHP.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 18.04.1 LTS
| PHP version               | 7.2
| MISP version / git hash   | 2.4.100, 15dc418d22004c80c686ddd1326d1d8e64465071

### Actual behavior

Error 500 when browsing to MISP.

### Logs, screenshots, configuration dump, ...
In the PHP logs:

` PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Object.php on line 30`

### Operations:

I tried

```
rm -R /var/www/MISP/app/Lib/cakephp
git submodule init
git submodule update
```

Also tried to follow all the relevant steps from : 
[/docs/INSTALL.ubuntu1804.md](https://github.com/MISP/MISP/blob/2.4/docs/INSTALL.ubuntu1804.md)

Still stuck. Any hints ?
(wondering if it's tied to : 
[Fix reserved word: Object (as of PHP 7.2)](https://github.com/CakeDC/migrations/pull/315)
"This was fixed in 2.9.0 - released 2016-10-18"
Following install procedure it seems I end-up with 2.8.9 - unsure how to update CakePHP version in MISP context
)

**Comment by Kafeine** [comment] 2019-01-13 10:39
Got it Fixed.

Operations fwiw:
```
git fetch --all
git reset --hard origin/2.4
git pull origin 2.4
```

then

```
rm -R /var/www/MISP/app/Lib/cakephp
git submodule init
git submodule update
```

CakePHP is now in version 2.10.9. Misp back.

**Comment by SteveClement** [comment] 2019-01-17 08:22
I will try to reproduce from a fresh install.

**Comment by SteveClement** [comment] 2019-01-25 04:26
Could not reproduce.
Closing for now.

**Closed as completed by SteveClement** 2019-01-25 04:26 UTC

**Comment by iglocska** [comment] 2019-01-25 08:15
This was indeed an issue with old versions of cakePHP and new versions of
PHP. Updating cakePHP should fix this, with the caveat that workers also
need to be restarted. Think the issue was simply the cakePHP directory
being altered and the submodule update refusing to run due to unmerged
changes. This normally happens if git filemode is not set to false and the
required permission changes are made on the MISP directory, git will think
that there's an unmerged change modifying the file permissions.
