### ISSUE TITLE
js not honoring baseurl ?

### ISSUE THREAD

**Issue by rmarsollier** [MISP/MISP#1431] opened 2016-08-11 14:49 UTC
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug |
| OS version (server) | Ubuntu srv 14.04 |
| OS version (client) | Debian 8 |
| PHP version | 5.5.9 |
| MISP version / git hash | 2.4.50, 751bad6 |
| Browser | Firefox |

Some additions:
Reverse proxy : apache2 with mod_proxy.
MISP is behind the RP, the URL to access it is `example.com/misp/`
MISP.baseurl is set accordingly
### Expected behavior

Every MISP features working after some RP configuration.

Current RP configuration:

```
<Location /misp/>
         Order deny,allow
         Allow from all
         SSLRequireSSL On
         ProxyPass http://10.10.10.10/
         ProxyPassReverse http://10.10.10.10/
         Header edit Location ^http://(.*)$ https://$1

         SetOutputFilter proxy-html
         ProxyHTMLExtended On
         ProxyHTMLURLMap "^/" "/misp/" "R"
         ProxyHTMLURLMap "https?://([^/]*)(/misp.*)$" "$2/" "R"
         ProxyHTMLURLMap "\"/events/" "\"/misp/events/" "R"
         ProxyHTMLURLMap "\"/jobs/" "\"/misp/jobs/" "R"
         RequestHeader unset Accept-Encoding
```
### Actual behavior

Many feature are not working, mainly the one depending on the misp2.4.XX.js functions to work.
I.e : editing server setting from webUI doesn't work, the url tried is `example.com/servers/serverSettingsEdit/[...]` instead of `example.com/misp/servers/serverSettingsEdit/[...]`.
#### My so dirty workaround

After editing the app/webroot/js/misp2.4.XX.js file to modify the functions (for example `function serverSettingsActivateField(setting, id)`) to include  the missing `/misp/` to the urls, it works. However, this doesn't seem to be the clean fix :)
### Steps to reproduce the behavior

The impacted fonctionnalities are , at least, the following (with the corresponding urls):
- seting edition : /servers/serverSettingsEdit/[...]
- filtering of MyEvents/OrgEvents : /events/filterEventIndex?_= [...]
- event publishing : /events/alert/[...]
- event downloading : /events/exportChoice/[...]
- freetext import : /events/freeTextImport/[...]
- add tag : /tags/selectTaxonomy/[...]
- enrichment /Attributes/hoverEnrichment/[...]
- UI - Global actions -> member list : /users/histogram/[...]  
### Logs, screenshots, configuration dump, ...

N/A

**Comment by iglocska** [comment] 2016-08-11 14:58
Good point a lot of the js relies on relative paths. This should definitely be fixed.

**Comment by adulau** [comment] 2017-01-17 20:24
Is it something fixed?

**Comment by rmarsollier** [comment] 2017-01-18 15:28
I managed to work around my problem with this some times ago so it is not a concern anymore for me, but i guess the bug is still there.

**Comment by adulau** [comment] 2017-01-18 15:59
Thank you for the feedback.

**Comment by 1inkmann** [comment] 2018-10-09 11:31
Good day! I have this problem too, is it not fixed?

**Comment by SteveClement** [comment] 2019-02-04 06:00
Closing due to non-activity.

Feel free to re-open with updated content.

**Closed as completed by SteveClement** 2019-02-04 06:00 UTC
Labels: T: bug, S: review before closing

**Comment by Quyrean** [comment] 2020-02-03 22:43
Hello I am having the same problem.  My misp is located at something like:

 https://testproxy.com/misp/

(login page is https://testproxy.com/misp/users/login)  

the browser redirect back after login is incorrect and all the css, js, and other redirects are missing the "/misp" part.  I have set the base url to "https://testproxy.com/misp/"

we are using version  MISP 2.4.117 

the returned html has links like "//users/login?%2Fusers%2Flogin=" and "/js/jquery.js".  These absolute links do not work when misp is not at the root.  For example, when trying to login, the browser is redirected to "https://users/login?%2Fusers%2Flogin=".

**Expected behavior**:
the redirect goes to "https://testproxy.com/misp/users/login?%2Fusers%2Flogin=".
 
some examples:
`      <form action="//users/login?%2Fusers%2Flogin=" id="UserLoginForm" method="post" accept-charset="utf-8"><div style="display:none;"><input type="hidden" name="_method" value="POST"/><input type="hidden" name="data[_Token][key]" value="7f7d19a6b53de0db615fb90964eb078f81bdf39ea76513e09dea697a5c322a0f73304fe12f7f6c1e8a9db7667a4fa4c595d1f201bac986210babd39525bb979d" id="Token612394077" autocomplete="off"/></div>        <legend>Login</legend>`

`<link rel="stylesheet" type="text/css" href="/css/bootstrap.css"/><link rel="stylesheet" type="text/css" href="/css/bootstrap-datepicker.css"/><link rel="stylesheet" type="text/css" href="/css/bootstrap-colorpicker.css"/><link rel="stylesheet" type="text/css" href="/css/famfamfam-flags.css"/><link rel="stylesheet" type="text/css" href="/css/font-awesome.css"/><link rel="stylesheet" type="text/css" href="/css/jquery-ui.css"/><link rel="stylesheet" type="text/css" href="/css/chosen.min.css"/><link rel="stylesheet" type="text/css" href="/css/main.css"/><link rel="stylesheet" type="text/css" href="/css/print.css" media="print"/><script type="text/javascript" src="/js/jquery.js"></script><script type="text/javascript" src="/js/misp-touch.js"></script><script type="text/javascript" src="/js/jquery-ui.js"></script><script type="text/javascript" src="/js/chosen.jquery.min.js"></script><link href="/favicon.ico" type="image/x-icon" rel="icon"/><link href="/favicon.ico" type="image/x-icon" rel="shortcut icon"/>`

here is the full page:

[Users - MISP.txt](https://github.com/MISP/MISP/files/4150555/Users.-.MISP.txt)

please advise.  Thank you.
