### ISSUE TITLE
Fixed events for Feeds have wrong attribute count

### ISSUE THREAD

**Issue by sustefil** [MISP/MISP#7196] opened 2021-03-12 08:27 UTC
I have observed 2 errors with Fixed events for Feeds:

1) The attribute count in the "List events" view doesn't match at all in the UI
2) In the database, the attributes, that are not part of the feed anymore (have been deleted from the original source), DO NOT actually get deleted in the database, they are only flagged with the field deleted=1

Maybe these errors are related

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu,
| PHP version               | dont know
| MISP version / git hash   | 2.4.137
| Browser                   | firefox

### Expected behavior
Correct numbers in the UI and the DB.

### Actual behavior

So in the event list view, I see this (wrong) number:

![image](https://user-images.githubusercontent.com/32512488/110912414-34010a00-8314-11eb-9207-640058ea3312.png)

Inside the event, this number is correct:

![image](https://user-images.githubusercontent.com/32512488/110912588-6874c600-8314-11eb-95f9-53fa35d45627.png)

In the DB, the number is correct only when I filter deleted=0 (not sure if storing the deleted=1 is a feature, if yes, please explain why)

![image](https://user-images.githubusercontent.com/32512488/110912896-c43f4f00-8314-11eb-9fbd-76f01fcb5767.png)

### Steps to reproduce the behavior

Just use some Fixed event for some Feed and after few updates, the numbers will start to mismatch I guess

**Comment by chrisinmtown** [comment] 2021-03-12 12:45
Attributes are SOFT-deleted by the Cake/MISP feed fetcher, that's the deleted column 0/1 value.  It sounds like you want them to be expunged completely (aka, hard deleted) by the Cake feed fetcher? If so please vote +1 on this issue: https://github.com/MISP/MISP/issues/6933

**Comment by sustefil** [comment] 2021-03-12 13:52
Ok thanks, voted +1

Anyway, the main bug remains, that is the wrong attribute count in the "List events" view (even when you take the soft deleted into account, this number is wrong)

**Comment by chrisinmtown** [comment] 2021-03-12 14:04
This issue is a dupe, might want to vote +1 on these old attribute-count issues: https://github.com/MISP/MISP/issues/3346 and https://github.com/MISP/MISP/issues/4768

Super frustrating that this known bug lingers for so long.

**Comment by enjeck** [comment] 2021-03-14 12:38
Duplicate of #4768. Closing this since it has fewer comments.

**Closed as completed by enjeck** 2021-03-14 12:38 UTC
Labels: T: bug, topic: feed, R: duplicate
