### ISSUE TITLE
New sighting type - (negative sighting - I haven't seen this)

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#2833] opened 2018-01-17 10:24 UTC
New sighting type - (negative sighting - I haven't seen this)

**Comment by RichieB2B** [comment] 2018-01-17 15:06
Duplicate of #2551

**Comment by iglocska** [comment] 2018-01-17 16:02
The goldfish that is the MISP dev team has yet again completed another round in our fishbowl and forgotten everything that happened before that. Good point @RichieB2B ;)

**Closed as completed** 2020-11-30 20:23 UTC
Labels: T: enhancement, topic: sighting, R: duplicate
