### ISSUE TITLE
Loop in shibboleth authentication

### ISSUE THREAD

**Issue by dsever** [MISP/MISP#3162] opened 2018-04-18 09:23 UTC
Hi, 

I'm trying to implement Shibboleth authentication for MISP instance. I'be followed available configuration from Plugin folder. But getting loop:

Please can someone provide mi assistence how to establish sso shibboleth:
 
My apache config:

<VirtualHost *:443>
        ServerAdmin me@me.local
        ServerName misp2.lab.cs
        DocumentRoot /var/www/MISP/app/webroot
        <Directory /var/www/MISP/app/webroot>
                Options -Indexes
                AllowOverride all
                #Require all granted
                Require valid-user
                AuthType shibboleth
                ShibRequestSetting requiresession On
                ShibRequestSetting shibexportassertion Off
                ShibUseHeaders On
        </Directory>

        SSLEngine On
        SSLCertificateFile /etc/ssl/crt/misp2.crt
        SSLCertificateKeyFile /etc/ssl/keys/misp2.key

        LogLevel warn
        ErrorLog /var/log/httpd/misp.local_error.log
        CustomLog /var/log/httpd/misp.local_access.log combined
        ServerSignature Off
        Header set X-Content-Type-Options nosniff
        Header set X-Frame-Options DENY
</VirtualHost>

And it gives me loop grom IDP back to SP.

Thanks

Dubravko

**Comment by dsever** [comment] 2018-04-24 07:03
I've managed to make it work, but there is mismatch in conf. documentation and code. It says that it supports default group ip, but there is no code for given feature (ok fix is 3 lines of code, I can create pool request for given fix). 
As far I can see SLO is not implemented at all?

Dubravko

**Comment by Rafiot** [comment] 2018-04-24 07:30
@dsever you should get in touch with @ppanero, he is the main maintainer of the shibboleth module.

And yes, we're welcoming pull requests.

**Comment by ppanero** [comment] 2018-04-24 07:54
Hello @dsever 

I am not sure I understand what you mean by default group *ip*. You mean Organization or egroup/role?

I am not maintaining it anymore since I have been move to another project. But I can put you in contact with the guys that are doing so lately.

Cheers,
Pablo

**Comment by dsever** [comment] 2018-04-24 07:58
Hi @ppanero,

I'm talking about default egroup id (default one if group is not provided by REMOTE_USER varibale), I've already fixed it. But problem is SLO in shibboleth, doesn't exist.

Dubravko

**Comment by ppanero** [comment] 2018-04-24 08:02
Hi again @dsever,
Okay I understand what you mean, I will ping the current manteiners :D Since Im not sure what they have been up to lately, maybe they are into the same.
cheers,
Pablo

**Comment by Rafiot** [comment] 2018-04-24 11:00
@ppanero Thank you very much :) 

And if they patched the code, we would love to get the update.

**Comment by pettai** [comment] 2018-09-26 12:59
Hi, there was never a patch/pull request sent or?

I understand its two separate issues? 
1) No group id is provided by REMOTE_USER
2) SLO isn't supported by Shibboleth

I'm wondering what the solution for the first problem is?

**Comment by niteshuk** [comment] 2019-07-28 02:27
> I've managed to make it work, but there is mismatch in conf. documentation and code. It says that it supports default group ip, but there is no code for given feature (ok fix is 3 lines of code, I can create pool request for given fix).
> As far I can see SLO is not implemented at all?
> 
> Dubravko

I am facing the same issue, can you please tell me how did you fix this issue.
Thanks

**Comment by ninpo99** [comment] 2019-09-04 18:16
Short of and prior to actually deploying the supporting identity provider and service provider is there a way to use the MISP application to determine if the MISP shibboleth plugin has been installed in the deployed application? 

I have looked at the servers and maintenance page under plugins but do not see anything related to Shibboleth plugin being present. 

This is after following the instructions in Shibboleth readme directions and enabling header custom authentication which does show the external authentication box on the user pages.

**Comment by pettai** [comment] 2019-09-05 04:46
> Short of and prior to actually deploying the supporting identity provider and service provider is there a way to use the MISP application to determine if the MISP shibboleth plugin has been installed in the deployed application?
> 
> I have looked at the servers and maintenance page under plugins but do not see anything related to Shibboleth plugin being present.
> 
> This is after following the instructions in Shibboleth readme directions and enabling header custom authentication which does show the external authentication box on the user pages.

This has nothing to do with the original issue discussed in this thread. please open a new issue

(btw. MISP-members, can you close this issue? we can't do more on the original topic)

**Comment by Sp-TT** [comment] 2020-07-21 00:46
> I've managed to make it work, but there is mismatch in conf. documentation and code. It says that it supports default group ip, but there is no code for given feature (ok fix is 3 lines of code, I can create pool request for given fix).
> As far I can see SLO is not implemented at all?
> 
> Dubravko

@dsever Could you please advise how to solve the looping issue?

**Comment by Sp-TT** [comment] 2020-07-30 00:08
> > I've managed to make it work, but there is mismatch in conf. documentation and code. It says that it supports default group ip, but there is no code for given feature (ok fix is 3 lines of code, I can create pool request for given fix).
> > As far I can see SLO is not implemented at all?
> > Dubravko
> 
> @dsever Could you please advise how to solve the looping issue?

Problem solved. 

MISP server sitting behind LB, looping caused by requests Bouncing Between HTTP and HTTPS.

**Closed as completed** 2020-11-17 16:08 UTC
Labels: T: support, authentication
