### ISSUE TITLE
MISP Upgrade, not pulling correct version...

### ISSUE THREAD

**Issue by gitnorty** [MISP/MISP#5663] opened 2020-02-21 18:20 UTC
I was trying to update MISP to 2.4.121 today; and one version back (2.4.120) is getting pulled?

Here are the steps performed:

[root@md2nj11ta www]# cd MISP

[root@md2nj11ta MISP]# git fetch
remote: Enumerating objects: 5629, done.
remote: Counting objects: 100% (4342/4342), done.
remote: Compressing objects: 100% (1337/1337), done.
remote: Total 3829 (delta 3020), reused 3266 (delta 2473), pack-reused 0
Receiving objects: 100% (3829/3829), 2.58 MiB | 833.00 KiB/s, done.
Resolving deltas: 100% (3020/3020), completed with 248 local objects.
From https://github.com/MISP/MISP
   af87a64..980dbf5  2.4        -> origin/2.4
 * [new branch]      Rafiot-patch-4 -> origin/Rafiot-patch-4
 * [new branch]      add_attribute -> origin/add_attribute
 * [new branch]      dev/migration-views -> origin/dev/migration-views
 * [new branch]      enforce-iso-datetime -> origin/enforce-iso-datetime
   5c7a5d0..386b910  feature-fix-db-inconsistencies -> origin/feature-fix-db-inconsistencies
   3f4ba24..f1a0035  gh-pages   -> origin/gh-pages
 * [new branch]      move_forms -> origin/move_forms
 * [new branch]      nibbler    -> origin/nibbler
 * [new branch]      push_sightings_final -> origin/push_sightings_final
 * [new branch]      retention_perpetual_decay -> origin/retention_perpetual_decay
 * [new branch]      rework_stix -> origin/rework_stix
 * [new branch]      sqlIndexDiagnostic -> origin/sqlIndexDiagnostic
 * [new branch]      zoidberg-final -> origin/zoidberg-final
 * [new branch]      zoidberg_final -> origin/zoidberg_final
From https://github.com/MISP/MISP
 * [new tag]         v2.4.119   -> v2.4.119
 * [new tag]         v2.4.120   -> v2.4.120
 * [new tag]         v2.4.121   -> v2.4.121
Fetching submodule PyMISP
remote: Enumerating objects: 477, done.
remote: Counting objects: 100% (477/477), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 633 (delta 396), reused 411 (delta 339), pack-reused 156
Receiving objects: 100% (633/633), 330.71 KiB | 0 bytes/s, done.
Resolving deltas: 100% (438/438), completed with 83 local objects.
From https://github.com/MISP/PyMISP
 * [new branch]      datetime-parsing -> origin/datetime-parsing
   5ebaca3..3537739  master     -> origin/master
 * [new branch]      poetry     -> origin/poetry
 * [new branch]      python3.6  -> origin/python3.6
From https://github.com/MISP/PyMISP
 * [new tag]         v2.4.117.3 -> v2.4.117.3
 * [new tag]         v2.4.119   -> v2.4.119
 * [new tag]         v2.4.119.1 -> v2.4.119.1
 * [new tag]         v2.4.120   -> v2.4.120
 * [new tag]         v2.4.121   -> v2.4.121
 * [new tag]         v2.4.121.1 -> v2.4.121.1
Fetching submodule PyMISP/pymisp/data/misp-objects
remote: Enumerating objects: 236, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 446 (delta 198), reused 214 (delta 180), pack-reused 210
Receiving objects: 100% (446/446), 92.41 KiB | 0 bytes/s, done.
Resolving deltas: 100% (250/250), completed with 35 local objects.
From https://github.com/MISP/misp-objects
   3d7b09e..8de8d85  master     -> origin/master
Fetching submodule app/files/misp-decaying-models
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 8 (delta 4), reused 8 (delta 4), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/MISP/misp-decaying-models
   0bf4d8b..f1b9747  master     -> origin/master
Fetching submodule app/files/misp-galaxy
remote: Enumerating objects: 251, done.
remote: Counting objects: 100% (251/251), done.
remote: Total 378 (delta 251), reused 251 (delta 251), pack-reused 127
Receiving objects: 100% (378/378), 359.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (260/260), completed with 27 local objects.
From https://github.com/MISP/misp-galaxy
   5dc55fb..c98093e  master     -> origin/master
Fetching submodule app/files/misp-objects
remote: Enumerating objects: 236, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 446 (delta 198), reused 214 (delta 180), pack-reused 210
Receiving objects: 100% (446/446), 92.41 KiB | 0 bytes/s, done.
Resolving deltas: 100% (250/250), completed with 35 local objects.
From https://github.com/MISP/misp-objects
   3d7b09e..8de8d85  master     -> origin/master
Fetching submodule app/files/taxonomies
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 79 (delta 35), reused 66 (delta 23), pack-reused 0
Unpacking objects: 100% (79/79), done.
From https://github.com/MISP/misp-taxonomies
   e7df5c2..a3f7cf8  master     -> origin/master
Fetching submodule app/files/warninglists
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 103 (delta 47), reused 34 (delta 26), pack-reused 19
Receiving objects: 100% (103/103), 5.17 MiB | 929.00 KiB/s, done.
Resolving deltas: 100% (47/47), completed with 10 local objects.
From https://github.com/MISP/misp-warninglists
   baa2588..6592642  master     -> origin/master
Fetching submodule cti-python-stix2
remote: Enumerating objects: 270, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 393 (delta 256), reused 264 (delta 255), pack-reused 123
Receiving objects: 100% (393/393), 94.62 KiB | 0 bytes/s, done.
Resolving deltas: 100% (303/303), completed with 60 local objects.
From https://github.com/MISP/cti-python-stix2
   e2a4129..5aaf077  master     -> origin/master
   
[root@md2nj11ta MISP]# git describe --tags `git rev-list --tags --max-count=1`
v2.4.121

[root@md2nj11ta MISP]# cat VERSION.json
{"major":2, "minor":4, "hotfix":118}

[root@md2nj11ta MISP]# git checkout tags/$(git describe --tags `git rev-list --tags --max-count=1`)
error: Your local changes to the following files would be overwritten by checkout:
        app/Controller/LogsController.php
        app/View/Elements/Events/View/attribute_correlations.ctp
Please, commit your changes or stash them before you can switch branches.
Aborting

[root@md2nj11ta MISP]# git stash
Saved working directory and index state WIP on (no branch): 448f8a9 Merge branch '2.4' of github.com:MISP/MISP into 2.4
HEAD is now at 448f8a9 Merge branch '2.4' of github.com:MISP/MISP into 2.4

[root@md2nj11ta MISP]# git checkout tags/$(git describe --tags `git rev-list --tags --max-count=1`)
M       PyMISP
M       app/files/misp-decaying-models
M       app/files/misp-galaxy
M       app/files/misp-objects
M       app/files/taxonomies
M       app/files/warninglists
M       cti-python-stix2
Previous HEAD position was 448f8a9... Merge branch '2.4' of github.com:MISP/MISP into 2.4
HEAD is now at 88894fc... chg: [version] bump

[root@md2nj11ta MISP]# cat VERSION.json
{"major":2, "minor":4, "hotfix":120}

As you can see, version 120 was checked out not 121.

Any help in resolving this would be appreciated.

If other information is required, please let me know?

Thanks.

**Comment by gitnorty** [comment] 2020-02-21 18:27
If I perform the steps, which I believe will grab the latest commit, I see the expected version as shown below.  But I'd like to get the latest point release as I was trying to perform as shown above.

[root@md2nj11ta MISP]# git pull origin 2.4
From https://github.com/MISP/MISP
 * branch            2.4        -> FETCH_HEAD
Updating 88894fc..980dbf5
Fast-forward
 INSTALL/INSTALL.sh                                  |  38 +++++++++++++-----------
 INSTALL/INSTALL.sh.sha1                             |   2 +-
 INSTALL/INSTALL.sh.sha256                           |   2 +-
 INSTALL/INSTALL.sh.sha384                           |   2 +-
 INSTALL/INSTALL.sh.sha512                           |   2 +-
 INSTALL/INSTALL.tpl.sh                              |  17 ++++++-----
 README.debian                                       |  23 +++++++++++++++
 VERSION.json                                        |   2 +-
 app/Console/Command/AdminShell.php                  |  50 ++++++++++++++++++++++++++++++++
 app/Controller/AppController.php                    |   8 ++++++
 app/Controller/DecayingModelController.php          |   2 +-
 app/Controller/EventsController.php                 |  11 -------
 app/Lib/Tools/ComplexTypeTool.php                   |   6 ----
 app/Lib/Tools/PubSubTool.php                        |   4 +--
 app/Model/Attribute.php                             |   2 +-
 app/Model/Event.php                                 |   5 +++-
 app/Model/FuzzyCorrelateSsdeep.php                  |   7 ++---
 app/Model/Galaxy.php                                |   2 +-
 app/Model/ObjectTemplateElement.php                 |   2 +-
 app/Model/Server.php                                |  14 ++++++++-
 app/Model/Tag.php                                   |   4 +--
 app/View/Communities/view.ctp                       |   4 +--
 app/View/Elements/eventattributetoolbar.ctp         |   2 +-
 app/View/Elements/genericElements/viewMetaTable.ctp |   3 +-
 app/View/Servers/edit.ctp                           |  35 ++++++++++++++---------
 app/View/SharingGroups/index.ctp                    |   2 +-
 app/composer.phar                                   | Bin 1704783 -> 1932034 bytes
 app/files/community-metadata/defaults.json          |  19 ++++++++++--
 app/files/misp-objects                              |   2 +-
 app/files/scripts/mispzmq/mispzmq.py                |  19 ++++++------
 app/webroot/js/event-graph.js                       |  10 +++++--
 build-deb.sh                                        |   4 +++
 debian/README                                       |   1 +
 debian/changelog                                    |  11 +++++++
 debian/config                                       |  20 +++++++++++++
 debian/control                                      |  41 ++++++++++++++++++++++++++
 debian/install                                      |   6 ++++
 debian/misp.apache2                                 |   1 +
 debian/misp.apache2.conf                            |  28 ++++++++++++++++++
 debian/patches/Add-CakeResque-Config.patch          | 203 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 debian/patches/series                               |   1 +
 debian/postinst                                     |  79 ++++++++++++++++++++++++++++++++++++++++++++++++++
 debian/rules                                        |   6 ++++
 debian/source/format                                |   1 +
 debian/templates                                    |  41 ++++++++++++++++++++++++++
 docs/generic/misp-dashboard-centos.md               |   3 ++
 docs/generic/misp-dashboard-debian.md               |   4 +++
 docs/generic/supportFunctions.md                    |  21 +++++++-------
 48 files changed, 666 insertions(+), 106 deletions(-)
 create mode 100644 README.debian
 create mode 100755 build-deb.sh
 create mode 100644 debian/README
 create mode 100644 debian/changelog
 create mode 100755 debian/config
 create mode 100644 debian/control
 create mode 100644 debian/install
 create mode 100644 debian/misp.apache2
 create mode 100644 debian/misp.apache2.conf
 create mode 100644 debian/patches/Add-CakeResque-Config.patch
 create mode 100644 debian/patches/series
 create mode 100644 debian/postinst
 create mode 100755 debian/rules
 create mode 100644 debian/source/format
 create mode 100644 debian/templates

[root@md2nj11ta MISP]# git submodule update --init --recursive
Submodule path 'PyMISP': checked out 'cb718b97f1e36e11a06870adb5368309e1c14912'
Submodule path 'PyMISP/pymisp/data/misp-objects': checked out '3ba77c9d2cfea5c27bc8935812d83be54c4f0fd4'
Submodule path 'app/files/misp-decaying-models': checked out 'f1b974790f0969fab4251046f292eedc59a272ca'
Submodule path 'app/files/misp-galaxy': checked out '33aa1c8f3f25a70b9ab393c48db0b9c6a1776971'
Submodule path 'app/files/misp-objects': checked out '8de8d85979e3ecf3c426c660f58400a48695e42e'
Submodule path 'app/files/taxonomies': checked out '90f77df5792109de3b810006616dcbc68e239a3b'
Submodule path 'app/files/warninglists': checked out '659264240a82893e22df6dccdf8fbdced6398b43'
Submodule path 'cti-python-stix2': checked out '96946d956d41b4c9c9b24683add88f457181ee75'

[root@md2nj11ta MISP]# cat VERSION.json
{"major":2, "minor":4, "hotfix":121}

**Comment by RichieB2B** [comment] 2020-02-22 17:27
The problem is that tag v2.4.121 does not include the updated VERSION.json that still contains 2.4.120

**Comment by gitnorty** [comment] 2020-02-24 14:51
Thanks for the feedback.

**Comment by gitnorty** [comment] 2020-02-24 18:00
Will this be addressed for the 2.4.121 release?  Nice to have this as a quick confirmation that the desired release was pulled...  Thanks.

**Comment by RichieB2B** [comment] 2020-02-24 18:06
Someone with the proper rights should check out 349ec58941f369a16ba1b660f7fadc50f0d4d671 and retag it with v2.4.121

**Comment by github-germ** [comment] 2020-02-25 19:09
+1 ... Any chance to get this updated "soon". Many thanks!

**Comment by iglocska** [comment] 2020-02-26 15:52
Fixed indirectly. 2.4.122 is out :p

**Closed as completed by iglocska** 2020-02-26 15:52 UTC

**Comment by github-germ** [comment] 2020-02-26 16:33
> Fixed indirectly. 2.4.122 is out :p

When will .122 be officially released? THANKS!

**Comment by iglocska** [comment] 2020-02-27 05:46
It is 😉
