### ISSUE TITLE
Failed Login with default credentials

### ISSUE THREAD

**Issue by atekaya** [MISP/MISP#1513] opened 2016-09-06 08:36 UTC
Hi,
I installed MISP on twice (on two VMs) once using the readme file and once using this script (https://github.com/da667/AutoMISP/blob/master/auto-MISP-ubuntu.sh).
I couldn't in both cases log in with default credentials (admin@admin.test/admin)
I amd using Ubunty 16.04, Firefox 48 , MISP

**Comment by ventz** [comment] 2016-09-10 06:17
Exactly same issue here.

Noticing that if I delete the mysql user it works (even though I changed the salt before the first login as per the steps). Also I can change manually (/var/www/MISP/app/Console/cake Password XYZ) and then it works too. Did someone set a different password?

Maybe related -- but the first login after creating a new VM always tells me:
Error: The requested address '/users/login' was not found on this server.
(and it blackholes the request).

From that point on if I change the password/reset, it always works.

**Comment by atekaya** [comment] 2016-09-13 14:27
It worked I just had to change the password. Thanks

**Comment by ventz** [comment] 2016-09-13 14:53
@atekaya - the problem with this is that it prevents automation - since the password cannot be changed until the web url is hit.

There's a bigger problem here.

**Comment by iglocska** [comment] 2016-09-13 15:43
This is definitely an issue, will investigate it.

**Comment by ventz** [comment] 2016-09-13 23:24
@iglocska thanks for looking into this!

**Comment by ventz** [comment] 2016-09-15 03:12
@iglocska By the way - the reason this is a concern is because at my work we are releasing a fully automated docker container (will be also autobuilt, and has variable options for key parts), which we plan on supporting as versions of MISP change in the future. Everything is ready, but this is the only bit that's preventing us from publishing github to be public so we can autobuild in dockerhub. We don't want to release it and have a few people try it and find out that the default login doesn't work.

**Comment by ventz** [comment] 2016-09-27 02:58
Looks like it was fixed with the latest change from a few days ago?
(only change we saw and applied was composer.phar upgrade per new notes from 1.1.2 to 1.2.1)

**Comment by ventz** [comment] 2016-09-27 03:19
Yep - confirming - it looks like that fixed it! Running some tests, and then we will publish the container. I'll put up links here.

**Comment by ventz** [comment] 2016-09-27 07:02
Here is everything published on DockerHub:
https://hub.docker.com/r/harvarditsecurity/misp/

and the GitHub repo for it:
https://github.com/harvard-itsecurity/docker-misp

@cristianbell ^

If anyone has any suggestions on ways to improve it, please let me know!

**Comment by annetteshajan** [comment] 2020-06-22 06:38
@SteveClement @iglocska I'm getting this same error on first login
Can you help out?

**Comment by mokaddem** [comment] 2020-07-17 14:33
@annetteshajan If you have an error with the default password, you can reset it by using the MISP cli
```
MISP/app/Console/cake Password [email] [new_password]
```

**Comment by ankitsynx** [comment] 2021-05-21 13:05
what's the fix here? The problem is still here in 2021 with docker install. Using latest MISP version.

**Comment by adulau** [comment] 2021-05-21 14:35
> what's the fix here? The problem is still here in 2021 with docker install. Using latest MISP version.

What's your version? Install process? It depends how you setup your initial credentials. 

and there is an explanation on how to reset a password just above in this issue:

~~~
MISP/app/Console/cake Password [email] [new_password]
~~~

**Closed as completed by adulau** 2021-05-21 14:35 UTC
Labels: T: bug, T: support, authentication, needs documentation

**Comment by mahsaghorbanpour** [comment] 2025-02-12 19:39
Resetting a Password When Username and Password Are Not Recognized
To reset the password, follow these steps to access the MySQL database with root privileges and update the user's password hash.

Steps:
1) sudo su
2) sudo mysql
3) use misp;
4) SELECT * FROM users; 
5) UPDATE users SET password = 'your_password_hash' WHERE email = 'admin@admin.test';
6) exit
7) sudo systemctl restart apache2

Generating a Password Hash
You can generate the required password hash using this tool:
[MySQL Password Hash Generator](https://www.edchart.com/free-online-converters/mysql-password.php)

Hash for 'admin' password = $2y$10$80xoj1Yd1peaveQu9UNB8OE1Q4tjwNLC9PORJ8.pWyXqCVuSvnnMK
