### ISSUE TITLE
Enhancement: Bulk upload files

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#337] opened 2014-11-25 08:38 UTC
Bulk upload files of a certain category.

**Comment by Rafiot** [comment] 2016-03-29 13:39
Recommended way: API 

Duplicate of https://github.com/MISP/MISP/issues/750 

Closing

**Closed by Rafiot** 2016-03-29 13:39 UTC
Labels: enhancement

**Comment by iglocska** [comment] 2016-03-29 14:00
Also, doable via the UI for a while now.
