### ISSUE TITLE
Regexp for filenames

### ISSUE THREAD

**Issue by cvandeplas** [MISP/MISP#51] opened 2013-03-08 10:03 UTC
Reported by David Andre, Mar 29, 2012

Via a new type or inside filename type?
Format could be glob or regexp.

ie: for duqu ~DQ*.tmp or ~DQ[09]{1,3}.tmp

**Comment by elhoim** [comment] 2015-08-26 10:04
Duplicate of #403, tracked under the umbrella ticket https://github.com/MISP/MISP/issues/460. Closing

**Closed by elhoim** 2015-08-26 10:04 UTC
Labels: enhancement, functionality
