### ISSUE TITLE
Decay models are not listed under the Decaying Models Tool

### ISSUE THREAD

**Issue by ag-michael** [MISP/MISP#7576] opened 2021-07-20 01:39 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Any
| OS version (client)       | Any
| PHP version               | 7.2
| MISP version / git hash   | 2.4.141/b714571ad7ff1a95dee264b02d96e231ae796f93
| Browser                   | any

### Expected behavior

The decaying models tool (`/decayingModel/decayingTool`) should list available models

### Actual behavior

Available decaying models are not listed. These models are however listed under `/decayingModel/index`

### Steps to reproduce the behavior

If you already have decaying models defined, visit the page for decaying model tool

### Logs, screenshots, configuration dump, ...

List Decaying models:

![image](https://user-images.githubusercontent.com/39683291/126248873-fa830ad5-71c0-4d2a-92b8-d7fe6d907bd1.png)

Decay model tool page:

![decayingmodelstool](https://user-images.githubusercontent.com/39683291/126249186-a613da71-0b85-43e4-a590-091fe4152cb5.png)

**Comment by mokaddem** [comment] 2021-07-23 13:07
Do you see error in your browser console? Also, anything in your logs?

**Comment by ag-michael** [comment] 2021-07-23 18:39
@mokaddem  no errors or any other event in apache logs or in app/tmp/logs/* under misp install. what else can I do to troubleshoot?

**Comment by ag-michael** [comment] 2021-08-02 12:53
@mokaddem  any update?

**Comment by ag-michael** [comment] 2021-08-02 14:38
@mokaddem  apologies, I didn't read your question properly, there was indeed an error in the browser for URL: `/decayingModel/getAllDecayingModels/?all=1`. It is a 403 error with message: 

`{"name":"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.","message":"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.","url":"\/decayingModel\/getAllDecayingModels\/?all=1"}`

**Comment by ag-michael** [comment] 2021-08-11 14:10
@mokaddem  any idea on how to resolve this?

**Comment by mokaddem** [comment] 2021-08-16 14:07
Hey @ag-michael , authentication failed, this is interesting..
How do you log into MISP?
Standard user-password login form? Custom auth? Authentication plugins?
Do you also have this error whenever you are browsing other pages?
Thanks

**Comment by Y4N4EL** [comment] 2021-08-20 13:39
Hey @ag-michael and @mokaddem, I'm currently facing the same issue.
For my part the authentication to the API is made by token.
And the most amazing thing is the next one : when I directly request '/decayingModel/getAllDecayingModels/?all=1' with my browser, there is no error, I get my json.
Have you any idea of where the problem might come from ?

**Comment by ag-michael** [comment] 2021-08-23 21:29
@mokaddem  I login using an LDAP integration with apache+misp, nly that specific page shows that error.  Similar to @Y4N4EL , I get the JSON just fine when requesting it directly on the same tab. It is using the Basic authorization with my ldap user+password in base64. when I mess with that, I get a 401, which means it isn't an authentication issue, but the user is not somehow authorized, even though it is an admin user account.

**Comment by mokaddem** [comment] 2021-08-31 08:20
Hey guys, sorry for the late response. I was sure I already replied to this thread.
Thanks @ag-michael for the nudge ;)

The issue you are encountering is a flaw in the authentication logic of MISP (or a misconfiguration of your LDAP setup?).
Let me try to quickly explain:

If you look at the [authentication scheme of MISP](https://github.com/MISP/MISP/tree/develop/docs/generic/Authentication%20Diagram), you can see that if you perform a request on a REST endpoint (such as the `/decayingModel/getAllDecayingModels), MISP will try to authenticate the user with the API key (even thought the user has already been authenticated via the ApacheSercureAuth plugin):
1. MISP picks up the `Authorization` header (which contains the `Basic Auth` for LDAP and not the expected MISP API Key)
2. MISP fails to resolve the API key to a user (which is the expected behavior in this case) and throws and `Authentication failed`.

I see two possible solutions to solve this issue:
1. Once the authentication via LDAP is successful, if you were to clear the `Authorization` header, it should not try to authenticate with the MISP API key and the request should succeed.
2. Fix the authentication logic in MISP and ignore API authentications if the `Authorization` header is of type `Basic Auth`.
So something like this:
```php
// class AppController extends Controller
// [...]
         // Authenticate user with authkey in Authorization HTTP header
+        if (!empty($_SERVER['HTTP_AUTHORIZATION']) && substr($_SERVER['HTTP_AUTHORIZATION'], 0, 5) === "Basic") { // Skip Basic Authorizations
+            return null;
+        }
         if (!empty($_SERVER['HTTP_AUTHORIZATION']) || !empty($namedParamAuthkey)) {
             $foundMispAuthKey = false;
             $authentication = explode(',', $_SERVER['HTTP_AUTHORIZATION']);
// [...]
```

I would like to go for solution 2, but I'm not sure how this change would impact other authentication schemes contributed by the community. So, this should be explored first before merging the change above.

If you are willing to, trying the solution 2 with your current setup would help us a lot.
And trying with other authentication schemes would help us tremendously! :wink:

**Comment by Y4N4EL** [comment] 2021-08-31 09:29
Hi guys !
Thanks @mokaddem for your explanation and fix.
I have test your solution 2, and it works !
Since I am using exactly the same authentication scheme as @ag-michael I think it will also solve the problem ! 😉

**Comment by ag-michael** [comment] 2021-08-31 16:47
@mokaddem Thank you for the fix. Unfortunately our dev box doesn't have LDAP integration and I can't mess with the code in prod. But if the next misp release contains the fix, I can test it then.  Meanwhile, If solution #1 is something I can implement in apache's config (no idea how for what you proposed), please point me in the right direction. 

Lastly, regarding solution 2, pardon my ignorance but what if an attacker submits a fake Basic authorization header, would apache return a 401 before passing it to MISP?

@Y4N4EL  Thank you for testing this!

**Comment by Y4N4EL** [comment] 2021-09-01 13:23
@ag-michael I don't know how it works in depth, but I have made this test and indeed if i alter my Basic token I get a 401.

**Comment by ag-michael** [comment] 2021-10-10 02:03
@mokaddem  has this had any progress?

**Comment by ag-michael** [comment] 2022-01-18 01:41
@mokaddem  I just upgraded MISP, hoping this was fixed :( any progress?

**Comment by mokaddem** [comment] 2022-01-18 13:32
It is fixed on the `develop` branch and will be part of the `2.4` branch on the next release.
@ag-michael apologies for the massive delay and thanks for your perseverance. ;)

**Closed as completed** 2022-02-04 15:25 UTC
Labels: needs triage

**Comment by ag-michael** [comment] 2022-02-05 16:13
@mokaddem  I can confirm the fix did the job. Thank you!
