### ISSUE TITLE
Disable correlation not working

### ISSUE THREAD

**Issue by p3tr0v** [MISP/MISP#3561] opened 2018-08-16 15:42 UTC
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian 
| OS version (client)       | 9.4
| PHP version               |  7.0
| MISP version / git hash   | 2.4.94
| Browser                   | FF , CR
 
I observed that 'disable_correlation' is not working.
I created an object, setted 'disable correlation' true but MISP are correlating yet.
![config](https://user-images.githubusercontent.com/28512249/44219099-95a76a80-a151-11e8-82c0-fc03b6e4929b.png)

The object populated
![capturar](https://user-images.githubusercontent.com/28512249/44219114-9f30d280-a151-11e8-948b-c08ca8ee40e9.PNG)

But in the graph MISP correlate them, I think they didn't has to correlate, this make the graph visual poluted
![correlacao](https://user-images.githubusercontent.com/28512249/44219123-a6f07700-a151-11e8-8c43-2e33030e42c9.png)

**Comment by cvandeplas** [comment] 2018-11-01 09:49
I can confirm the same behavior with other objects.

The object definition contains the disable_correlation for the `file` object:
![image](https://user-images.githubusercontent.com/1073662/47844837-b764d500-ddc3-11e8-94de-d3972a2618e8.png)


Correlations appear on an object-attribute:
![image](https://user-images.githubusercontent.com/1073662/47844745-7a98de00-ddc3-11e8-9aae-887b2e9f9a7a.png)

(this event was created by a feed, event uuid `5a63182c-6bc4-4774-99d4-04070a00020f`

**Comment by mokaddem** [comment] 2018-11-21 15:34
Hi @cvandeplas, we recently pushed a fix preventing the edition of the ``disabled_correlation`` field. I then tried to reproduce your issue (steps below) and it was working for me. Could you please try again and if it is still not working for you, provide more detailed steps to reproduce? Thanks a lot.
- Add Object ``File v15``
- Add a Mimetype value
- Let all ``disable_correlation`` fields set to template's default value
- Submitted (obviously)
-> **Correlate** field is not checked

**Comment by SteveClement** [comment] 2019-02-04 06:02
Closing due to non-activity.

Feel free to re-open with updated content.

**Closed as completed by SteveClement** 2019-02-04 06:02 UTC
Labels: T: potential bug, S: under investigation, S: review before closing
