### ISSUE TITLE
New theme is not responsive

### ISSUE THREAD

**Issue by ANSSI-BSOD** [MISP/MISP#1251] opened 2016-06-10 09:35 UTC
The new top black header hide menu item when the width is reduced.
It is confusing if you use it on a landscape screen.

It might be interesting to use common tools like bootstrap no? 
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | ergonomics |
| OS version (client) | Debian (local) |
| MISP version / git hash | 2.4.48 |
| Browser | chromium, iceweasel |
### Steps to reproduce the behavior

Just reduce the width of the browser window

**Comment by cristianbell** [comment] 2016-06-10 09:54
Hi! 
Thanks for the issue report. 
I tried to reporduce the issue on Firefox 46 and 47, Chrome 50, Opera 37 and Internet Exprorer 11 but I can't replicate the issue. 
Do you have the option of using one of the above mentioned browsers? 

On a side note, the design is not really responsive at the moment, and we are already using bootstrap.

**Comment by ANSSI-BSOD** [comment] 2016-06-10 10:51
Hi 
Sorry for bootstrap :)
I see the link here ^^ 
https://github.com/MISP/MISP/tree/2.4/app/webroot/css

Friefox ESR : 45.2.0
Chrome : Version 51.0.2704.79 Built on 8.4, running on Debian 8.5 (64-bit)

Here a little gif 
![animated](https://cloud.githubusercontent.com/assets/17572412/15962176/8e8781ac-2f09-11e6-87dd-e0e57f45d6df.gif)

**Comment by cristianbell** [comment] 2016-06-10 11:06
Ok, this is odd, must be a Linux issue. For me (all mentioned browsers) but running on Windows the side menu is just pushed down. 

I see that there is no Ubuntu/Linux on Browserstack. I'll try to set up a Ubuntu start up stick as soon as possible and test it there. 

I'll let you know as soon as I have some more info.

**Comment by iglocska** [comment] 2016-06-10 11:38
Indeed, I have it too. The issue can be reproduced by disabling the debug mode.

**Comment by cristianbell** [comment] 2016-06-10 12:31
Yep, igloscka is right. 
At the moment the solution is to increase the width of the browser.

**Comment by iglocska** [comment] 2016-06-10 12:35
A bit of elaboration: Right now it's a temporary measure, @SleuthKid is working on a UI rework that he is doing in steps to avoid diverging too far from the main code-base. For the time-being, indeed increasing the browser size if your best bet, but it's only a temporary measure.

**Comment by rhaist** [comment] 2016-06-10 12:40
Indeed. It has not been responsive before the change (afaik). We first try to use all non-breaking changes to the templates bootstrap 2.x provides to clean up everything and then lift the codebase to bootstrap 3.x (or 4.x until then).

**Comment by iglocska** [comment] 2016-06-10 13:01
It had a hacky solution before to it which was flat out nasty, so you removing it is definitely a move in the right direction, even if it temporarily looks weirder (it collapsed the logo for example and used a larger gap between the top bar and the content).

**Comment by rhaist** [comment] 2016-06-10 13:18
In my initial pull request I set the navbar as "navbar navbar-fixed-top navbar-inverse" which would be the right BS 2.x type for this kind of UI and placement. This would be responsive (a little bit :) )

You removed this due to interference with the debug mode (which should also be up to discussion IMHO when it breaks normal user UI).

Right now the navbar is glued on top with the wrong navbar class which breaks responsibility.

We will sort this out somehow :)

**Comment by cristianbell** [comment] 2016-06-10 15:00
@SleuthKid can you point me to your commit? Or can you just send me the original html line with the navbar.. that had issues with the debug mode on? 
thanks!

**Comment by rhaist** [comment] 2016-06-10 15:04
@cristianbell sure:

My pull: https://github.com/MISP/MISP/commit/66aee6b8d4525eae4d78c7624f6b421669a610cf

The aftercare: https://github.com/MISP/MISP/commit/c36f62d47ef17f86c34c2e8eff96101fe9a6ccfb

**Comment by cristianbell** [comment] 2016-06-16 13:47
@SleuthKid sorry I only got time to look into this now. Did you change something in the meanwhile? for me actually the additional "navbar-fixed-top" just makes the top menu go over the left menu/page... It is better w/o it, w/ or w/o debug. 

@iglocska what was the issue with "navbar-fixed-top" while having the debug on? I don't see it right away - home, list users, event details..

**Comment by iglocska** [comment] 2016-06-16 16:14
It was overlapping with debug messages blocking out the first line of
debug.

**Comment by Yradio** [comment] 2017-10-12 08:09
The blue left nav menu hidden by the top inverse menu issue when the windows is narrowed is still present.

Look like #332 ?


### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug.
| OS version (server)    | CentOS 6
| OS version (client)     | windows 10
| PHP version               | 5.6.
| MISP version / git hash   | v2.4.80 (09dd5b12c0f7f559d5724660f99956e1f25510fd)	
| Browser                   | Edge 38.14393.1066.0 or Chrome Version 61.0.3163.100.

### Expected behavior

When the windows is narrowed, the top inverse menu should not overlap the blue left nav menu.


### Actual behavior

The blue left nav menu is hidden by the top inverse menu when the windows is narrowed.

### Steps to reproduce the behavior

Change the wide of the window.


### Logs, screenshots, configuration dump, ...

**Comment by iglocska** [comment] 2017-10-12 10:05
This should have been resolved as of the latest commits, could you git pull and test again?

**Comment by BenjaminJoly** [comment] 2018-01-19 14:44
Any news about the issue ? Is this still a problem with an up-to-date misp ?

**Comment by iglocska** [comment] 2018-01-23 14:07
This should be resolved by now.

**Closed as completed by iglocska** 2018-01-23 14:07 UTC
Labels: T: bug, visual
