### ISSUE TITLE
Object references not synced for event that has already been synced once before

### ISSUE THREAD

**Issue by Wachizungu** [MISP/MISP#7026] opened 2021-02-17 16:02 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04.5 LTS (both MISP instances)
| OS version (client)       | Windows 10 but N/A
| PHP version               |  7.2.24
| MISP version / git hash   | 2.4139, 8233f0f6143472be376ab31ea7ca6d18d670b5fd

### Expected behavior
Object references in event graph get synced to remote instance

### Actual behavior
Object references in event graph do not get synced to remote instance (or at least they don't show up in event graph)

### Steps to reproduce the behavior

1. Create an event on instance A with distribution that means it will get shared with a remote instance B
2. Add an object or attribute in the event on instance A and publish (confirm correctly synced with B)
3. Add some objects as well as related references in the event graph to the event on instance A
4. Publish the event

-> Result, new objects etc get synced with B but object reference(s) in event graph do not

Notes:

- The references get synced if added before the first publication / sync
- Type of objects / attributes doesn't seem to matter but I tried with malware sample / file , windows services and ip-port
- The published flag is unset correctly when I add the new references
- I used a sharing group
- Easiest reproduction scenario you have is to just take an existing event you know has been synced, add a reference, resync, check on remote

edits:

- Clarified to make sure there is no misunderstanding as to what I mean with object references. I mean references in the event graph linking objects or objects with attributes

**Comment by mokaddem** [comment] 2021-02-18 14:27
Hey @Wachizungu !
Your precise description, helped us a lot to track down the issue!
The issue is now fixed on a225ac4483687251b4ae0b5853d6ffa34814a66d.
Thanks a lot for your help!

**Closed as completed by mokaddem** 2021-02-18 14:27 UTC
Labels: T: bug, topic: object, topic: sync, confirmed

**Comment by Wachizungu** [comment] 2021-02-18 15:28
Super, thanks!
