### ISSUE TITLE
Support: Azure AD authentication

### ISSUE THREAD

**Issue by LOMA-TheCollectiveConsulting** [MISP/MISP#8403] opened 2022-05-24 16:20 UTC
### Support Questions

Hi

I'm currently having some issue's getting the Azure AD authentication plugin to work properly. 

I implemented the following guide: https://github.com/MISP/MISP/tree/2.4/app/Plugin/AadAuth
I created users with the same username as their upn in Azure AD. 
They are created as a regular User.  
I have set no password when creating the MISP user, as I expect it to use the auth token provided by Azure AD. 

I have added the user to the site admin group in Azure AD. (The group that is also configured in the config file in MISP)
I assume that if I have added the user to the Site admin group in AD that the assigned permissions on the MISP instance are overwritten? As I can't create a MISP user without any permissions. 

My experience:
When I use the "login with azure AD" the authentication flows start. 
I'm forwarded the tenant Azure Ad sign-in experience, confirm with MFA. 
In Azure Ad, I can see lots of successful sign-in with the app registration I created. 

On completion, I'm being forwarded to the sign-in  page of the MISP instance with a token in the URL bar. 
But I'm not signed in. 

I have also included some error logs from the MISP vm. 

### MISP version

 v2.4.158 (2564a90dd9e43104f94cb4e5c3a53ed16ffc8907)

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3 

### Relevant log output

```shell
error log output:
2022-05-24 16:03:07 Warning: Error received during Bearer token fetch (context).
2022-05-24 16:03:07 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token) [<a href='http://php.net/function.file-g
et-contents'>function.file-get-contents</a>]: failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AadAuthenticateAuthenticate::authenticate() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 158
AuthComponent::identify() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 772
AuthComponent::login() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 612
UsersController::login() - APP/Controller/UsersController.php, line 1188
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ntnco** [comment] 2022-06-10 12:29
I have the same issue with the same error `400 Bad Request` when Group Auth is enabled. However, if Group Auth is disabled, it works.

**Comment by ThijsLecomte** [comment] 2022-06-14 11:25
Would you have any input on this? @noodlemctwoodle

**Comment by noodlemctwoodle** [comment] 2022-06-14 11:44
@ThijsLecomte Yeah I've seen this issue I'm not at my computer at the moment, I'll update in the next couple of hours.

**Comment by noodlemctwoodle** [comment] 2022-06-14 21:36
@ThijsLecomte  | @LOMA-TheCollectiveConsulting 

I had this exact issue when I had some white space in the the Group names or a typo can also cause it. 

```
2022-05-24 16:03:07 Warning: Error received during Bearer token fetch (context).
```

Please can you check that there is no leading or trailing white space in the group names and ensure that there are no typos in `/var/www/MISP/app/Config/config.php`

![image](https://user-images.githubusercontent.com/15075388/173690779-406aa8cf-a505-49ef-8c77-76b0b03c4f98.png)

When your setting up the User do you have the  `Azure AD User` checkbox? 

![image](https://user-images.githubusercontent.com/15075388/173692484-7d5fec2f-305c-4072-9c7d-6d1b4fc49c01.png)

There are some additional configuration settings that need to be enabled to see it, the `External Authentication Key` doesnt require populating

I am currently working on a full end to end guide on setting up Azure AD Auth, I just need to update some screenshots, I can post it here if your still having trouble.

**Comment by ntnco** [comment] 2022-06-20 14:57
> Please can you check that there is no leading or trailing white space in the group names and ensure that there are no typos in `/var/www/MISP/app/Config/config.php`

I cannot speak for OP, but in my case there is no white space in the the group names and there are no typos in `/var/www/MISP/app/Config/config.php`. AAD works for users but not groups.

However, there is no Azure AD User checkbox when creating a new user.

![image](https://user-images.githubusercontent.com/28058284/174630107-c6c2ce45-cd2f-44d9-aeb8-85293d864553.png)

**Comment by LOMA-TheCollectiveConsulting** [comment] 2022-06-20 15:01
> @ThijsLecomte | @LOMA-TheCollectiveConsulting
> 
> I had this exact issue when I had some white space in the the Group names or a typo can also cause it.
> 
> ```
> 2022-05-24 16:03:07 Warning: Error received during Bearer token fetch (context).
> ```
> 
> Please can you check that there is no leading or trailing white space in the group names and ensure that there are no typos in `/var/www/MISP/app/Config/config.php`
> 
> ![image](https://user-images.githubusercontent.com/15075388/173690779-406aa8cf-a505-49ef-8c77-76b0b03c4f98.png)
> 
> When your setting up the User do you have the `Azure AD User` checkbox?
> 
> ![image](https://user-images.githubusercontent.com/15075388/173692484-7d5fec2f-305c-4072-9c7d-6d1b4fc49c01.png)
> 
> There are some additional configuration settings that need to be enabled to see it, the `External Authentication Key` doesnt require populating
> 
> I am currently working on a full end to end guide on setting up Azure AD Auth, I just need to update some screenshots, I can post it here if your still having trouble.

Sharing the link would be extremely helpful. :)

**Comment by righel** [comment] 2022-06-27 15:38
Hello,
I don't have much experience with AAD and Azure, but I followed @noodlemctwoodle [guide](https://github.com/MISP/MISP/tree/2.4/app/Plugin/AadAuth) with a fresh MISP instance installed in an Azure Ubuntu 20.04 VM and managed to get it working.

At first I had the same error message `Warning: Error received during Bearer token fetch (context).`
In my case the solution was to check the exact username that is registered in the AAD matches the one registered user in MISP, for me in MISP the user was registered as `foobar@gmail.com` but the AAD auth plugin was looking for `foobar_gmail.com#EXT#@xxxxxx.onmicrosoft.com`

You can temporarily increase the logging verbosity of this plugin by changing the frameworks logging settings to display `info` logs.

Modify: `/var/www/MISP/app/Config/bootstrap.php` by add 'info' for in the `types` array.
```php
CakeLog::config('error', array(
	'engine' => 'FileLog',
	'types' => array('info', 'warning', 'error', 'critical', 'alert', 'emergency'), 
	'file' => 'error',
));
```

EDIT: This seems to be the same issue as https://github.com/MISP/MISP/issues/7169#issuecomment-792299283

Let me know if that helps.

**Comment by ntnco** [comment] 2022-07-04 14:59
Alright, I just added `info`, but the logs don't seem to be of much help. Definitely not a duplicate of #7169 in my case.

The log below is for a single attempt to connect with group-AAD (please note there is no error when user groups are disabled). Before sharing the logs below, I adjusted to show `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` instead of actual value.

File `/var/www/MISP/app/tmp/logs/error.log`:

```
2022-07-04 10:30:18 Info: Redirect to Azure for authentication.
2022-07-04 10:30:20 Info: Fetching user data from Azure.
2022-07-04 10:30:20 Info: Fetching user group data from Azure.
2022-07-04 10:30:21 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AuthComponent::_getUser() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 698
AuthComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 301
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 129
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 683
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:21 Warning: Error received during Bearer token fetch (context).
2022-07-04 10:30:21 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AadAuthenticateAuthenticate::authenticate() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 158
AuthComponent::identify() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 772
AuthComponent::login() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 612
UsersController::login() - APP/Controller/UsersController.php, line 1177
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:21 Warning: Error received during Bearer token fetch (context).
2022-07-04 10:30:24 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AuthComponent::_getUser() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 698
AuthComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 305
AppController::_loadAuthenticationPlugins() - APP/Controller/AppController.php, line 1150
AppController::beforeFilter() - APP/Controller/AppController.php, line 233
UsersController::beforeFilter() - APP/Controller/UsersController.php, line 31
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:24 Warning: Error received during Bearer token fetch (context).
2022-07-04 10:30:24 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AuthComponent::_getUser() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 698
AuthComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 301
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 129
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 683
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:24 Warning: Error received during Bearer token fetch (context).
2022-07-04 10:30:25 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AadAuthenticateAuthenticate::authenticate() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 158
AuthComponent::identify() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 772
AuthComponent::login() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 612
UsersController::login() - APP/Controller/UsersController.php, line 1177
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:25 Warning: Error received during Bearer token fetch (context).
2022-07-04 10:30:25 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AuthComponent::_getUser() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 698
AuthComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 305
AppController::_loadAuthenticationPlugins() - APP/Controller/AppController.php, line 1150
AppController::beforeFilter() - APP/Controller/AppController.php, line 233
UsersController::beforeFilter() - APP/Controller/UsersController.php, line 31
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 682
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:25 Warning: Error received during Bearer token fetch (context).
2022-07-04 10:30:26 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AuthComponent::_getUser() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 698
AuthComponent::startup() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 301
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 129
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 244
Controller::startupProcess() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 683
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:26 Warning: Error received during Bearer token fetch (context).
2022-07-04 10:30:26 Warning: Warning (2): file_get_contents(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in [/var/www/MISP/app/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
file_get_contents - [internal], line ??
AadAuthenticateAuthenticate::_getUserAad() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 204
AadAuthenticateAuthenticate::getUser() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 143
AadAuthenticateAuthenticate::authenticate() - APP/Plugin/AadAuth/Controller/Component/Auth/AadAuthenticateAuthenticate.php, line 158
AuthComponent::identify() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 772
AuthComponent::login() - APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 612
UsersController::login() - APP/Controller/UsersController.php, line 1177
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 99

2022-07-04 10:30:26 Warning: Error received during Bearer token fetch (context).
```
There did not seem to be other relevant logs.

**Comment by MarkJaroski** [comment] 2022-07-18 18:55
For what it's worth I got this working on our setup. I started with @righel's patch, and added account creation and group enumeration. I don't think the form is good enough to submit as a pull request, and I still had to do a hacky work-around for the proxy part.

**Comment by righel** [comment] 2022-07-18 19:04
Feel free to open a pull request when you consider it's ready @MarkJaroski. We can take a look, suggest changes/or refactor it if necessary.

**Comment by LOMA-TheCollectiveConsulting** [comment] 2022-07-19 07:18
Hi all, 

I also got it to work with the help of @righel. 
In my case it were the spaces in the groups that were defined here: 
![image](https://user-images.githubusercontent.com/65909131/179688680-3bc85151-1daf-49c2-9b42-b7d592a039ac.png)

Even dough I copied and pasted them from the the Azure AD portal when creating the groups. 
It seems like spaces in the group name were the issue so I replaced them all with _

**Comment by MarkJaroski** [comment] 2022-07-19 19:16
See pull request #8501 

I have absolutely no idea if the enum structure is right. I'll confess that in our running instance it's just magic numbers.

Likewise, I also presume that haven't got user creation quite right, but we need it, so it's in there. I mostly borrowed it from one of the other AuthN plugins.

**Closed as completed** 2022-07-20 05:48 UTC
Labels: support

**Comment by mdhusseini** [comment] 2023-07-26 02:33
@righel Was there ever a link that is shared to enable the "Azure AD User" checkbox?
