### ISSUE TITLE
Column 'org_id' cannot be null

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#814] opened 2016-01-06 10:12 UTC
I see in the log resque-2016-01-05.log following error message:

[2016-01-05 12:00:04] main.INFO: got {"queue":"cache","id":"802f30d4698ad819e3b51a1147d3f386","class":"EventShell","args":[["enqueueCaching",1451991600,false,false]]} {"type":"got","args":"[object] (Resque_Job: {\"queue\":\"cache\",\"id\":\"802f30d4698ad819e3b51a1147d3f386\",\"class\":\"EventShell\",\"args\":[[\"enqueueCaching\",1451991600,false,false]]})","worker":"misp.my.org:32570"} []
[2016-01-05 12:00:04] main.INFO: Processing ID:802f30d4698ad819e3b51a1147d3f386 in cache {"type":"process","worker":"misp.my.org:32570","job_id":"802f30d4698ad819e3b51a1147d3f386"} []
[2016-01-05 12:00:04] main.ERROR: {"queue":"cache","id":"802f30d4698ad819e3b51a1147d3f386","class":"EventShell","args":[["enqueueCaching",1451991600,false,false]]} failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null {"type":"fail","log":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null","job_id":"802f30d4698ad819e3b51a1147d3f386","time":111,"worker":"misp.my.org:32570"} []

Sorry, I don't have more information

**Comment by adulau** [comment] 2016-01-10 21:48
Thanks for the report. Is this one solved with the recent updates?

**Comment by h122015** [comment] 2016-01-14 10:59
I think it is. The last time that error message poped up in my logs was:

resque-2016-01-10.log:[2016-01-10 12:00:03] main.ERROR: {"queue":"cache","id":"b70fe508299e445210da16b3f3caaa4c","class":"EventShell","args":[{"0":"enqueueCaching","1":1452423600,"2":false,"3":false,"s_time":1452337205}]} failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null {"type":"fail","log":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null","job_id":"b70fe508299e445210da16b3f3caaa4c","time":100,"worker":"misp.my.org:32570"} []

**Comment by RichieB2B** [comment] 2016-01-14 15:18
I just did the upgrade to 2.4.7 and pulling from misppriv.circl.lu gives me the same type of error:
```
2016-01-14 15:13:34 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org' cannot be null
Request URL: /servers/pull/2/full
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('INSERT INTO `mi...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1024): DboSource->execute('INSERT INTO `mi...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1933): DboSource->create(Object(Job), Array, Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1751): Model->_doSave(Array, Array)
#5 /var/www/MISP/app/Controller/ServersController.php(468): Model->save(Array)
#6 [internal function]: ServersController->pull('2', 'full')
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#10 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
```

**Comment by iglocska** [comment] 2016-01-14 15:22
Ah, I think I know what's going on. The upgrade script doesn't actually
remove the old org field if it's still there - at one point it changed to a
non nullable field which gives you that error and it explains why I can't
reproduce it.

If you could remove the "org" field from the table for now that would solve
it for now, I'll look into adding a cleanup script that checks if all data
has been successfully migrated to the new system and then removes the field
itself.

Sorry for the inconvenience!

**Comment by RichieB2B** [comment] 2016-01-15 15:40
#604 seems to be related.
I was able to fix this with the following SQL statements:
```
ALTER TABLE events DROP COLUMN org;
ALTER TABLE jobs DROP COLUMN org;
ALTER TABLE servers DROP COLUMN org;
ALTER TABLE shadow_attributes DROP COLUMN org;
ALTER TABLE threads DROP COLUMN org;
ALTER TABLE users DROP COLUMN org;
ALTER TABLE correlations DROP COLUMN org;
```
and after that clearing the cached models:
```
find /var/www/MISP/app/tmp/cache/ -type f -not -name 'empty' -delete
```

**Comment by pierrempr** [comment] 2016-03-18 12:24
Hi, 

I have the same issue when I tried to do a pull : 

`main.ERROR: {"queue":"default","id":"8eec9fc206623e330101b8a27b07dde7","class":"ServerShell","args":[["pull","1","1","full","1887"]]} 
failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'org_id' cannot be null {"type":"fail","log":"SQLSTATE[23000]: 
Integrity constraint violation: 1048 Column 'org_id' cannot be null","job_id":"8eec9fc206623e330101b8a27b07dde7","time":79143,
"worker":"xxxxxxxx:15733"} []`

The MISP is in v2.4.27 on a centos7. 

To compare, I also tried on a debian with a instance of MISP in version 2.4.23, and on this instance I don't have the issue.. The pulling is going normaly.

Is it a matter of possible differences between MariaDB and MySql ?

**Comment by Rafiot** [comment] 2016-04-05 10:06
This should have been fixed with https://github.com/MISP/MISP/commit/7de5ebe902d282ffd133075118645984f6480afa . We will close the issue. Don't hesitate to reopen the case if the issue persists.

**Closed by Rafiot** 2016-04-05 10:06 UTC
Labels: support
