### ISSUE TITLE
STIX import module not working

### ISSUE THREAD

**Issue by TostyT** [MISP/MISP#3534] opened 2018-08-07 11:04 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| PHP version               | 7.1
| MISP version / git hash   | v2.4.94 (b7233957b61e6014cfde49dd1e872b89ea5bcfad) 

### Expected behavior
Import STIX file with success. 

### Actual behavior
MISP shows the following error when I try to import a .xml STIX file in the GUI:

Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool.

### Logs, screenshots, configuration dump, ...
Looking at exec-errors.log I can see the following:

`root@misp:/var/www/MISP/app/files/scripts# cat /var/www/MISP/app/tmp/logs/exec-errors.log`
`/usr/local/lib/python3.6/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)`
`/usr/local/lib/python3.6/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)`
`/usr/local/lib/python3.6/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)`
`/usr/local/lib/python3.6/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'STIXPackage' object.
  warnings.warn(msg)`
`Traceback (most recent call last):`
  `File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1167, in <module>
    main(sys.argv)`
  `File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1161, in main
    stix_parser.load(args)`
  `File "/var/www/MISP/app/files/scripts/stix2misp.py", line 70, in load
    if fromMISP:`
`NameError: name 'fromMISP' is not defined`

It has something to do with the last statement I presume? NameError: name 'fromMISP' is not defined

Also, I've updated MISP to the latest version and now the CYBOX library is not in sync anymore. In the previous MISP version (when the CYBOX library was in sync) the STIX import function however also didn't work and resulted in the same error message. 

> Current libraries status…Some versions should be updated:
STIX library version…OK
CYBOX library version…Incorrect CyBox version installed, found 2.1.0.18.dev0, expecting 2.1.0.17
MIXBOX library version…OK
MAEC library version…OK
PYMISP library version…OK

**Comment by chrisr3d** [comment] 2018-08-07 12:56
Yes, I was cleaning up code in different scripts, and I forgot to push this one
It should be OK now
Sorry for the inconvenience

**Comment by TostyT** [comment] 2018-08-07 13:32
Downloaded the new script but still get a error message. Any thoughts? 

`  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 166, in parse_journal_entries
    entry_type, entry_value = journal_entry.split(': ')
ValueError: too many values to unpack (expected 2)`

**Comment by chrisr3d** [comment] 2018-08-07 15:35
Do you have any data to share here as an example of what you are trying to import ?
Is it coming from a MISP export of an external STIX file ?
It is a special case I never had before (because I never saw yet journal entries on files coming from external sources) so it would be cool if I could adjust the parsing for this part

Otherwise, I quick fixed it but don't hesitate if you have anything else failing here

**Comment by TostyT** [comment] 2018-08-14 11:26
The code fix did the trick. I'm able to import STIX file now, both from a MISP export and an external STIX file.

**Comment by SteveClement** [comment] 2018-08-15 09:13
@chrisr3d can you close this if done.

**Closed as completed** 2018-08-18 00:10 UTC
Labels: T: bug, confirmed

**Comment by AntoninHL** [comment] 2018-09-09 08:44
Hi,
I have the same issue...
MISP: v2.4.95
Ubuntu: 16.04
==> Incorrect CyBox version installed, found 2.1.0.18.dev0, expecting 2.1.0.17

How did you fixed it?

Thx
A./

**Comment by chrisr3d** [comment] 2018-09-09 10:19
There is no big changes between those two versions, I doubt it is the origin of the problem.
Do you have any sample data to share so I can try to reproduce the issue on my own instance ?

**Comment by AntoninHL** [comment] 2018-09-09 11:03
In fact, I just want to understant how to be sure that my MISP install is OK.
Because I have this Red Warning in Diagnostic part: Incorrect CyBox version installed, found 2.1.0.18.dev0, expecting 2.1.0.17

Do you have a workaround to have OK everywhere?

**Comment by chrisr3d** [comment] 2018-09-11 14:51
We do not have any script doing this automatically.
However, you can find instructions in the file [UPDATE.txt](https://github.com/MISP/MISP/blob/2.4/INSTALL/UPDATE.txt)
