### ISSUE TITLE
Add system to purge Cake_sessions table that keeps on growing infinitely

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#650] opened 2015-09-11 12:42 UTC
It is on a busy instance but not _that_ busy.

I think it might be a problem with session expiration configuration.

```
mysql> SELECT table_name AS "Tables", round(((data_length +
index_length) / 1024 / 1024), 2) "Size in MB" FROM
information_schema.TABLES WHERE table_schema = "misp" ORDER BY
(data_length + index_length) DESC;
+-----------------------------+------------+
| Tables                      | Size in MB |
+-----------------------------+------------+
| cake_sessions               |    4573.00 |
+-----------------------------+------------+


With more than 3million rows:
mysql> select count(id) from cake_sessions;
+-----------+
| count(id) |
+-----------+
|   3046820 |
+-----------+
```

**Comment by iglocska** [comment] 2015-09-11 12:43
Yeah, something is definitely wrong there...

**Comment by iglocska** [comment] 2015-09-11 12:58
OK, just looked into this, so this is what happens: 

The garbage collection of the session table depends on the php.ini settings session.gc_probablity and session.gc_divisor. Basically, each time you load a page there is a gc_probability/gc_divisor chance that garbace collection is triggered - make sure that this is set to some reasonable number (like 1 / 1000 for 0.1% chance). That should allow cake to actually trigger garbage collections. 

Just tested it and this should resolve it, but this also needs to be documented or even better, will check if this could be overriden from within the application as others will be affected too.

**Comment by elhoim** [comment] 2015-09-11 13:13
Maybe [via htaccess](http://davidwalsh.name/php-values-htaccess)?

**Comment by elhoim** [comment] 2015-09-11 14:17
For documentation purposes, based on [this blog post](http://www.laurencegellert.com/2012/08/php-sessions-not-being-deleted-on-ubuntu-server/) Ubuntu and Debian distribution have set gc_probability to 0 by default, so that garbage collection does not happen when trying to serve pages.
Instead it is trying to do via a cronjob calling */usr/lib/php5/maxlifetime*

This will probably be fixed either via an override of the php.ini value via htaccess file or via reoccuring task to clean-up the table.

**Comment by iglocska** [comment] 2015-09-17 13:46
Just a heads-up on this, there is now a tool in the diagnostics page that checks the number of expired sessions in the session table and allows the site admins to remove all expired sessions directly from that page. It's not a final fix, but something that should go a long way for now.

**Comment by iglocska** [comment] 2015-09-21 18:06
I'll close this for now as there is a solution, might reopen it in the future when we look into automating administrative tasks.

**Closed by iglocska** 2015-09-21 18:06 UTC
Labels: enhancement

**Comment by 59e5aaf4** [comment] 2017-10-17 07:31
We had those MISP downtimes every day starting at midnight, probably caused by some `mysqldump`. It started being some 10 minutes minor downtimes, and it's now a 3.5h unacceptable downtime.

The host is a pretty standard Ubuntu 16 x64 with apache2 and php7.

```
# uname -srvmpio
Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# head -n 2 /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
# cat /var/www/MISP/VERSION.json
{"major":2, "minor":4, "hotfix":49}
# dpkg -l | grep -E 'ii  (apache2|php|mysql-server) '
ii  apache2                             2.4.18-2ubuntu3.1                   amd64        Apache HTTP Server
ii  mysql-server                        5.7.17-0ubuntu0.16.04.1             all          MySQL database server (metapackage depending on the latest version)
ii  php                                 1:7.0+35ubuntu6                     all          server-side, HTML-embedded scripting language (default)

```

We observed a very high number of processes on the host in the morning, all were mysql threads on requests : 

- **1** select * from misp.cake_sessions (caused by mysqldump)
- **N-1** insertion tentatives of new web sessions in the `misp.cake_sessions` table (caused by automated HTTP requests)

There is a **34GB misp.cake_session table**, which might not be what we want.
```
mysql> SELECT table_schema as `Database`, table_name AS `Table`, round(((data_length + index_length)/1024/1024),2) `Size in MB` FROM information_schema.TABLES ORDER BY (data_length + index_length) DESC limit 2;
+----------+---------------+------------+
| Database | Table         | Size in MB |
+----------+---------------+------------+
| misp     | cake_sessions |   34198.02 |
| misp     | logs          |      97.61 |
+----------+---------------+------------+
2 rows in set (0.05 sec)
```

Looking at your comments, I saw that Ubuntu did put 0 in `php.ini` :
```
# find /etc -type f -name php.ini -exec grep '^session.gc_probability' {} \; | sort | uniq -c
      6 session.gc_probability = 0
```

I killed the msysql export task (show processlist ; kill $id), and removed all the session data :
```
mysql> TRUNCATE TABLE cake_sessions;
Query OK, 0 rows affected (1 min 6.94 sec)
```
I'm not sure if I should setup a crontab pointing to `/usr/lib/php/sessionclean` or modify the gc_probability setting somewhere.

**Comment by adulau** [comment] 2017-10-17 08:02
We recommend to move session to Redis:

- https://www.digitalocean.com/community/tutorials/how-to-set-up-a-redis-server-as-a-session-handler-for-php-on-ubuntu-14-04

By the way, you should upgrade to the latest version where many fixes were introduced for session handling and alike.
