### ISSUE TITLE
Bug: PHP error affects NIDs Export

### ISSUE THREAD

**Issue by Silberweich** [MISP/MISP#9514] opened 2024-01-26 04:39 UTC
### Actual behavior

After Attempting to generate Suricata rules export on page "Events Action > Export", The export failed. Checking "Administration > Jobs" page, it reports that the cache_suricata job failed with this error. 
```
Notice Error: Undefined variable: tmpMessage in [/var/www/MISP/app/Lib/Export/NidsExport.php, line 718]
```
**There is no rules file generated after such error.** 

### Expected behavior

On page "Events Action > Export" for Suricata, clicking "Generate" successfully runs. 

### Steps to reproduce

The MISP instance is run on Docker, see this repository: [MISP Docker](https://github.com/MISP/misp-docker). All default compose configuration.
The provided OS information and PHP version is of the Docker Container, not host device.

**Steps**:
1. On page "Events Action > Export", click generate export for Suricata. The Progress column notes "Adding".
2. Wait for a very long time, the computer will froze for up to 5 minutes.
3. Check "Administration > Jobs" to see running jobs, The status will note "Failed". 

### Version

2.4.183

### Operating System

Debian

### Operating System version

6.1.69-1

### PHP version

7.4.33

### Browser

Firefox

### Browser version

115.6.0esr

### Relevant log output

```shell
Error at "Administration > Jobs"

Error: Notice Error: Undefined variable: tmpMessage in [/var/www/MISP/app/Lib/Export/NidsExport.php, line 718]

Error at debug.log

2024-01-26 10:30:27 Notice: Notice (8): Undefined variable: tmpMessage in [/var/www/MISP/app/Lib/Export/NidsExport.php, line 718]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
NidsExport::snortRule() - APP/Lib/Export/NidsExport.php, line 718
NidsExport::export() - APP/Lib/Export/NidsExport.php, line 235
NidsSuricataExport::export() - APP/Lib/Export/NidsSuricataExport.php, line 11
NidsExport::__convertFromEventFormat() - APP/Lib/Export/NidsExport.php, line 64
NidsExport::handler() - APP/Lib/Export/NidsExport.php, line 39
Event::restSearch() - APP/Model/Event.php, line 7373
AppController::restSearch() - APP/Controller/AppController.php, line 1347
EventsController::nids() - APP/Controller/EventsController.php, line 3552
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 101
```

### Extra attachments

![Screenshot_20240126_190020](https://github.com/MISP/MISP/assets/69336541/35f240fe-7bdb-4872-ab75-a6dfbc7dea1f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment] 2024-01-26 08:48
Duplicate of 9515

**Closed as completed by adulau** 2024-01-26 08:48 UTC
Labels: needs triage
