### ISSUE TITLE
"Deleted flag" for events/attributes

### ISSUE THREAD

**Issue by thomai** [MISP/MISP#659] opened 2015-09-16 08:09 UTC
As discussed with @iglocska there is a new feature request: Synchronizing the delition of events/attributes should be possible by adding a "deleted" flag in both models.

If this flag is set, the event/attribute entry in the user interface should not be clickable.

(probably this would be useful for tags too)

**Comment by elhoim** [comment] 2016-02-12 11:25
Just realized my #698 is a duplicate of this one.

**Comment by adulau** [comment] 2017-02-01 20:37
Deleted attributes has been implemented. Feel free to reopen if you think that is not the case.

**Closed by adulau** 2017-02-01 20:37 UTC
Labels: automation, datamodel enhancement
