### ISSUE TITLE
Bug: References between Objects no longer work

### ISSUE THREAD

**Issue by lazydaemon** [MISP/MISP#9787] opened 2024-06-18 15:36 UTC
### Actual behavior

After upgrading MISP from v2.4.177 to v2.4.193 the reference link between objects does no longer work. I can still see the references but clicking on one reference will not lead me to the referenced object.

### Expected behavior

Clicking on a reference within an object should lead me to the referenced object.
![MISP_Object_Ref_broken](https://github.com/MISP/MISP/assets/3420941/ee18c59d-1d75-4529-a216-a9d9e9175807)

### Steps to reproduce

Create two objects and reference one to the other. Then click on the reference to see that nothing happens.

### Version

2.4.193

### Operating System

Ubuntu

### Operating System version

20.04.6

### PHP version

7.4.3

### Browser

Every Browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wachizungu** [comment] 2024-06-20 09:23
Hi,

I'm not really sure what you expect it to do in this scenario. The other object is on the same page so it just sets the focus to it, because they are both so close to each other it just looks like not much happens.

Can you please try adding a list of attributes so the two referenced attributes/objects are on separate pages, or far enough from each other that your browser should scroll up/down, and then test again? For me it correctly jumps to the referenced attribute / object as expected (2.4.193).

**Comment by lazydaemon** [comment] 2024-06-20 09:41
Hi, thanks for your quick answer. I tried and the browser is not scrolling down to the object. 
![MISP_Object_Ref_broken4](https://github.com/MISP/MISP/assets/3420941/0f4a9137-b97c-49a3-ab74-9c1a7ed0d4bf)

**Comment by Wachizungu** [comment] 2024-06-20 10:18
Strange,

Anything blocking javascript execution by any chance (I know you said this appeared after update of MISP but okay)?
Could you have a look at your browser console / web developer tools to see if there's any related error?

And perhaps check /js/misp.js is fetched correctly (http 200 in network tab for that file / uri).

**Comment by lazydaemon** [comment] 2024-06-20 11:10
Yes, it's broken after I updated to the latest version. The version before (v2.4.177) worked fine. Actually I don't think it's my client. Several people from my team with different setups (Linux, Win, macOS, different browsers etc.) all telling the same. I just tried it again in a completely clean Windows 11 VM and see the same behaviour. Inside the VM, I looked into the network tab and for me, everything looks ok. Also no errors or messages in the console.

<img width="768" alt="Screenshot 2024-06-20 at 13 05 28" src="https://github.com/MISP/MISP/assets/3420941/c527dd64-27c4-4553-ac81-2f80b664d5c3">

**Comment by lazydaemon** [comment] 2024-06-20 11:43
When I reference an attribute from an object, it works fine. Only references from one object to another object do not seem to work.

**Comment by Wachizungu** [comment] 2024-06-20 12:50
The annoying thing is that I can't reproduce the issue on the same version :(. It works for me with firefox and edge on MISP 2.4.193 and I don't really see anything wrong in the related code.
If you're handy with javascript debugging you can put a breakpoint in pivotObjectReferences misp.js function and have a look after clicking the link. I guess it's going wrong somewhere in focusObjectByUuid but no idea why.

Also:
Any chance you could verify the update went successfully / check output of git status in /var/www/MISP?
Check <your_misp_url>/servers/updateProgress
And logs in /var/www/MISP/app/tmp/logs
If you could add the commit version you are on here as well, that could help.

I think after that I can't help much more myself, hope someone else picks it up when they can.

**Comment by lazydaemon** [comment] 2024-06-20 13:40
I played around within the Debugger and for whatever reason, the uuid cannot be found in ``focusObjectByUuid(uuid)``. I just wanted to report that and will investigate further.

**Comment by lazydaemon** [comment] 2024-06-20 19:27
**Disclaimer**: I'm not a JavaScript Expert

I debugged the JS and I think, I've found something.

If `trId` starts with `Attribute`, the following `var objectUuid = $('.uuid', this).text().trim();` (Line 3783) works fine and the two valid uuid will be compared in line 3784.
<img width="1303" alt="Screenshot 2024-06-20 at 21 16 43" src="https://github.com/MISP/MISP/assets/3420941/f6bd91a6-8493-432c-9581-54c599a89f33">



If `trId` starts with `Object`, something is messed up and `objectUuid` never looks like a valid uuid so the check in Line 3784 will always fail. I have no idea why this works for you.

<img width="1564" alt="Screenshot 2024-06-20 at 21 17 32" src="https://github.com/MISP/MISP/assets/3420941/85c1d575-dc59-4c86-bb85-497a88c6add7">

As I said, referencing an attribute works fine as I could also validate inside the debugger but referencing objects is broken because line 3783 does strange things.

**Comment by iglocska** [comment] 2024-06-21 05:30
That indeed looks like a bug, there has been a change to the object's html code when the collapsing was introduced, so it's probably a regression there. Will have a look today.

**Comment by iglocska** [comment] 2024-06-21 07:17
Pushed a fix to develop, it will be included in the upcoming release, thanks for all the debugging effort!

**Comment by Wachizungu** [comment] 2024-06-21 07:54
Thx!

I'm just a bit worried this change will cover up another issue though (either with MISP, the instance or both).
text() shouldn't take what is inside the <script> tags? I'm worried it's somehow possible to get this html messed up. 
The content there is coming from https://github.com/MISP/MISP/blob/2.4/app/View/Elements/genericElements/Analyst_data/thread.ctp I believe?

Any chance you could post entire content of one of the object rows? For me it looks like this:

![image](https://github.com/MISP/MISP/assets/9868873/9eeea98b-33f1-4b76-8177-6e1ac406e5eb)

**Comment by lazydaemon** [comment] 2024-06-21 09:41
Looks pretty much like yours. 

<img width="1111" alt="Screenshot 2024-06-21 at 11 37 44" src="https://github.com/MISP/MISP/assets/3420941/b2da58d0-1669-4241-8a82-48094a50b4b3">

The problem is that text() returns the uuid and all the script content (see Screenshot above).

<img width="1254" alt="Screenshot 2024-06-21 at 11 39 34" src="https://github.com/MISP/MISP/assets/3420941/a64bf038-a3df-44cb-85ea-80defb9882cf">

**Comment by Wachizungu** [comment] 2024-06-21 10:43
Ha, my bad!
For my test the 2nd object was on a different page, and that seemed to work because then it still loaded that other page somehow and I didn't have much on there so it looked good, facepalm. Was wrong about text(), cheers!

**Closed as completed** 2024-06-21 12:15 UTC
Labels: needs triage
