### ISSUE TITLE
Warning lists ignored (POST ->events/freeTextImport/<event_id> )

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#4881] opened 2019-07-16 13:33 UTC
(the appropriate Warniglist is enabled)

Request:
```json
{"value": "8.8.8.8 foo@bar.de", "adhereToWarninglists": true, "distribution": 2}
```

Response:
```
[{'to_ids': True, 'comment': False, 'value': '8.8.8.8', 'type': 'ip-dst', 'category': 'Network activity', 'distribution': 2, 'event_id': '2669'}, {'to_ids': True, 'value': 'foo@bar.de', 'type': 'email-src', 'category': 'Payload delivery', 'distribution': 2, 'event_id': '2669'}]
```

**Comment by Rafiot** [comment] 2019-07-31 15:48
Query: 

```json
{
  "value": "8.8.8.8 foo@bar.de",
  "adhereToWarninglists": true,
  "distribution": 2
}
```

**Comment by iglocska** [comment] 2019-08-05 14:15
Cannot reproduce.

**Comment by iglocska** [comment] 2019-08-05 14:16
I will close it for now, tested with and without background processing. If you use background processing it indeed will show up in the response - but that's because we just pass the raw input back before the processing. Warninglist violating entries will be stripped.

**Closed as completed by iglocska** 2019-08-05 14:16 UTC
Labels: T: bug, from:testcases

**Comment by Rafiot** [comment] 2019-08-05 14:32
Yeah, nvm, it's fine...
