### ISSUE TITLE
MISP attribute url normalization/validation

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3602] opened 2018-08-29 21:09 UTC
Is there any way in MISP or a module, etc. to normalize/validate URLs as they are ingested as `url` attributes into an event?

A quick search revealed these (I imagine there are more):
- https://github.com/MISP/MISP/issues/2286
- https://github.com/MISP/MISP/issues/525

Thanks.

**Comment by SteveClement** [comment] 2018-09-03 13:38
Duplicate of #2286 and #525 closing.

**Closed as completed by SteveClement** 2018-09-03 13:38 UTC
