### ISSUE TITLE
Users get error 0 when they attempt to sync barncat MISP to their own local MISP

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#2098] opened 2017-03-31 16:26 UTC
A few users have reported when they try to sync their own MISP instances with Barncat, they get error code 0.  Want to make sure they can only pull events and not push with whatever resolution there is.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | 
| PHP version               | 7.0
| MISP version / git hash   | 2.4.70
| Browser                   | If applicable

**Comment by lolnate** [comment] 2017-03-31 16:48
As a user, I have added the instance and the test connection works properly. In the jobs section of my MISP instance it says "Error: got response code 0". I can't find what this means, and I don't see anything in any of the logs on my server. A connection test to the remote server works fine:

Local version: 2.4.70
Remote version: 2.4.70
Status: OK
Compatiblity: Compatible
POST test: Received sent package

**Comment by BurntToast-DFIR** [comment] 2017-04-13 08:28
I also receive this error.  Exactly the same as that shown above.

**Comment by iglocska** [comment] 2017-04-13 09:00
Sorry for all the delays, looking into it now.

**Comment by iglocska** [comment] 2017-04-13 19:01
So after looking into this: This is caused by a low timeout, at least on the Barncat instance (seems to be set to 30 seconds).

The problem is that the sync starts with a negotiation phase where the full event index containing all event metadata is fetched to decide on what actually gets synchronised. This, considering the amount of data fetched (all event fields, creator and orwner organisation, tags, galaxies) whilst dealing with 200k+ events is actually quite a massive fetch and serialisation task. 

So in order to resolve this, I pushed a new patch that includes a parameter called "minimal" for the event index. This makes MISP only fetch the event id, uuid, timestamp and published state, meaning that the data amount and fetch workload is heavily reduced. The synchronisation mechanism now tries to request the minimal version of the index.

Please make sure that you update your instances with this new patch and tell your users to do the same and the issue should be resolved. Additionally, make sure you raise the timeout timer to something a tad higher. Let me know if this has resolved it!

**Comment by bambenek** [comment] 2017-04-13 19:03
Where is that timeout defined?  php.ini?

**Comment by iglocska** [comment] 2017-04-13 19:04
Yup!

**Comment by iglocska** [comment] 2017-04-13 19:05
I should also work on the error message "code 0" is about as useful as a solar powered flashlight.

**Comment by bambenek** [comment] 2017-04-13 19:22
Which precise variable, i see nothing at 30 seconds in the config

**Comment by iglocska** [comment] 2017-04-13 19:23
Should be 

```
max_execution_time
```

**Comment by iglocska** [comment] 2017-04-13 19:32
Argh, not my day. The above patch wasn't working quite as intended, could you git pull again? Sorry about that.

**Comment by bambenek** [comment] 2017-04-13 19:34
done

**Comment by iglocska** [comment] 2017-04-13 20:45
Just tested and I can now pull from you, yay! 

Fixed a few more edge-case issues, think we'll do another tagged bugfix-release tomorrow. This has been productive, thanks for the help!

**Comment by BurntToast-DFIR** [comment] 2017-04-13 20:46
I'll try on Monday. Thanks for the swift resolution.

**Comment by bambenek** [comment] 2017-04-13 20:47
No worries... I'll try to make it over there at some point where we can
just do a bunch of this stuff in the same room and call it a beer and
hackathon at some point considering I'm giving you all the edge cases :)

**Comment by iglocska** [comment] 2017-04-13 21:07
That would be fantastic! Your use-case is super interesting and the best
real-life stress test we've had so far. Really appreciate all the work you
do!

**Comment by adulau** [comment] 2017-04-14 06:53
@bambenek there is one hackathon foreseen (and you should come over ;-) https://hackathon.hack.lu/ with MISP project and many others like TheHive.

**Comment by bambenek** [comment] 2017-04-14 15:30
That's a little too soon for me to leave the country, $newbaby won't
even be 2 months old yet.

**Comment by iglocska** [comment] 2017-04-14 15:37
The only acceptable excuse ;) 

Massive congratulations!

**Comment by bambenek** [comment] 2017-04-14 15:39
Thanks... I'll get over there soon enough :)

**Comment by adulau** [comment] 2017-04-14 15:48
@bambenek If you come to Luxembourg at some point, feel free to stop at our office ;-)

**Comment by bambenek** [comment] 2017-04-14 22:16
It's on my agenda, just gotta find an excuse to get there... and I'm
good at finding excuses :)

**Comment by BurntToast-DFIR** [comment] 2017-04-26 12:59
Fixed for me by upgrading to 2.4.72.  Thanks guys.  You are, as ever, freaking awesome.

**Comment by iglocska** [comment] 2017-04-26 13:37
Excellent news! B-)

**Comment by adulau** [comment] 2017-04-26 13:42
Then we will close the issue as it seems resolved ;-) Feel free to reopen or create a new issue if there another related issue.

**Closed as completed by adulau** 2017-04-26 13:42 UTC
Labels: T: potential bug
