### ISSUE TITLE
Edit User = Error: An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by zoni171** [MISP/MISP#3708] opened 2018-09-24 14:17 UTC
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | support
| OS version (server)       | ubuntu
| OS version (client)       | Ubuntu, ...
| PHP version               | 7.2
| MISP version / git hash   | v2.4.95 (9d83c840ec92cd8a04b8f28d82f7771b26c7d356) 
| Browser                   | Firefox 62.0 (64-bit)

### Expected behavior
Being able to edit a user.

### Actual behavior
When I try to edit a user I get the Error: An Internal Error Has Occurred. I can list Users and Add them if needed with no issues.

**Comment by iglocska** [comment] 2018-09-24 20:51
I could not reproduce this. Could you check the error logs after triggering the internal error?

/var/www/MISP/app/tmp/logs/error.log

**Comment by zoni171** [comment] 2018-09-24 22:18
2018-09-25 00:17:49 Error: Fatal Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php, line 284]
2018-09-25 00:17:49 Error: [InternalErrorException] Internal Server Error
Request URL: /admin/users/edit/1
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Allowed memory ...', '/var/www/MISP/a...', 284)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Allowed memory ...', '/var/www/MISP/a...', 284, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}

**Comment by iglocska** [comment] 2018-09-25 07:03
Is it for any user or a specific one? Are you a site admin or an org admin?

**Comment by zoni171** [comment] 2018-09-26 14:08
Sorry for the delay answering.
Looks like i can do edit everyone and it only gives me the internal error on me. I am Admin. I am the original  and 1st account created. I edited and put my own email/info.

**Comment by SteveClement** [comment] 2019-02-04 05:42
Closing due to non-activity.

Feel free to re-open with updated content.

**Closed as completed by SteveClement** 2019-02-04 05:42 UTC
