### ISSUE TITLE
Suggestions on debugging GnuPG

### ISSUE THREAD

**Issue by mgeorgy** [MISP/MISP#413] opened 2015-02-24 21:34 UTC
Does MISP log problems associated with GnuPG?  Or is their a way to diagnose GnuPG issues?

My server diagnostics shows:
GnuPG installation and settings....FAIL: encrypt failed

No idea how to find the reason for the failure.

Thank you.

**Comment by dray0n** [comment] 2015-03-02 00:57
I am having difficulty as well.  I have double checked the install and everything appears to be in line.  Also validated permissions on my folders and they appear correct.

Looking for any guidance.

Ubuntu 14.04.

**Comment by iglocska** [comment] 2015-03-02 15:15
I'll look into adding a way for getting the debug output on request in the
tool. In the meanwhile, you can get the crypt_gpg debug by altering this
line:

$gpg = new Crypt_GPG(array('homedir' => Configure::read('GnuPG.homedir')));

in /var/www/MISP/app/Controller/ServersController.php (line 375) to the
following:

$gpg = new Crypt_GPG(array('homedir' => Configure::read('GnuPG.homedir'),
'debug' => true));

Look for the first line starting with "ERROR:", it should tell you what
went wrong.

Also, I have just been debugging an issue with GPG for the past few hours
that was frustrating (on CentOS, it looks like an update they pushed
altered its behaviour), let me know if the issue mentions S.gpg-agent.

**Comment by mgeorgy** [comment] 2015-03-02 16:07
Thank you.  The debug logs were useful is identifying the issue.  My problem was not associated with the gpg-agent.

**Comment by iglocska** [comment] 2015-03-02 16:30
Glad it worked out!

dray0n, let me know if you get stuck.

**Comment by dray0n** [comment] 2015-03-04 09:21
Worked like a charm.

I am embarrassed to say I was providing the incorrect pass phrase....... You know, that field that I "verified" multiple times. DOH!

**Comment by iglocska** [comment] 2015-03-04 09:26
Hehe it happens :)

**Comment by virtugon** [comment] 2015-04-08 10:32
>Also, I have just been debugging an issue with GPG for the past few hours
>that was frustrating (on CentOS, it looks like an update they pushed
>altered its behaviour), let me know if the issue mentions S.gpg-agent.

Unfortunately I still experience this problem on CentOS. These is the errors I get:

    ERROR: can't connect to `/var/www/MISP/.gnupg/S.gpg-agent': No such file or directory
    ERROR: gpg-agent[9006]: can't create directory `/var/www/.gnupg': Permission denied

For some reason this command want to use the default homedir of the Apache user:
`/usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --armor --local-user '<SNIP>' --homedir '/var/www/MISP/.gnupg' --clearsign`

Does anyone has any experience fixing this? I can't seem to work out the behaviour on CentOS... :(

**Comment by RichieB2B** [comment] 2015-04-08 12:37
I remember getting the same error message. I solved it with a symlink:
```
ln -s /var/www/MISP/.gnupg /var/www
```

**Comment by virtugon** [comment] 2015-04-16 08:26
That trick worked. I can now start the gpg-agent. However, now I get an error that's even more generic and mysterious to me. After a lot of experimentation I still can't seem to figure out what's going wrong now.

> bash-4.1$ /usr/bin/gpg --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --armor --local-user '[SNIP]' --homedir '/var/www/MISP/.gnupg' --clearsign
> gpg: cancelled by user
> gpg: skipped "[SNIP]": General error
> gpg: [stdin]: clearsign failed: General error

Although it says canceled by user, the user (me) did no such thing :)
The key is alright and the passphrase in the config should be working fine, I've confirmed that manually.
The debug option can also verify the right key exists, but it 'crashes' every time the passphrase comes into play.

Maybe I'm overlooking the obvious here. Hopefully somebody can give me a hint in the right direction.

**Comment by RichieB2B** [comment] 2015-04-16 10:15
Since gpg 2 the use of gpg-agent for passphrase entry mandatory (they removed the --no-use-agent option). So unless you entered your passphrase into gpg-agent you did "cancel" the gpg signing (because you never supplied the passphrase).

Of course using gpg-agent with interactive pinentry is not very useful in a MISP server scenario. I wrote a custom pinentry script to supply the password to gpg-agent when needed, but decided that putting the passphrase inside a script is worse than using no passphrase on the keyring at all.

See also the comment on http://php.net/manual/en/function.gnupg-addsignkey.php

**Comment by elhoim** [comment] 2015-05-08 07:44
From what I understand I can close this ticket, correct?

**Comment by Rafiot** [comment] 2015-09-15 15:05
I guess so.

**Comment by iglocska** [comment] 2015-11-06 08:27
Just a heads-up on this issue, Crypt_GPG 1.4.0 is finally out of beta after 2 years, so now there's a stable build that will work with RHEL passphrases without any tricks. http://pear.php.net/package/Crypt_GPG/download/1.4.0/

**Closed** 2015-12-15 16:34 UTC
Labels: potential-bug
