### ISSUE TITLE
gpg: agent_genkey failed: Permission denied 

### ISSUE THREAD

**Issue by zero3228** [MISP/MISP#3702] opened 2018-09-20 10:55 UTC
Hello, I've been trying to fix this error for many days, but there is no any solutions that work.

![image](https://user-images.githubusercontent.com/13799256/45813912-24357b80-bcfe-11e8-8b84-805bb3b88c33.png)

If anybody can solve this, please share your solutions.

Thank you.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by adulau** [comment] 2018-09-21 06:35
Maybe you want to set the tty ownership as described there: https://github.com/MISP/MISP/issues/2372#issuecomment-358790301

**Comment by zero3228** [comment] 2018-10-01 08:29
![image](https://user-images.githubusercontent.com/13799256/46277862-bb1bf680-c58e-11e8-8eaf-f2b486662e02.png)

**Comment by jasonzio** [comment] 2018-11-30 23:31
Expected behavior. Here's why.

At the point of failure, gen-key is about to ask the user for a passphrase. For security purposes, rather than using stdin/stdout, it wants to directly open the controlling terminal for the session and use that handle to write the prompt and receive the passphrase. When you use su to switch to some other user, the owner of the controlling terminal device file _does not change_; it remains associated with the user who actually logged in (i.e. received a real terminal from getty or got a pty from telnet or ssh or whatever). That device file is protected mode 600, so it can't be opened by anyone else.

The solution is to sudo-chown the device file to the user-who-needs-to-gen-the-key _before_ su'ing to that user. Create the key within the su'd environment, then exit back to the original environment. Then, finally, sudo-chown the terminal back to yourself.

**Comment by SteveClement** [comment] 2019-01-07 05:27
@5730325021-PT closing this issue, I assume it is solved.

If not feel free to check out [gitter](https://gitter.im/MISP/MISP)

**Closed as completed by SteveClement** 2019-01-07 05:27 UTC
Labels: T: support

**Comment by joncard1** [comment] 2020-09-21 19:15
~~So, service accounts that need to store passwords can't use the password manager because they can't set it up without sudo. Got it. This is a dumb security feature.~~

Maybe more helpfully, running tmux allowed this to succeed.

**Comment by jpmcneely** [comment] 2021-01-12 13:42
Agree with joncard1 - should be able to make a key for/with a service account without chowning the pty.  Reason for fail is not obvious, and error text does not indicate what required permission is not in place.  Not a good user experience at all.

**Comment by eschoeller** [comment] 2021-06-03 00:24
Thanks for the tmux tip. That was really handy. And agreed ... this was a terrible user experience.

**Comment by matimuchauke** [comment] 2024-11-05 19:49
On ubuntu 20.04 : I just created a [screen](https://www.gnu.org/software/screen/manual/screen.html) which comes with the distribution and no need to install third party multiplexers.

```
sudo su www-data
screen
sudo gpg --generate-key
```

**Comment by LM1LC3N7** [comment] 2025-01-17 18:12
> On ubuntu 20.04 : I just created a [screen](https://www.gnu.org/software/screen/manual/screen.html) which comes with the distribution and no need to install third party multiplexers.
> 
> ```
> sudo su www-data
> screen
> sudo gpg --generate-key
> ```

Thanks that was really useful to me. I had this issue running the command from a proxmox LXC, connected using `pct enter 109`, so probably a tty issue for gpg.

**Comment by scholtz** [comment] 2025-02-03 07:33
for me this helped:

```
sudo su www-data
screen
gpg --generate-key
```

the screen command somehow fixes it

**Comment by Jhaempyre** [comment] 2025-03-06 09:09
> Expected behavior. Here's why.
> 
> At the point of failure, gen-key is about to ask the user for a passphrase. For security purposes, rather than using stdin/stdout, it wants to directly open the controlling terminal for the session and use that handle to write the prompt and receive the passphrase. When you use su to switch to some other user, the owner of the controlling terminal device file _does not change_; it remains associated with the user who actually logged in (i.e. received a real terminal from getty or got a pty from telnet or ssh or whatever). That device file is protected mode 600, so it can't be opened by anyone else.
> 
> The solution is to sudo-chown the device file to the user-who-needs-to-gen-the-key _before_ su'ing to that user. Create the key within the su'd environment, then exit back to the original environment. Then, finally, sudo-chown the terminal back to yourself.

honoureddd to youu..... it actually worked . Thanks for the new knowledge in bucket ..
