### ISSUE TITLE
Enforce unique attribute values within an event

### ISSUE THREAD

**Issue by ag-michael** [MISP/MISP#6936] opened 2021-01-31 22:19 UTC
**Is your feature request related to a problem? Please describe.**
I have an event that is updated using a feed. The feed will have the same IOCs each time it is pulled, this has resulted in multiple attributes in the event with identical values.

When you search for the attribute value, to find out what tag applies to it, the sighting, the decay score and other properties, I am not certain which attribute the result would be for. To avoid this, non-feed attribute sources (TAXII feeds for now) have to manually search MISP for each attribute value they receive and exclude it from being pushed into MISP if it already exists.  This already has a very high performance impact on MISP.

**Describe the solution you'd like**

Ideally, MISP would allow configuring the enforcement of unique attribute values.  At the time an attribute is added, if this option is configured in MISP the adding of the the attribute would result in an error letting the client know the attribute exists already. It is fine to have the same attribute value in different events because that's the whole point of correlation,but it doesn't make much sense to repeat the same value in the same event, or at lest it doesn't make much sense in my use-case and it would solve a lot of problems if there was a way to enforce uniqueness of attributes.

**Describe alternatives you've considered**

Not my idea but @iglocska  has suggested adding a massive unique index for the tuple of things that should stay unique with something like:

```
ALTER TABLE `attributes` ADD UNIQUE `attribute_unique_index`(`value1`, `value2`, `type`, `category`, `event_id`, `object_id`);
```

**Comment by JakubOnderka** [comment] 2021-02-01 09:57
Hello, there is already check for that:

https://github.com/MISP/MISP/blob/c768b9372a231782a878ecb80b9586f158dbcd79/app/Model/Attribute.php#L632

So maybe it just doesn't work?

**Comment by iglocska** [comment] 2021-02-01 12:46
Kinda. There is that check indeed, which gets the job down 99% of the time, but due to concurrency you might have an issue where 2 attributes being inserted both meet the requirements during validation, if it happens before the actual saving takes place in both cases.

That is just my guess what happened here. In order to avoid that our only real solution is to have something in place on the DB level such as the suggestion above.

**Comment by JakubOnderka** [comment] 2021-02-01 15:15
@iglocska Yes, thats true, but @ag-michael says that this happen for feeds and there is no concurrency when fetching feed. So I think the problem must be somewhere else. 

@ag-michael Is your feed public? Or can you provide example what attributes values are duplicated?

**Comment by iglocska** [comment] 2021-02-01 15:57
It's taxii feeds, pretty sure it's some external script doing the feeding ;)

**Comment by ag-michael** [comment] 2021-02-01 22:48
@iglocska  @JakubOnderka  This is actually a feed, my taxii scripts do a good job (at a performance cost) of removing duplicates. 

This is the feed `https://raw.githubusercontent.com/brakmic/Sinkholes/master/Sinkholes_List.csv`

Screenshot of duplicates (note the timestamp):

![image](https://user-images.githubusercontent.com/39683291/106527646-3bc7c600-64ad-11eb-9f49-9a2faac00c86.png)

Maybe I should have created a bug report instead? 

Here is the feed config json:

```
{
    "Feed": {
        "id": "66",
        "name": "Sinkhole Subnets",
        "provider": "Public Information",
        "url": "https:\/\/raw.githubusercontent.com\/brakmic\/Sinkholes\/master\/Sinkholes_List.csv",
        "rules": "{\"tags\":{\"OR\":[],\"NOT\":[]},\"orgs\":{\"OR\":[],\"NOT\":[]},\"url_params\":\"\"}",
        "enabled": true,
        "distribution": "3",
        "sharing_group_id": "0",
        "tag_id": "0",
        "default": false,
        "source_format": "csv",
        "fixed_event": true,
        "delta_merge": true,
        "event_id": "18091",
        "publish": true,
        "override_ids": true,
        "settings": "{\"csv\":{\"value\":\"2\",\"delimiter\":\",\"},\"common\":{\"excluderegex\":\"\"}}",
        "input_source": "network",
        "delete_local_file": false,
        "lookup_visible": true,
        "headers": "Organization\r\nIP Range\r\nWhois\r\nNotes",
        "caching_enabled": true,
        "force_to_ids": false,
        "orgc_id": "1",
        "cached_elements": 68,
        "coverage_by_other_feeds": "0%"
    }
}
```

**Comment by JakubOnderka** [comment] 2021-02-02 08:53
@ag-michael Thats very nice bug report, thanks! 

I think the main problem is that the value `212.227.55.84` is duplicated in the feed, but even then value should not be duplicated. I just tested on my instance and the value is not duplicated. What MISP version do you use?

**Comment by ag-michael** [comment] 2021-02-03 02:55
@JakubOnderka , 

I am running MISP 2.4.135 (ce96003b8997e348ed3b0870162c590fb734e5b1) , I believe we upgraded to this version several weeks ago, soon after it was released. we have been on this version since and I believe we upgraded from 2.4.134.

**Comment by iglocska** [comment] 2021-02-03 07:51
Wow, ok that is indeed weird!

**Comment by iglocska** [comment] 2021-02-03 07:59
Hmm, Just tried to reproduce it via that feed and I'm not getting any duplicates.

**Comment by iglocska** [comment] 2021-02-03 08:03
Yeah, no luck with c396003 either, this is weird.

**Comment by ag-michael** [comment] 2021-02-03 15:38
@iglocska  perhaps the caching is the problem or some gradual change in the source feed? 

Do you think your original proposal will avert scenarios like this?

**Comment by ag-michael** [comment] 2021-03-05 04:24
@iglocska @JakubOnderka any update on this?

**Comment by adulau** [comment] 2022-09-01 11:55
@ag-michael is it something solved? I'll close the issue but feel free to re-open if this is not the case. Thanks!

**Closed as completed by adulau** 2022-09-01 11:55 UTC
Labels: T: feature request
