### ISSUE TITLE
Error: Missing Controller

### ISSUE THREAD

**Issue by advancedeng** [MISP/MISP#717] opened 2015-11-15 16:25 UTC
Hi there,

Whilre trying to search for a specific IoC -> hxxps://misptest[.]com/insecure[.]js  
(please deobfuscate when searching in the main event page)
## I got the following error:

Missing Controller

Error: Controller could not be found.

Error: Create the class Controller below in file: app/Controller/Controller.php

<?php
class Controller extends AppController {

}

Notice: If you want to customize this error message, create app/View/Errors/missing_controller.ctp
Stack Trace

```
APP/webroot/index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)

App::uses('Dispatcher', 'Routing');

$Dispatcher = new Dispatcher();
$Dispatcher->dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding'))));
```

---

Cheers,
Andreas

**Comment by iglocska** [comment] 2015-11-15 21:52
Hello Andreas,

how are you searching for it? Is it via the API? If so, the problem is that slashes will be interpreted as a different parameter. Passing values via url parameters can cause all sorts of similar issues, so the best way to do it is to POST a json object at the API, as you don't have to worry about the limitations of a url then.

So as an example:

Instead of:

`https://my_misp_url/attributes/restSearch/download/hxxps://misptest[.]com/insecure[.]js`

use:

`https://my_mis_url/attributes/restSearch/download`

and POST the following body:

`{"request": {"value":"hxxps://misptest[.]com/insecure[.]js"}}`

Let me know if this isn't what you've meant!

Best regards,
Andras

**Comment by advancedeng** [comment] 2015-11-16 11:29
Hi Andras, 

It is not via the API! In the main event home page, I manually use the uper right filter search form.

Cheers,
Andreas

**Comment by iglocska** [comment] 2015-11-16 11:42
Oh wow, I see! I'll have a fix for that later today, will keep you posted here.

**Comment by iglocska** [comment] 2015-11-16 21:47
This actually seems a bit trickier than I first thought... Will try to find a usable solution for it asap, for now just use the search attributes feature please!

**Comment by adulau** [comment] 2017-10-22 09:49
Not really sure if this was fixed with the recent changes. @iglocska

**Comment by adulau** [comment] 2018-01-18 14:00
We will close the issue. Let us know if this is fixed and feel free to reopen the issue if this is not fixed.

**Closed by adulau** 2018-01-18 14:00 UTC
Labels: potential-bug
