### ISSUE TITLE
First number of ip-dst|port attribute is replace by a colon (:)

### ISSUE THREAD

**Issue by wilson-santos-pf** [MISP/MISP#2534] opened 2017-10-04 16:30 UTC
An attribute with the type ip-dst|port or ip-src|port  gets its first number replaced by a colon (:)
This seems to be a display problem, because fetching the event with PyMISP gets the expected attribute value.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Debian
| PHP version               | 7.0.19-1
| MISP version   | 2.4.80

### Expected behavior
172.234.42.65|80

### Actual behavior
:72.234.42.65|80

### Steps to reproduce the behavior
Create an attribute with the category "Network activity" and type "ip-dst|port" or "ip-src|port"

**Comment by RichieB2B** [comment] 2017-10-04 17:43
In which view do you see this? Can you share a screenshot?

**Comment by wilson-santos-pf** [comment] 2017-10-05 08:01
@RichieB2B 
When viewing the event's details (/events/view/**_id_**)
![image](https://user-images.githubusercontent.com/22000887/31216447-f856c4c8-a9b3-11e7-94d4-82f4b3eab19e.png)

**Comment by iglocska** [comment] 2017-10-05 08:32
What the hell. I can't seem to be able to reproduce it... Which browser is it? Can't think of anything else :) (though it looks like the | to : replacement fails on your end for the view for some reason - no clue how.)

**Comment by adulau** [comment] 2017-10-05 08:40
I cannot reproduce on recent version. Could you do a `git pull`? Just to be sure that we are on the same version. Thanks a lot.

**Comment by wilson-santos-pf** [comment] 2017-10-05 09:13
It happens both on Firefox (45.9.0) and Google Chrome (59.0.3071.115)
It also happens if the attribute is created on the web interface or via the API (PyMISP)
Also I have two MISP instances, on different servers, and both have this display problem.

@adulau at the moment I cannot git pull. I don't have permissions to change the server.

**Comment by iglocska** [comment] 2017-10-05 09:15
Ah ok. There was an issue when 2.4.80 was released but it should be fixed. Are you a site admin? You can also git pull via the diagnostics page.

**Comment by wilson-santos-pf** [comment] 2017-10-05 09:28
@iglocska I am a site admin. However, the last time we upgraded we lost some configurations (eg, taxonomies). Is this always the case?

**Comment by iglocska** [comment] 2017-10-05 10:05
Custom taxonomies?

**Comment by wilson-santos-pf** [comment] 2017-10-05 10:50
Yes, and some taxonomies add to be re-enabled.

**Comment by iglocska** [comment] 2017-10-05 10:55
Hmm, I see. We generally don't use custom taxonomies so I never noticed the issue. Will look into adding an alternate directory for custom stuff so that it doesn't get overwritten.

**Comment by RichieB2B** [comment] 2017-10-05 11:30
We use custom taxonomies and they are simply new files that git ignores. We never had an issue with them being removed on updates. 

Now if you edited files that are managed by git those changes might indeed be overwritten.

**Comment by iglocska** [comment] 2017-10-05 11:44
Thanks for the heads-up @RichieB2B, was wondering how to reproduce it already ;)

**Comment by ppanero** [comment] 2017-10-20 09:32
Could reproduce. Only in 2.4.80, not in 2.4.81

**Comment by Rafiot** [comment] 2019-07-19 09:07
Composite attributes are deprecated.

**Closed as completed by Rafiot** 2019-07-19 09:07 UTC
Labels: T: bug
