### ISSUE TITLE
Virustotal enrichment problem

### ISSUE THREAD

**Issue by Mokatani** [MISP/MISP#2029] opened 2017-03-08 13:28 UTC
Hi everyone,
i tried to use VirusTotal enrichment feature in our MISP, i have enabled the feature and give thee API key in MISP setting. When i enrich an attribute with virustotal then i receive an error "Something went wrong, look in the server logs for details". I have search all available logs in MISP but have not seen any log related to the virustotal. Can you please advice me how can i find the related log?

MISP version : 2.4.66
Virustotal plugin ver : 2.0 (latest version)

Thanks and best regards,
Mohammad

**Comment by FloatingGhost** [comment] 2017-03-08 13:31
oh no I have a feeling that's my thing.

Are you on about the MISP-Modules expansion thing?

**Comment by Mokatani** [comment] 2017-03-08 13:46
Hi, 
Yes correct i am trying to use MISP-Modules :)

**Comment by FloatingGhost** [comment] 2017-03-08 13:47
:< That actually is my thing

The log should be printed to STDOUT wherever you're running your modules server - let's hope it's been nice and told you the error

**Comment by Mokatani** [comment] 2017-03-08 15:12
Ok
i have killed all misp-modules and then i have run it again,
First try i have seen this LOGS:
 ```
Traceback (most recent call last):
 File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/virustotal.py", line 31, in handler
    limit = int(q["config"].get("event_limit", 5))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/virustotal.py", line 31, in handler
    limit = int(q["config"].get("event_limit", 5))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
then i have changed the "Plugin.Enrichment_virustotal_event_limit" but now when i try to enrich an attribute i dont see any LOG and dont see any Result and no Error :)

Does this work behind a proxy? We see your request-call, but it has no proxy. Is there a proxy wrapped around it?

Thanks

**Comment by FloatingGhost** [comment] 2017-03-08 15:42
It's quite possible that there's just nothing on VT for your query - does MISP refer you to a blank results page?

**Comment by Mokatani** [comment] 2017-03-09 10:00
Hi again,
thanks, now it works but :)
I have tried with domain attribute and when i search this domain in VT web i see some result but in MISP i dont see the result that i see in WEB.
Here the example domain: likemellc[.]org
Or this IP: 136[.]243[.]104[.]200

And many other attributes and i see different error each time :)

Thanks and best regards,
Mohmmad

**Comment by FloatingGhost** [comment] 2017-03-09 10:15
>when i search this domain in VT web i see some result but in MISP i dont see the result that i see in WEB.

Yes, this is a limitation of the API - the `search` call on VT's API only actually goes through the last 30 or so days, whereas the web front-end will search a much larger dataset.

This is to be expected.

>And many other attributes and i see different error each time

If you have errors, paste them here and I'll try my best to fix them

**Comment by Mokatani** [comment] 2017-03-09 12:58
For example: likemellc[.]org
in our first instance i receive error "Enrichment service not reachable..."
in our second instance: "Something went wrong, look in the server logs for details"

Only recommendation: Is not better that we see another error message if there is not any result in VT? 
IS not possible to enrich URI attribute right?

Thanks again,
Mohammad

**Comment by FloatingGhost** [comment] 2017-03-09 13:02
>in our first instance i receive error "Enrichment service not reachable..."
>in our second instance: "Something went wrong, look in the server logs for details"

I can't help you without the server logs

>Is not better that we see another error message if there is not any result in VT?

No, the API will happily throw back an empty array, this is expected behaviour

**Comment by Mokatani** [comment] 2017-03-09 13:19
Ok,
I have tried the same attribute in two instances that we have (likemellc[.]org)
here for the first instance with error message "Enrichment service not reachable..."

``
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/virustotal.py", line 40, in handler
    r["results"] += getDomain(q["domain"], key)
  File "modules/expansion/virustotal.py", line 125, in getDomain
    toReturn += getIP(res["ip_address"], key, True)
  File "modules/expansion/virustotal.py", line 84, in getIP
    req = req.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/virustotal.py", line 40, in handler
    r["results"] += getDomain(q["domain"], key)
  File "modules/expansion/virustotal.py", line 125, in getDomain
    toReturn += getIP(res["ip_address"], key, True)
  File "modules/expansion/virustotal.py", line 84, in getIP
    req = req.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``

here LOG for the second instance with error message "Something went wrong, look in the server logs for details"

``
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/virustotal.py", line 40, in handler
    r["results"] += getDomain(q["domain"], key)
  File "modules/expansion/virustotal.py", line 125, in getDomain
    toReturn += getIP(res["ip_address"], key, True)
  File "modules/expansion/virustotal.py", line 84, in getIP
    req = req.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:misp-modules:Something went wrong:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 197, in post
    response = yield tornado.gen.with_timeout(timeout, self.run_request(jsonpayload))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/misp_modules/__init__.py", line 185, in run_request
    response = mhandlers[x['module']].handler(q=jsonpayload)
  File "modules/expansion/virustotal.py", line 40, in handler
    r["results"] += getDomain(q["domain"], key)
  File "modules/expansion/virustotal.py", line 125, in getDomain
    toReturn += getIP(res["ip_address"], key, True)
  File "modules/expansion/virustotal.py", line 84, in getIP
    req = req.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``

Thanks,
Mohammad

**Comment by FloatingGhost** [comment] 2017-03-09 13:50
Works for me. 

You're getting JSON decode errors, which implies to me that you may be at rate limit or some other exceptional status. Try running the API call manually with `
curl -XGET "https://www.virustotal.com/vtapi/v2/domain/report?domain=likemellc.org&apikey=<YOURKEY>"` and post the result here.

To avoid the "Not reachable" error for non-json related issues, I'd advise turning up the timeout (Administration -> Server Settings -> Plugin Settings -> Enrichment Settings -> Plugin.enrichment_Timeout) - I set mine to 60, but it's up to you.

**Comment by Mokatani** [comment] 2017-03-09 15:20
Here the result:
``
curl -XGET "https://www.virustotal.com/vtapi/v2/domain/report?domain=likemellc.org&apikey=Here was my API key"

{"domain_siblings": [], "BitDefender domain info": "This URL domain/host was seen to host badware at some point in time", "whois": null, "response_code": 1, "detected_urls": [{"url": "http://likemellc.org/", "positives": 8, "total": 66, "scan_date": "2017-03-07 02:18:17"}, {"url": "http://likemellc.org/evueiwsvps.exe", "positives": 7, "total": 64, "scan_date": "2017-02-14 06:41:30"}, {"url": "http://likemellc.org/oBaNrPmIyG.php", "positives": 5, "total": 68, "scan_date": "2017-01-21 04:20:45"}, {"url": "http://likemellc.org/obanrpmiyg.php", "positives": 1, "total": 68, "scan_date": "2017-01-20 01:41:52"}], "verbose_msg": "Domain found in dataset", "Websense ThreatSeeker category": "malicious web sites", "resolutions": [{"last_resolved": "2017-01-21 00:00:00", "ip_address": "109.108.253.190"}, {"last_resolved": "2017-01-19 00:00:00", "ip_address": "109.108.73.131"}, {"last_resolved": "2017-01-23 00:00:00", "ip_address": "109.200.147.143"}, {"last_resolved": "2017-01-25 00:00:00", "ip_address": "178.150.110.220"}, {"last_resolved": "2017-01-21 00:00:00", "ip_address": "212.2.153.190"}, {"last_resolved": "2017-01-20 00:00:00", "ip_address": "46.173.89.91"}, {"last_resolved": "2017-01-20 00:00:00", "ip_address": "5.58.92.52"}, {"last_resolved": "2017-01-20 00:00:00", "ip_address": "87.97.165.217"}, {"last_resolved": "2017-01-20 00:00:00", "ip_address": "96.50.181.81"}], "Dr.Web category": "known infection source", "categories": ["malicious web sites", "known infection source"]}``

Thanks

**Comment by FloatingGhost** [comment] 2017-03-09 15:54
Seems to all be working then

**Comment by adulau** [comment] 2017-06-17 15:03
We will close the issue. Don't hesitate to reopen it if there is a need. Thank you.

**Closed as completed by adulau** 2017-06-17 15:03 UTC
