### ISSUE TITLE
invalid dates (valid_from, valid_until) in exported STIX 2.0 files 

### ISSUE THREAD

**Issue by girdav01** [MISP/MISP#7327] opened 2021-04-12 13:53 UTC
Hi, when I tried to use exported STIX2 files from MISP, the files include invalid dates that make them unusable in other systems.

Milliseconds are missing in valid_from and valid_until

example :
	"created_by_ref": "identity--2a76e61b-d643-4d5f-aa0a-12016d16d106",
			"pattern": "[domain-name:value = 'smalleststores.com']",
			"created": "2021-03-29T18:49:25.000Z",
			"modified": "2021-03-29T18:49:25.000Z",    
			"valid_from": "2021-03-29T18:49:25Z",      #milliseconds missing
			"valid_until": "2021-03-29T18:49:25Z"        #milliseconds missing

Expected : STIX 2.0 require 3 digits and valid_from and valid_until should be "2021-03-29T18:49:25.123Z" exactly like created and modified

Development Environment 
MISP 2.4.141 VM  upgraded from MISP_v2.4.133@da7e410
I use both Windows 10 (2004) and Ubuntu 18.04.2 for development
I use pyMISP 2.4.141.1
python 3.7

I retrieve the stix file this way 
        payload = {
            "returnFormat": 'json',
            "eventid": eventid
        }
        stix = requests.post(misp_url + 'events/restSearch', headers=self.headers, data=payload, verify=misp_verify)

Thanks

David

**Comment by chrisr3d** [comment] 2021-04-28 16:45
I hope this has been fixed with f098dba
Let me know if it works as intended now for you or reopen the issue otherwise

**Closed as completed by chrisr3d** 2021-04-28 16:45 UTC
Labels: T: support, topic: stix
