### ISSUE TITLE
CISCP STIX Import failing intermittently

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4575] opened 2019-05-06 18:59 UTC
Question re' STIX CISCP import. Some xml files work; others fail.

Not sure if root cause is file content, library version in MISP, or something else. All help appreciated!! Thx...

Those that fail, do not pass `best-practices` on `stix-validator` (https://github.com/STIXProject/stix-validator). Same failures on MISP 2.4.102, and 2.4.106. I did see mention in RelNotes for .105 of CISCP support. I also noticed on .../servers/serverSettings/diagnostics
```
STIX2 library version…Incorrect STIX2 version installed, found 1.1.1, expecting 1.1.2
```
How can I get STIX2 lib to 1.1.2 on 2.4.106; and also 
on my 2.4.102 I see
```
CYBOX library version…Incorrect CyBox version installed, found 2.1.0.17, expecting 2.1.0.18.dev0
```

**Comment by github-germ** [comment] 2019-05-06 19:00
From 2.4.102
```
root@misp-Lab1:/var/www/MISP/app/tmp/logs tail -f --lines=0 exec-errors.log
/usr/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'StructuredTextList' object.
  warnings.warn(msg)
/usr/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/usr/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/usr/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
TOUMarking:TermsOfUseMarkingStructureType
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1210, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1205, in main
    stix_parser.build_misp_dict(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 988, in build_misp_dict
    self.parse_external_indicators(self.event.indicators)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1056, in parse_external_indicators
    self.parse_external_single_indicator(indicator)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1066, in parse_external_single_indicator
    attribute_type, attribute_value, compl_data = self.handle_attribute_type(properties)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 195, in handle_attribute_type
    return self.attribute_types_mapping[xsi_type](*args)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 272, in handle_email_attribute
    attributes.append(self.handle_email_attachment(properties.parent))
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 278, in handle_email_attachment
    properties = indicator_object.related_objects[0].properties
TypeError: 'NoneType' object is not subscriptable
```

**Comment by github-germ** [comment] 2019-05-06 19:01
```
$ stix-validator.py --best-practices *10045*
[-] Performing xml schema validation on IB-19-10045.xml
[-] Performing best practice validation on IB-19-10045.xml
================================================================================
[-] Results: IB-19-10045.xml
[+] XML Schema: True
[!] Best Practices: False
    [!] ID Format
        [-] line : 2
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : IB-19-10045
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}STIX_Package
        --------------------------------------------------------------------------------
        [-] line : 27
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : indicator-15579ce1-3924-11e9-b94a-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        --------------------------------------------------------------------------------
        [-] line : 62
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : indicator-dbeec8e1-3935-11e9-bb7b-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        --------------------------------------------------------------------------------
        [-] line : 116
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : indicator-d37bd7ee-394b-11e9-ba99-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        --------------------------------------------------------------------------------
        [-] line : 169
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : indicator-59c91fde-3954-11e9-9e13-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        --------------------------------------------------------------------------------
        [-] line : 223
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : indicator-e24b178f-395b-11e9-b6dd-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        --------------------------------------------------------------------------------
        [-] line : 251
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : indicator-68563851-3962-11e9-9f2f-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        --------------------------------------------------------------------------------
        [-] line : 291
        [-] message : ID should be formatted as [ns prefix]:[construct type]-[GUID]
        [-] id : indicator-22745aa1-396d-11e9-a82a-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
    [!] Indicator Suggestions
        [-] line : 27
        [-] message : None
        [-] id : indicator-15579ce1-3924-11e9-b94a-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        [-] missing : ['Valid_Time_Position', 'Indicated_TTP', 'Confidence']
        --------------------------------------------------------------------------------
        [-] line : 62
        [-] message : None
        [-] id : indicator-dbeec8e1-3935-11e9-bb7b-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        [-] missing : ['Valid_Time_Position', 'Indicated_TTP', 'Confidence']
        --------------------------------------------------------------------------------
        [-] line : 116
        [-] message : None
        [-] id : indicator-d37bd7ee-394b-11e9-ba99-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        [-] missing : ['Valid_Time_Position', 'Indicated_TTP', 'Confidence']
        --------------------------------------------------------------------------------
        [-] line : 169
        [-] message : None
        [-] id : indicator-59c91fde-3954-11e9-9e13-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        [-] missing : ['Valid_Time_Position', 'Indicated_TTP', 'Confidence']
        --------------------------------------------------------------------------------
        [-] line : 223
        [-] message : None
        [-] id : indicator-e24b178f-395b-11e9-b6dd-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        [-] missing : ['Valid_Time_Position', 'Indicated_TTP', 'Confidence']
        --------------------------------------------------------------------------------
        [-] line : 251
        [-] message : None
        [-] id : indicator-68563851-3962-11e9-9f2f-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        [-] missing : ['Valid_Time_Position', 'Indicated_TTP', 'Confidence']
        --------------------------------------------------------------------------------
        [-] line : 291
        [-] message : None
        [-] id : indicator-22745aa1-396d-11e9-a82a-0050569c6b2d
        [-] idref : None
        [-] tag : {http://stix.mitre.org/stix-1}Indicator
        [-] missing : ['Valid_Time_Position', 'Indicated_TTP', 'Confidence']
$ 
```

**Comment by github-germ** [comment] 2019-05-06 19:06
From 2.4.106:
```
root@misp:/var/www/MISP/app/tmp/logs# cat exec-errors.log
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'StructuredTextList' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
TOUMarking:TermsOfUseMarkingStructureType
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1233, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1228, in main
    stix_parser.build_misp_dict(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 993, in build_misp_dict
    self.parse_external_indicators(self.event.indicators)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1061, in parse_external_indicators
    self.parse_external_single_indicator(indicator)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1071, in parse_external_single_indicator
    attribute_type, attribute_value, compl_data = self.handle_attribute_type(properties)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 200, in handle_attribute_type
    return self.attribute_types_mapping[xsi_type](*args)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 277, in handle_email_attribute
    attributes.append(self.handle_email_attachment(properties.parent))
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 283, in handle_email_attachment
    properties = indicator_object.related_objects[0].properties
TypeError: 'NoneType' object is not subscriptable
root@misp:/var/www/MISP/app/tmp/logs#
```

**Comment by github-germ** [comment] 2019-05-06 19:45
FYI, I did the following as per https://github.com/MISP/MISP/issues/4378#issuecomment-480193409 and the same CISCP file fails STIX import.
```
root@misp:/var/www/MISP/cti-python-stix2# pip3 install -U .
Processing /var/www/MISP/cti-python-stix2
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.6/dist-packages (from stix2==1.1.2)
Collecting pytz (from stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 332kB/s
Collecting requests (from stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 352kB/s
Collecting simplejson (from stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz (81kB)
    100% |████████████████████████████████| 81kB 431kB/s
Collecting six (from stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting stix2-patterns (from stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/c9/95/2ed814e9d93110b10b7afade3c53358618d3121f184f83b935e900b38f9e/stix2_patterns-1.1.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 546kB/s
Collecting certifi>=2017.4.17 (from requests->stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 233kB/s
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->stix2==1.1.2)
Collecting idna<2.9,>=2.5 (from requests->stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 344kB/s
Collecting antlr4-python3-runtime>=4.7; python_version >= "3" (from stix2-patterns->stix2==1.1.2)
  Downloading https://files.pythonhosted.org/packages/29/14/8ac135ec7cc9db3f768e2d032776718c6b23f74e63543f0974b4873500b2/antlr4-python3-runtime-4.7.2.tar.gz (112kB)
    100% |████████████████████████████████| 112kB 102kB/s
Building wheels for collected packages: stix2, simplejson, antlr4-python3-runtime
  Running setup.py bdist_wheel for stix2 ... done
  Stored in directory: /root/.cache/pip/wheels/56/53/71/3082949580400d343ff20c4736be4b14e7bb05f3d18afb4160
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /root/.cache/pip/wheels/5d/1a/1e/0350bb3df3e74215cd91325344cc86c2c691f5306eb4d22c77
  Running setup.py bdist_wheel for antlr4-python3-runtime ... done
  Stored in directory: /root/.cache/pip/wheels/03/65/47/b6700d23b7529a49513f7601b4f96174a4fa9efdbec03e7ea3
Successfully built stix2 simplejson antlr4-python3-runtime
Installing collected packages: pytz, urllib3, certifi, idna, requests, simplejson, six, antlr4-python3-runtime, stix2-patterns, stix2
  Found existing installation: urllib3 1.22
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: certifi 2018.1.18
    Not uninstalling certifi at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: idna 2.6
    Not uninstalling idna at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: requests 2.18.4
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: six 1.11.0
    Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed antlr4-python3-runtime-4.7.2 certifi-2019.3.9 idna-2.8 pytz-2019.1 requests-2.21.0 simplejson-3.16.0 six-1.12.0 stix2-1.1.2 stix2-patterns-1.1.0 urllib3-1.24.3
root@misp:/var/www/MISP/cti-python-stix2#
```

**Comment by chrisr3d** [comment] 2019-05-08 09:54
Hello,

I just tried to reproduce your issue, without success, do you have any sample to share so I can reproduce it ?

Btw:
- Don't worry about cybox library versions, 2.1.0.17 is the latest released version where 2.1.0.18.dev0 has some minor updates that should not affect you. There is no big change anymore since the versions are fixed and no new feature is added to the STIX format.
- cti-python-stix2 library is not related to this issue, because it is about STIX2 format.

**Comment by github-germ** [comment] 2019-05-08 14:03
@chrisr3d -- thx for looking at this! I do not believe I am able to share CISCP content publicly. Do you have access to their files? If so, I could refer you to one of the offending files.

**Comment by iglocska** [comment] 2019-05-10 07:14
No problem, if you cannot share anything there's still something we could do: Could you take a sample that fails from CISCP and replace all values with made up ones so that it still fails the same way but doesn't contain any of the original data? Then we could test it.

Without a way to test we can't really do much to help you ;)

**Comment by github-germ** [comment] 2019-05-10 13:29
Understood. I had tried to anonymize one failed file using QXmlEdit, but that then fails validation. However, I will attach so you can review the XML hierarchy. If you have a better method to anonymize, please let me know. Thanks!!

[Anonymized-IB-19-10045.xml.zip](https://github.com/MISP/MISP/files/3166664/Anonymized-IB-19-10045.xml.zip)

**Comment by chrisr3d** [comment] 2019-05-13 12:43
I managed to parse your STIX file and reproduce the issue. It ended up with an interesting case that was actually not supported, so thank you for reporting it, it should be fixed now with the latest version.
Don't hesitate to poke me again if you have anything broken.

**Comment by github-germ** [comment] 2019-05-13 13:38
EXCELLENT!! I just tested locally with update to the latest in 2.4 branch, and indeed the file failing with 2.4.106 is now succeeding. Thanks a ton.

My org only deploys "official" MISP releases to our Production data center. Any prediction on when 2.4.107 will be released?

**Comment by SteveClement** [comment] 2019-05-13 13:40
@github-germ very soon(tm) ;)
I saw some tagging going on...

**Comment by github-germ** [comment] 2019-05-14 12:43
@chrisr3d -- I just updated to 2.4.107 locally, and that same file which failed in 2.4.106, and then succeeded in the latest 2.4 branch (see above: https://github.com/MISP/MISP/issues/4575#issuecomment-491825950), is now failing.

Did your fix make it into .107?

**Comment by chrisr3d** [comment] 2019-05-14 14:35
Do you have anything in `/var/www/MISP/app/tmp/logs/exec-errors.log` ?

I pushed my changes to 2.4, so if you updated to the latest version, it should still be there, and working.

**Comment by github-germ** [comment] 2019-05-14 14:44
Thx... Here's `exec-errors.log`

```
root@misp:~# tail -f --lines=0 /var/www/MISP/app/tmp/logs/exec-errors.log
tail: /var/www/MISP/app/tmp/logs/exec-errors.log: file truncated
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'StructuredTextList' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'VocabList' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'str' object.
  warnings.warn(msg)
/var/www/MISP/venv/lib/python3.6/site-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
TOUMarking:TermsOfUseMarkingStructureType
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1233, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1228, in main
    stix_parser.build_misp_dict(event)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 993, in build_misp_dict
    self.parse_external_indicators(self.event.indicators)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1061, in parse_external_indicators
    self.parse_external_single_indicator(indicator)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 1071, in parse_external_single_indicator
    attribute_type, attribute_value, compl_data = self.handle_attribute_type(properties)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 200, in handle_attribute_type
    return self.attribute_types_mapping[xsi_type](*args)
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 277, in handle_email_attribute
    attributes.append(self.handle_email_attachment(properties.parent))
  File "/var/www/MISP/app/files/scripts/stix2misp.py", line 283, in handle_email_attachment
    properties = indicator_object.related_objects[0].properties
TypeError: 'NoneType' object is not subscriptable
```

```
root@misp:~# ls -l /var/www/MISP/app/files/scripts/stix2misp.py
-rw-r--r-- 1 root www-data 62288 May 14 14:38 /var/www/MISP/app/files/scripts/stix2misp.py
root@misp:~# 
```

**Comment by github-germ** [comment] 2019-05-14 15:06
```
root@misp:/var/www/MISP/app/files/scripts/python-stix# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
root@misp:/var/www/MISP/app/files/scripts/python-stix#
```

I manually copied the latest from https://raw.githubusercontent.com/MISP/MISP/2.4/app/files/scripts/stix2misp.py to `/tmp/` locally and...
```
root@misp:/var/www/MISP/app/files/scripts# diff /var/www/MISP/app/files/scripts/stix2misp.py /tmp
277c277
<             attributes.append(self.handle_email_attachment(properties.parent))
---
>             attributes.extend(self.handle_email_attachment(properties))
281,284c281,294
<     @staticmethod
<     def handle_email_attachment(indicator_object):
<         properties = indicator_object.related_objects[0].properties
<         return ["email-attachment", properties.file_name.value, "attachment"]
---
>     def handle_email_attachment(self, properties):
>         attributes = []
>         related_objects = {}
>         if properties.parent.related_objects:
>             related_objects = {related.id_: related.properties for related in properties.parent.related_objects}
>         for attachment in (attachment.object_reference for attachment in properties.attachments):
>             if attachment in related_objects:
>                 attributes.append(["email-attachment", related_objects[attachment].file_name.value, "attachment"])
>             else:
>                 parent_id = self.fetch_uuid(properties.parent.id_)
>                 referenced_id = self.fetch_uuid(attachment)
>                 self.references[parent_id].append({'idref': referenced_id,
>                                                    'relationship': 'attachment'})
>         return attributes
766a777,778
>         if self.references:
>             self.build_references()
root@misp:/var/www/MISP/app/files/scripts# 
```

**Comment by chrisr3d** [comment] 2019-05-14 15:07
Yes indeed, the function mentioned in your log file has been updated, this was the object of my fix, so if you still have the same issue with line 283, it means it is not running with the latest version

**Comment by github-germ** [comment] 2019-05-14 15:13
Then I'd appreciate you teaching me how to properly update to the latest. Here's what I did...
```
MispDir='/var/www/MISP'
SudoArg='-u www-data'

cd ${MispDir}/app/files/scripts/
rm -rf python-cybox
sudo ${SudoArg} git clone https://github.com/CybOXProject/python-cybox.git
cd ${MispDir}/app/files/scripts/python-cybox
python3 setup.py install

cd ${MispDir}/app/files/scripts/
rm -rf python-stix
sudo ${SudoArg} git clone https://github.com/STIXProject/python-stix.git
cd ${MispDir}/app/files/scripts/python-stix
python3 setup.py install
```

**Comment by chrisr3d** [comment] 2019-05-14 16:20
Usually:
```
cd /var/www/MISP
git pull origin 2.4
```

If you copied the `stix2misp.py` script directly within `/var/www/MISP/app/files/scripts`, it should fail and warn you that it would overwrite the file.

=> If `git status` does tell you

> nothing to commit, working tree clean

as before, it is ok

Otherwise, if it tells you there is a change on `/var/www/MISP/app/files/scripts/stix2misp.py`, do a `git stash` and then `git pull origin 2.4`.

**Comment by github-germ** [comment] 2019-05-14 17:05
I want the "official" .107 so I didn't use `git pull origin 2.4`, but rather followed `Option 2` https://misp.github.io/MISP/UPDATE/

And...
```
root@misp:/var/www/MISP/app/files/scripts/python-stix# pwd
/var/www/MISP/app/files/scripts/python-stix
root@misp:/var/www/MISP/app/files/scripts/python-stix# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
root@misp:/var/www/MISP/app/files/scripts/python-stix# 
```

* What am I missing?
* Is it possible your `push` was not included in the `master` for 2.4.107?

Thx a lot for working with me on this!!

**Comment by chrisr3d** [comment] 2019-05-15 11:35
I guess it was pushed right after 2.4.107 has been tagged, indeed
So unfortunately, following the commands you have under Option 2 does not give you the fix for this script

**Comment by SteveClement** [comment] 2019-05-23 06:12
Either patch it manually, or just update to the exact commit where this has been fixed.

**Closed as completed by SteveClement** 2019-05-23 06:12 UTC

**Comment by github-germ** [comment] 2019-05-23 13:15
Our operations team only accepts "official" releases. We will wait for 2.4.108. Thanks.
